import os
F = r"D:/WORKSPACE/linux-7.1.3/docs/系统文档\userspace-api/media/v4l/pixfmt-yuv-planar.md"
m = {
"######## Planar YUV formats": "######## 平面 YUV 格式",
"Planar formats split luma and chroma data in separate memory regions. They": "平面格式将亮度（luma）和色度（chroma）数据分割在独立的内存区域中。它们",
"exist in two variants:": "有两种变体：",
"- Semi-planar formats use two planes. The first plane is the luma plane and": "- 半平面（semi-planar）格式使用两个平面。第一个平面是亮度平面，",
"  stores the Y components. The second plane is the chroma plane and stores the": "  存储 Y 分量。第二个平面是色度平面，存储",
"  Cb and Cr components interleaved.": "  Cb 和 Cr 分量交错存储。",
"- Fully planar formats use three planes to store the Y, Cb and Cr components": "- 全平面（fully planar）格式使用三个平面，分别存储 Y、Cb 和 Cr 分量",
"  separately.": "  。",
"Within a plane, components are stored in pixel order, which may be linear or": "在平面内部，分量按像素顺序存储，可以是线性或",
"tiled. Padding may be supported at the end of the lines, and the line stride of": "平铺（tiled）方式。行尾可能支持填充（padding），而色度平面的行跨度（line stride）",
"the chroma planes may be constrained by the line stride of the luma plane.": "可能受亮度平面行跨度的约束。",
"Some planar formats allow planes to be placed in independent memory locations.": "某些平面格式允许平面放置于独立的内存位置。",
"They are identified by an 'M' suffix in their name (such as in": "它们通过名称中的 'M' 后缀来标识（例如",
"`V4L2_PIX_FMT_NV12M`). Those formats are intended to be used only in drivers": "`V4L2_PIX_FMT_NV12M`）。这些格式仅用于支持多平面（multi-planar）API 的驱动",
"and applications that support the multi-planar API, described in": "和应用程序，详见",
"planar-apis. Unless explicitly documented as supporting non-contiguous": "planar-apis。除非明确说明支持非连续",
"planes, formats require the planes to follow each other immediately in memory.": "平面，否则格式要求各平面在内存中紧邻排列。",
"## Semi-Planar YUV Formats": "## 半平面 YUV 格式",
"These formats are commonly referred to as NV formats (NV12, NV16, ...). They": "这些格式通常被称为 NV 格式（NV12、NV16……）。它们",
"use two planes, and store the luma components in the first plane and the chroma": "使用两个平面，将亮度分量存储在第一个平面，色度",
"components in the second plane. The Cb and Cr components are interleaved in the": "分量存储在第二个平面。Cb 和 Cr 分量在色度平面中交错存储，",
"chroma plane, with Cb and Cr always stored in pairs. The chroma order is": "且 Cb 与 Cr 始终成对存储。色度顺序",
"exposed as different formats.": "通过不同的格式来体现。",
"For memory contiguous formats, the number of padding pixels at the end of the": "对于内存连续格式，色度行尾的填充像素数与",
"chroma lines is identical to the padding of the luma lines. Without horizontal": "亮度行的填充相同。在没有水平子采样的情况下，",
"subsampling, the chroma line stride (in bytes) is thus equal to twice the luma": "色度行跨度（以字节计）等于亮度行跨度的两倍。在",
"line stride. With horizontal subsampling by 2, the chroma line stride is equal": "水平子采样为 2 时，色度行跨度等于亮度行跨度。",
"to the luma line stride. Vertical subsampling doesn't affect the line stride.": "垂直子采样不影响行跨度。",
"For non-contiguous formats, no constraints are enforced by the format on the": "对于非连续格式，格式不会约束",
"relationship between the luma and chroma line padding and stride.": "亮度与色度行的填充及跨度之间的关系。",
"All components are stored with the same number of bits per component.": "所有分量均以相同的每分量位数存储。",
"    - - Identifier": "    - - 标识符",
"      - Code": "      - 编码",
"      - Bits per component": "      - 每分量位数",
"      - Subsampling": "      - 子采样",
"      - Chroma order [^1^]_": "      - 色度顺序 [^1^]_",
"      - Contiguous [^2^]_": "      - 连续 [^2^]_",
"      - Tiling [^3^]_": "      - 平铺 [^3^]_",
"**Color Sample Location:**": "**色采样位置：**",
"Chroma samples are interstitially sited<yuv-chroma-centered>": "色度采样",
"horizontally.": "在水平方向上位于像素间隙（interstitially sited）<yuv-chroma-centered>。",
"### NV12, NV21, NV12M and NV21M": "### NV12、NV21、NV12M 与 NV21M",
"Semi-planar YUV 4:2:0 formats. The chroma plane is subsampled by 2 in each": "半平面 YUV 4:2:0 格式。色度平面在每个方向上子采样 2 倍。",
"direction. Chroma lines contain half the number of pixels and the same number": "色度行包含亮度行一半数量的像素和相同数量的",
"of bytes as luma lines, and the chroma plane contains half the number of lines": "字节，色度平面包含亮度平面一半数量的",
"of the luma plane.": "行。",
"### NV15": "### NV15",
"Semi-planar 10-bit YUV 4:2:0 format similar to NV12, using 10-bit components": "半平面 10 位 YUV 4:2:0 格式，类似于 NV12，使用 10 位分量",
"with no padding between each component. A group of 4 components are stored over": "且各分量之间无填充。每组 4 个分量",
"5 bytes in little endian order.": "以小端（little endian）顺序存储于 5 个字节中。",
"### Tiled NV12": "### 平铺 NV12",
"Semi-planar YUV 4:2:0 formats, using macroblock tiling. The chroma plane is": "半平面 YUV 4:2:0 格式，采用宏块（macroblock）平铺。色度平面",
"subsampled by 2 in each direction. Chroma lines contain half the number of": "在每个方向上子采样 2 倍。色度行包含",
"pixels and the same number of bytes as luma lines, and the chroma plane": "亮度行一半数量的像素和相同数量的字节，色度平面",
"contains half the number of lines of the luma plane. Each tile follows the": "包含亮度平面一半数量的行。每个瓦片（tile）在内存中",
"previous one linearly in memory (from left to right, top to bottom).": "线性紧随前一个（从左到右、从上到下）。",
"`V4L2_PIX_FMT_NV12MT_16X16` is similar to `V4L2_PIX_FMT_NV12M` but stores": "`V4L2_PIX_FMT_NV12MT_16X16` 与 `V4L2_PIX_FMT_NV12M` 类似，但将",
"pixels in 2D 16x16 tiles, and stores tiles linearly in memory.": "像素以二维 16x16 瓦片存储，并将瓦片在内存中线性排列。",
"The line stride and image height must be aligned to a multiple of 16.": "行跨度与图像高度必须对齐到 16 的倍数。",
"The layouts of the luma and chroma planes are identical.": "亮度平面与色度平面的布局相同。",
"`V4L2_PIX_FMT_NV12MT` is similar to `V4L2_PIX_FMT_NV12M` but stores": "`V4L2_PIX_FMT_NV12MT` 与 `V4L2_PIX_FMT_NV12M` 类似，但将",
"pixels in 2D 64x32 tiles, and stores 2x2 groups of tiles in": "像素以二维 64x32 瓦片存储，并以 Z 序（Z-order）在内存中排列",
"Z-order in memory, alternating Z and mirrored Z shapes horizontally.": "2x2 瓦片组，在水平方向上交替 Z 形与镜像 Z 形。",
"The line stride must be a multiple of 128 pixels to ensure an": "行跨度必须是 128 像素的倍数，以保证",
"integer number of Z shapes. The image height must be a multiple of 32 pixels.": "Z 形数量为整数。图像高度必须是 32 像素的倍数。",
"If the vertical resolution is an odd number of tiles, the last row of": "若垂直分辨率为奇数个瓦片，则最后一行",
"tiles is stored in linear order. The layouts of the luma and chroma": "瓦片以线性顺序存储。亮度平面与色度",
"planes are identical.": "平面的布局相同。",
"    V4L2_PIX_FMT_NV12MT macroblock Z shape memory layout": "    V4L2_PIX_FMT_NV12MT 宏块 Z 形内存布局",
"    Example V4L2_PIX_FMT_NV12MT memory layout of tiles": "    V4L2_PIX_FMT_NV12MT 瓦片内存布局示例",
"`V4L2_PIX_FMT_NV12_4L4` stores pixels in 4x4 tiles, and stores": "`V4L2_PIX_FMT_NV12_4L4` 将像素以 4x4 瓦片存储，并将",
"tiles linearly in memory. The line stride and image height must be": "瓦片在内存中线性排列。行跨度与图像高度必须",
"aligned to a multiple of 4. The layouts of the luma and chroma planes are": "对齐到 4 的倍数。亮度平面与色度平面的布局",
"identical.": "相同。",
"`V4L2_PIX_FMT_NV12_16L16` stores pixels in 16x16 tiles, and stores": "`V4L2_PIX_FMT_NV12_16L16` 将像素以 16x16 瓦片存储，并将",
"`V4L2_PIX_FMT_NV12_32L32` stores pixels in 32x32 tiles, and stores": "`V4L2_PIX_FMT_NV12_32L32` 将像素以 32x32 瓦片存储，并将",
"`V4L2_PIX_FMT_NV12M_8L128` is similar to `V4L2_PIX_FMT_NV12M` but stores": "`V4L2_PIX_FMT_NV12M_8L128` 与 `V4L2_PIX_FMT_NV12M` 类似，但将",
"pixels in 2D 8x128 tiles, and stores tiles linearly in memory.": "像素以二维 8x128 瓦片存储，并将瓦片在内存中线性排列。",
"The image height must be aligned to a multiple of 128.": "图像高度必须对齐到 128 的倍数。",
"`V4L2_PIX_FMT_NV12_8L128` is similar to `V4L2_PIX_FMT_NV12M_8L128` but stores": "`V4L2_PIX_FMT_NV12_8L128` 与 `V4L2_PIX_FMT_NV12M_8L128` 类似，但将",
"two planes in one memory.": "两个平面存储于同一段内存中。",
"`V4L2_PIX_FMT_MM21` store luma pixel in 16x32 tiles, and chroma pixels": "`V4L2_PIX_FMT_MM21` 将亮度像素以 16x32 瓦片存储，色度像素",
"in 16x16 tiles. The line stride must be aligned to a multiple of 16 and the": "以 16x16 瓦片存储。行跨度必须对齐到 16 的倍数，",
"image height must be aligned to a multiple of 32. The number of luma and chroma": "图像高度必须对齐到 32 的倍数。亮度与色度的",
"tiles are identical, even though the tile size differ. The image is formed of": "瓦片数量相同，即便瓦片尺寸不同。图像由",
"two non-contiguous planes.": "两个非连续平面组成。",
"### Tiled NV15": "### 平铺 NV15",
"`V4L2_PIX_FMT_NV15_4L4` Semi-planar 10-bit YUV 4:2:0 formats, using 4x4 tiling.": "`V4L2_PIX_FMT_NV15_4L4` 半平面 10 位 YUV 4:2:0 格式，采用 4x4 平铺。",
"All components are packed without any padding between each other.": "所有分量紧密打包，彼此之间无任何填充。",
"As a side-effect, each group of 4 components are stored over 5 bytes": "其副作用是每组 4 个分量存储于 5 个字节中",
"(YYYY or UVUV = 4 * 10 bits = 40 bits = 5 bytes).": "（YYYY 或 UVUV = 4 × 10 位 = 40 位 = 5 字节）。",
"`V4L2_PIX_FMT_NV12M_10BE_8L128` is similar to `V4L2_PIX_FMT_NV12M` but stores": "`V4L2_PIX_FMT_NV12M_10BE_8L128` 与 `V4L2_PIX_FMT_NV12M` 类似，但将",
"10 bits pixels in 2D 8x128 tiles, and stores tiles linearly in memory.": "10 位像素以二维 8x128 瓦片存储，并将瓦片在内存中线性排列。",
"the data is arranged in big endian order.": "数据以大端（big endian）顺序排列。",
"Note the tile size is 8bytes multiplied by 128 bytes,": "注意瓦片尺寸为 8 字节乘以 128 字节，",
"it means that the low bits and high bits of one pixel may be in different tiles.": "这意味着一个像素的低位与高位可能位于不同的瓦片中。",
"The 10 bit pixels are packed, so 5 bytes contain 4 10-bit pixels layout like": "10 位像素被紧密打包，因此 5 个字节包含 4 个 10 位像素，布局如下",
"this (for luma):": "（以亮度为例）：",
"`V4L2_PIX_FMT_NV12_10BE_8L128` is similar to `V4L2_PIX_FMT_NV12M_10BE_8L128` but stores": "`V4L2_PIX_FMT_NV12_10BE_8L128` 与 `V4L2_PIX_FMT_NV12M_10BE_8L128` 类似，但将",
"`V4L2_PIX_FMT_MT2110T` is one of Mediatek packed 10bit YUV 4:2:0 formats.": "`V4L2_PIX_FMT_MT2110T` 是联发科（Mediatek）打包 10 位 YUV 4:2:0 格式之一。",
"It is fully packed 10bit 4:2:0 format like NV15 (15 bits per pixel), except": "它是完全打包的 10 位 4:2:0 格式，类似于 NV15（每像素 15 位），区别在于",
"that the lower two bits data is stored in separate partitions. The format is": "低两位数据存储在独立的分区中。该格式由",
"composed of 16x32 luma tiles, and 16x16 chroma tiles. Each tiles is 640 bytes": "16x32 的亮度瓦片和 16x16 的色度瓦片组成。每个瓦片长 640 字节，",
"long, divided into 8 partitions of 80 bytes.  The first 16 bytes of the": "划分为 8 个分区，每个分区 80 字节。分区的头 16 字节表示",
"partition represent the 2 least significant bits of pixel data. The remaining": "像素数据的 2 个最低有效位（least significant bits）。其余",
"64 bytes represent the 8 most significant bits of pixel data.": "64 字节表示像素数据的 8 个最高有效位（most significant bits）。",
"    Layout of MT2110T Chroma Tile": "    MT2110T 色度瓦片布局",
"Filtering out the upper part of each partitions results in a valid": "滤除每个分区（partition）的上半部分可得到一个有效的",
"`V4L2_PIX_FMT_MM21` frame. A partition is a sub-tile of size 16 x 4. The": "`V4L2_PIX_FMT_MM21` 帧。分区是大小为 16 × 4 的子瓦片（sub-tile）。",
"lower two bits is said to be tiled since each bytes contains the lower two": "所谓低位“平铺”，是因为每个字节包含",
"bits of the column of for pixel matching the same index. The chroma tiles": "与相同索引对应的四像素列的低两位。色度瓦片",
"only have 4 partitions.": "仅有 4 个分区。",
"`V4L2_PIX_FMT_MT2110R` is identical to `V4L2_PIX_FMT_MT2110T` except that": "`V4L2_PIX_FMT_MT2110R` 与 `V4L2_PIX_FMT_MT2110T` 相同，只是",
"the least significant two bits layout is in raster order. This means the first byte": "最低两位的布局为光栅（raster）顺序。这意味着第一个字节",
"contains 4 pixels of the first row, with 4 bytes per line.": "包含第一行的 4 个像素，每行 4 个字节。",
"### NV16, NV61, NV16M and NV61M": "### NV16、NV61、NV16M 与 NV61M",
"Semi-planar YUV 4:2:2 formats. The chroma plane is subsampled by 2 in the": "半平面 YUV 4:2:2 格式。色度平面在",
"horizontal direction. Chroma lines contain half the number of pixels and the": "水平方向上子采样 2 倍。色度行包含亮度行一半数量的像素和",
"same number of bytes as luma lines, and the chroma plane contains the same": "相同数量的字节，色度平面包含与亮度平面",
"number of lines as the luma plane.": "相同数量的行。",
"### NV20": "### NV20",
"Semi-planar 10-bit YUV 4:2:2 format similar to NV16, using 10-bit components": "半平面 10 位 YUV 4:2:2 格式，类似于 NV16，使用 10 位分量",
"with no padding between each component. A group of 4 components are stored over": "且各分量之间无填充。每组 4 个分量",
"5 bytes in little endian order.": "以小端顺序存储于 5 个字节中。",
"### NV24 and NV42": "### NV24 与 NV42",
"Semi-planar YUV 4:4:4 formats. The chroma plane is not subsampled.": "半平面 YUV 4:4:4 格式。色度平面不进行子采样。",
"Chroma lines contain the same number of pixels and twice the": "色度行包含与亮度行相同数量的像素和两倍",
"number of bytes as luma lines, and the chroma plane contains the same": "数量的字节，色度平面包含与亮度平面",
"number of lines as the luma plane.": "相同数量的行。",
"### P010 and tiled P010": "### P010 与平铺 P010",
"P010 is like NV12 with 10 bits per component, expanded to 16 bits.": "P010 类似于 NV12，但每个分量为 10 位，并扩展为 16 位。",
"Data in the 10 high bits, zeros in the 6 low bits, arranged in little endian order.": "数据位于 10 个高位，6 个低位为零，以小端顺序排列。",
"### P012 and P012M": "### P012 与 P012M",
"P012 is like NV12 with 12 bits per component, expanded to 16 bits.": "P012 类似于 NV12，但每个分量为 12 位，并扩展为 16 位。",
"Data in the 12 high bits, zeros in the 4 low bits, arranged in little endian order.": "数据位于 12 个高位，4 个低位为零，以小端顺序排列。",
"## Fully Planar YUV Formats": "## 全平面 YUV 格式",
"These formats store the Y, Cb and Cr components in three separate planes. The": "这些格式将 Y、Cb 和 Cr 分量存储在三个独立的平面中。",
"luma plane comes first, and the order of the two chroma planes varies between": "亮度平面在前，两个色度平面的顺序",
"formats. The two chroma planes always use the same subsampling.": "因格式而异。两个色度平面始终使用相同的子采样。",
"For memory contiguous formats, the number of padding pixels at the end of the": "对于内存连续格式，色度行尾的填充像素数与",
"chroma lines is identical to the padding of the luma lines. The chroma line": "亮度行的填充相同。因此色度行",
"stride (in bytes) is thus equal to the luma line stride divided by the": "跨度（以字节计）等于亮度行跨度除以",
"horizontal subsampling factor. Vertical subsampling doesn't affect the line": "水平子采样系数。垂直子采样不影响",
"stride.": "行跨度。",
"`V4L2_PIX_FMT_P010_4L4` stores pixels in 4x4 tiles, and stores tiles linearly": "`V4L2_PIX_FMT_P010_4L4` 将像素以 4x4 瓦片存储，并将瓦片在内存中",
"in memory. The line stride must be aligned to multiple of 8 and image height to": "线性排列。行跨度必须对齐到 8 的倍数，图像高度必须",
"a multiple of 4. The layouts of the luma and chroma planes are identical.": "对齐到 4 的倍数。亮度平面与色度平面的布局相同。",
"    - - Planes order [^4^]_": "    - - 平面顺序 [^4^]_",
"      - Contiguous [^5^]_": "      - 连续 [^5^]_",
"### YUV410 and YVU410": "### YUV410 与 YVU410",
"Planar YUV 4:1:0 formats. The chroma planes are subsampled by 4 in each": "平面 YUV 4:1:0 格式。色度平面在每个方向上",
"direction. Chroma lines contain a quarter of the number of pixels and bytes of": "子采样 4 倍。色度行包含亮度行四分之一数量的",
"the luma lines, and the chroma planes contain a quarter of the number of lines": "像素和字节，色度平面包含亮度平面",
"of the luma plane.": "四分之一数量的行。",
"### YUV411P": "### YUV411P",
"Planar YUV 4:1:1 formats. The chroma planes are subsampled by 4 in the": "平面 YUV 4:1:1 格式。色度平面在",
"horizontal direction. Chroma lines contain a quarter of the number of pixels": "水平方向上子采样 4 倍。色度行包含亮度行四分之一数量的",
"and bytes of the luma lines, and the chroma planes contain the same number of": "像素和字节，色度平面包含与亮度平面",
"lines as the luma plane.": "相同数量的行。",
"### YUV420, YVU420, YUV420M and YVU420M": "### YUV420、YVU420、YUV420M 与 YVU420M",
"Planar YUV 4:2:0 formats. The chroma planes are subsampled by 2 in each": "平面 YUV 4:2:0 格式。色度平面在每个方向上",
"direction. Chroma lines contain half of the number of pixels and bytes of the": "子采样 2 倍。色度行包含亮度行一半数量的",
"luma lines, and the chroma planes contain half of the number of lines of the": "像素和字节，色度平面包含亮度平面",
"luma plane.": "一半数量的行。",
"### YUV422P, YUV422M and YVU422M": "### YUV422P、YUV422M 与 YVU422M",
"Planar YUV 4:2:2 formats. The chroma planes are subsampled by 2 in the": "平面 YUV 4:2:2 格式。色度平面在",
"horizontal direction. Chroma lines contain half of the number of pixels and": "水平方向上子采样 2 倍。色度行包含亮度行一半数量的",
"bytes of the luma lines, and the chroma planes contain the same number of lines": "像素和字节，色度平面包含与亮度平面",
"as the luma plane.": "相同数量的行。",
"### YUV444M and YVU444M": "### YUV444M 与 YVU444M",
"Planar YUV 4:4:4 formats. The chroma planes are no subsampled. Chroma lines": "平面 YUV 4:4:4 格式。色度平面不进行子采样。色度行",
"contain the same number of pixels and bytes of the luma lines, and the chroma": "包含与亮度行相同数量的像素和字节，色度",
"planes contain the same number of lines as the luma plane.": "平面包含与亮度平面相同数量的行。",
}
# also second-table header rows (first table already handled via "    - - Identifier" etc.)
# The second table header uses same indentation keys but different trailing tokens; merge:
m["    - - Planes order [^4^]_"] = "    - - 平面顺序 [^4^]_"

data = open(F, encoding='utf-8').read()
lines = data.split('\n')
out = []
for ln in lines:
    key = ln.rstrip('\r')
    if key in m:
        out.append(m[key])
    else:
        out.append(ln)
new = '\n'.join(out)
tmp = F + '.tmp'
open(tmp, 'w', encoding='utf-8').write(new)
os.replace(tmp, F)
print("done, changed lines:", sum(1 for a,b in zip(data.split('\n'), new.split('\n')) if a!=b))
