import os

F = r"D:/WORKSPACE/linux-7.1.3/docs/系统文档/userspace-api/media/v4l/dev-subdev.md"

T = {
"######## Sub-device Interface":
"######## 子设备接口（Sub-device Interface）",
"The complex nature of V4L2 devices, where hardware is often made of":
"V4L2 设备的复杂性在于，其硬件通常由",
"several integrated circuits that need to interact with each other in a":
"多个需要以受控方式相互协作的集成电路构成，因而产生了复杂的 V4L2 驱动。",
"controlled way, leads to complex V4L2 drivers. The drivers usually":
"这些驱动通常",
"reflect the hardware model in software, and model the different hardware":
"在软件中反映硬件模型，并将不同的硬件",
"components as software blocks called sub-devices.":
"组件建模为称为子设备（sub-devices）的软件模块。",
"V4L2 sub-devices are usually kernel-only objects. If the V4L2 driver":
"V4L2 子设备通常为仅内核对象。如果 V4L2 驱动",
"implements the media device API, they will automatically inherit from":
"实现了 media device API，它们将自动继承自",
"media entities. Applications will be able to enumerate the sub-devices":
"media 实体（media entities）。应用程序将能够枚举这些子设备，",
"and discover the hardware topology using the media entities, pads and":
"并通过 media 实体（entities）、pads 和",
"links enumeration API.":
"links 的枚举 API 发现硬件拓扑结构。",
"In addition to make sub-devices discoverable, drivers can also choose to":
"除了使子设备可被发现之外，驱动还可以选择",
"make them directly configurable by applications. When both the":
"让应用程序直接配置它们。当",
"sub-device driver and the V4L2 device driver support this, sub-devices":
"子设备驱动和 V4L2 设备驱动都支持此功能时，子设备",
"will feature a character device node on which ioctls can be called to":
"将具有一个字符设备节点，可在其上调用 ioctl 以",
"- query, read and write sub-devices controls":
"- 查询、读取和写入子设备的控制项（controls）",
"- subscribe and unsubscribe to events and retrieve them":
"- 订阅和取消订阅事件并检索事件",
"- negotiate image formats on individual pads":
"- 在独立的 pads 上协商图像格式",
"- inspect and modify internal data routing between pads of the same entity":
"- 检查并修改同一实体内 pads 之间的内部数据路由",
"Sub-device character device nodes, conventionally named":
"子设备字符设备节点通常命名为",
"`/dev/v4l-subdev*`, use major number 81.":
"`/dev/v4l-subdev*`，使用主设备号 81。",
"Drivers may opt to limit the sub-device character devices to only expose":
"驱动可以选择将子设备字符设备限制为只暴露",
"operations that do not modify the device state. In such a case the sub-devices":
"不修改设备状态的操作。在这种情况下，子设备",
"are referred to as `read-only` in the rest of this documentation, and the":
"在本文档其余部分被称为 `read-only`，并且",
"related restrictions are documented in individual ioctls.":
"相关限制记录在各自的 ioctl 中。",
"## Controls":
"## 控制项（Controls）",
"Most V4L2 controls are implemented by sub-device hardware. Drivers":
"大多数 V4L2 控制项由子设备硬件实现。驱动",
"usually merge all controls and expose them through video device nodes.":
"通常会合并所有控制项并通过视频设备节点暴露出来。",
"Applications can control all sub-devices through a single interface.":
"应用程序可以通过单一接口控制所有子设备。",
"Complex devices sometimes implement the same control in different pieces":
"复杂设备有时会在不同的硬件",
"of hardware. This situation is common in embedded platforms, where both":
"中实现了相同的控制项。这种情况在嵌入式平台中很常见，",
"sensors and image processing hardware implement identical functions,":
"传感器和图像处理硬件都实现了相同的功能，",
"such as contrast adjustment, white balance or faulty pixels correction.":
"例如对比度调节、白平衡或坏点校正。",
"As the V4L2 controls API doesn't support several identical controls in a":
"由于 V4L2 控制项 API 不支持在单个设备中存在多个相同的控制项，",
"single device, all but one of the identical controls are hidden.":
"因此这些相同控制项中除一个之外的其余都被隐藏。",
"Applications can access those hidden controls through the sub-device":
"应用程序可以通过子设备",
"node with the V4L2 control API described in control. The ioctls":
"节点以及 control 中描述的 V4L2 控制项 API 来访问这些被隐藏的控制项。",
"behave identically as when issued on V4L2 device nodes, with the":
"这些 ioctl 的行为与在 V4L2 设备节点上发出时完全相同，",
"exception that they deal only with controls implemented in the":
"唯一的区别是它们只处理在",
"sub-device.":
"子设备中实现的控制项。",
"## Events":
"## 事件（Events）",
"V4L2 sub-devices can notify applications of events as described in":
"V4L2 子设备可以按照 event 中的描述向应用程序通知事件。",
"event. The API behaves identically as when used on V4L2 device":
"该 API 的行为与在 V4L2 设备节点上使用时完全相同，",
"nodes, with the exception that it only deals with events generated by":
"唯一的区别是它只处理由",
"the sub-device. Depending on the driver, those events might also be":
"子设备生成的事件。取决于驱动，这些事件也可能",
"reported on one (or several) V4L2 device nodes.":
"被报告到一个（或多个）V4L2 设备节点。",
"## Pad-level Formats":
"## Pad 级别格式（Pad-level Formats）",
"    Pad-level formats are only applicable to very complex devices that":
"    Pad 级别的格式仅适用于那些",
"    need to expose low-level format configuration to user space. Generic":
"    需要向用户空间暴露底层格式配置的非常复杂的设备。通用的",
"    V4L2 applications do **not** need to use the API described in this":
"    V4L2 应用程序**不**需要使用本节描述的 API。",
"    For the purpose of this section, the term **format** means the":
"    就本节而言，术语 **format** 指的是",
"    combination of media bus data format, frame width and frame height.":
"    media 总线数据格式、帧宽度和帧高度的组合。",
"Image formats are typically negotiated on video capture and output":
"图像格式通常是在视频采集和输出",
"devices using the format and":
"设备上通过使用 format 和",
"selection <VIDIOC_SUBDEV_G_SELECTION> ioctls. The driver is":
"selection <VIDIOC_SUBDEV_G_SELECTION> ioctl 来协商的。驱动负责",
"responsible for configuring every block in the video pipeline according":
"根据管线输入和/或输出处所请求的格式，配置视频管线中的",
"to the requested format at the pipeline input and/or output.":
"每一个模块。",
"For complex devices, such as often found in embedded systems, identical":
"对于复杂设备（例如嵌入式系统中常见的设备），管线输出处相同的",
"image sizes at the output of a pipeline can be achieved using different":
"图像尺寸可以通过不同的",
"hardware configurations. One such example is shown on":
"硬件配置实现。pipeline-scaling 展示了这样一个例子，其中图像缩放",
"pipeline-scaling, where image scaling can be performed on both":
"可以同时在视频传感器和主机图像处理",
"the video sensor and the host image processing hardware.":
"硬件上执行。",
"    Image Format Negotiation on Pipelines":
"    管线上的图像格式协商",
"    High quality and high speed pipeline configuration":
"    高质量与高速的管线配置",
"The sensor scaler is usually of less quality than the host scaler, but":
"传感器缩放器通常质量不如主机缩放器，但",
"scaling on the sensor is required to achieve higher frame rates.":
"为了在传感器上进行缩放以实现更高的帧率。",
"Depending on the use case (quality vs. speed), the pipeline must be":
"根据使用场景（质量 vs. 速度），管线必须",
"configured differently. Applications need to configure the formats at":
"进行不同的配置。应用程序需要显式地",
"every point in the pipeline explicitly.":
"配置管线中每一处的格式。",
"Drivers that implement the media API <media-controller-intro>":
"实现了 media API <media-controller-intro> 的",
"can expose pad-level image format configuration to applications. When":
"驱动可以向应用程序暴露 pad 级别的图像格式配置。当",
"they do, applications can use the":
"它们这样做时，应用程序可以使用",
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> and":
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> 和",
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctls. to":
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctl 来",
"negotiate formats on a per-pad basis.":
"按每个 pad 协商格式。",
"Applications are responsible for configuring coherent parameters on the":
"应用程序负责在整个",
"whole pipeline and making sure that connected pads have compatible":
"管线上配置一致的参数，并确保相连的 pads 具有兼容的",
"formats. The pipeline is checked for formats mismatch at":
"格式。管线会在",
"VIDIOC_STREAMON <VIDIOC_STREAMON> time, and an `EPIPE` error":
"VIDIOC_STREAMON <VIDIOC_STREAMON> 时检查格式是否不匹配，如果配置",
"code is then returned if the configuration is invalid.":
"无效，则返回 `EPIPE` 错误码。",
"Pad-level image format configuration support can be tested by calling":
"可以通过调用",
"the VIDIOC_SUBDEV_G_FMT ioctl on pad":
"VIDIOC_SUBDEV_G_FMT ioctl 来测试 pad 级别图像格式配置的支持情况，即在 pad",
"0. If the driver returns an `EINVAL` error code pad-level format":
"0 上调用。如果驱动返回 `EINVAL` 错误码，则表示该子设备",
"configuration is not supported by the sub-device.":
"不支持 pad 级别的格式配置。",
"### Format Negotiation":
"### 格式协商（Format Negotiation）",
"Acceptable formats on pads can (and usually do) depend on a number of":
"pad 上可接受的格式（通常确实）取决于若干",
"external parameters, such as formats on other pads, active links, or":
"外部参数，例如其他 pads 上的格式、活动 links，或者",
"even controls. Finding a combination of formats on all pads in a video":
"甚至是控制项。要为视频管线中所有 pads 找到",
"pipeline, acceptable to both application and driver, can't rely on":
"应用程序和驱动都可接受的格式组合，不能",
"formats enumeration only. A format negotiation mechanism is required.":
"仅依赖格式枚举。因此需要一种格式协商机制。",
"Central to the format negotiation mechanism are the get/set format":
"格式协商机制的核心是 get/set 格式",
"operations. When called with the `which` argument set to":
"操作。当 `which` 参数被设置为",
"V4L2_SUBDEV_FORMAT_TRY <VIDIOC_SUBDEV_G_FMT>, the":
"V4L2_SUBDEV_FORMAT_TRY <VIDIOC_SUBDEV_G_FMT> 时，",
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> and":
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> 和",
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctls operate on":
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctl 操作的是",
"a set of formats parameters that are not connected to the hardware":
"一组与硬件",
"configuration. Modifying those 'try' formats leaves the device state":
"配置无关的格式参数。修改这些 'try' 格式不会改变设备状态",
"(this applies to both the software state stored in the driver":
"（这同时适用于驱动中存储的软件状态和",
"and the hardware state stored in the device itself).":
"设备本身存储的硬件状态）。",
"Depending on the driver, those controls might also be exposed through":
"取决于驱动，这些控制项也可能通过",
"one (or several) V4L2 device nodes.":
"一个（或多个）V4L2 设备节点暴露出来。",
"untouched (this applies to both the software state stored in the driver":
"未被改变（这同时适用于驱动中存储的软件状态",
"While not kept as part of the device state, try formats are stored in":
"虽然 try 格式不被作为设备状态的一部分保存，但它们存储在",
"the sub-device file handles. A":
"子设备的文件句柄中。一次",
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> call will return":
"VIDIOC_SUBDEV_G_FMT <VIDIOC_SUBDEV_G_FMT> 调用将返回",
"the last try format set **on the same sub-device file handle**. Several":
"**在同一子设备文件句柄上**设置的最后一个 try 格式。因此，多个",
"applications querying the same sub-device at the same time will thus not":
"同时查询同一子设备的应用程序之间",
"interact with each other.":
"不会相互影响。",
"To find out whether a particular format is supported by the device,":
"为了确定某个特定格式是否被设备支持，",
"applications use the":
"应用程序使用",
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctl. Drivers":
"VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctl。驱动会",
"verify and, if needed, change the requested `format` based on device":
"根据设备要求验证并在需要时修改所请求的 `format`，",
"requirements and return the possibly modified value. Applications can":
"然后返回可能已被修改的值。应用程序可以",
"then choose to try a different format or accept the returned value and":
"随后选择尝试不同的格式，或接受返回的值并",
"continue.":
"继续。",
"Formats returned by the driver during a negotiation iteration are":
"驱动在协商迭代期间返回的格式",
"guaranteed to be supported by the device. In particular, drivers":
"保证受设备支持。具体而言，驱动保证：如果将以原样",
"guarantee that a returned format will not be further changed if passed":
"传递给 VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> 调用，返回的",
"to an VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> call as-is":
"格式不会被进一步修改",
"(as long as external parameters, such as formats on other pads or links'":
"（只要外部参数（例如其他 pads 或 links 上的格式）的",
"configuration are not changed).":
"配置未被改变）。",
"Drivers automatically propagate formats inside sub-devices. When a try":
"驱动会在子设备内部自动传播格式。当在某个 pad 上设置了 try",
"or active format is set on a pad, corresponding formats on other pads of":
"或活动格式时，同一子设备上",
"the same sub-device can be modified by the driver. Drivers are free to":
"其他 pads 的相应格式可能会被驱动修改。驱动可自由",
"modify formats as required by the device. However, they should comply":
"根据设备要求修改格式。但是，在可能的情况下它们应当遵守",
"with the following rules when possible:":
"以下规则：",
"- Formats should be propagated from sink pads to source pads. Modifying":
"- 格式应该从 sink pads 传播到 source pads。修改",
"   a format on a source pad should not modify the format on any sink":
"   source pad 上的格式不应修改任何 sink",
"   pad.":
"   pad 上的格式。",
"- Sub-devices that scale frames using variable scaling factors should":
"- 使用可变缩放因子缩放帧的子设备，在 sink pads 格式被",
"   reset the scale factors to default values when sink pads formats are":
"   修改时应将缩放因子重置为默认值。如果支持 1:1 缩放比，则意味着",
"   modified. If the 1:1 scaling ratio is supported, this means that":
"   source pads 的格式应被重置为 sink pads 的格式。",
"   source pads formats should be reset to the sink pads formats.":
"",
"Formats are not propagated across links, as that would involve":
"格式不会跨 links 传播，因为那将涉及",
"propagating them from one sub-device file handle to another.":
"从一个子设备文件句柄传播到另一个。",
"Applications must then take care to configure both ends of every link":
"因此，应用程序必须注意使用兼容的格式显式地",
"explicitly with compatible formats. Identical formats on the two ends of":
"配置每条 link 的两端。link 两端",
"a link are guaranteed to be compatible. Drivers are free to accept":
"相同的格式保证是兼容的。驱动可以自由接受",
"different formats matching device requirements as being compatible.":
"符合设备要求的不同格式作为兼容格式。",
"sample-pipeline-config shows a sample configuration sequence":
"sample-pipeline-config 展示了一个示例配置序列，",
"for the pipeline described in pipeline-scaling (table columns":
"对应于 pipeline-scaling 中描述的管线（表格列",
"list entity names and pad numbers).":
"列出了实体名称和 pad 编号）。",
"    - - Initial state":
"    - - 初始状态",
"    - - Configure frontend sink format":
"    - - 配置前端 sink 格式",
"    - - Configure scaler sink format":
"    - - 配置缩放器 sink 格式",
"    - - Configure scaler sink compose selection":
"    - - 配置缩放器 sink 合成选择",
"      - format":
"      - 格式",
"      - compose selection rectangle":
"      - 合成选择矩形",
"1. Initial state. The sensor source pad format is set to its native 3MP":
"1. 初始状态。传感器源 pad 格式被设置为其原生的 3MP",
"   size and V4L2_MBUS_FMT_SGRBG8_1X8 media bus code. Formats on the":
"   尺寸，媒体总线码为 V4L2_MBUS_FMT_SGRBG8_1X8。主机前端以及缩放器的",
"   host frontend and scaler sink and source pads have the default":
"   sink 和 source pads 上的格式为默认值，",
"   values, as well as the compose rectangle on the scaler's sink pad.":
"   缩放器 sink pad 上的合成矩形也是如此。",
"2. The application configures the frontend sink pad format's size to":
"2. 应用程序将前端 sink pad 格式的尺寸配置为",
"   2048x1536 and its media bus code to V4L2_MBUS_FMT_SGRBG_1X8. The":
"   2048x1536，并将其媒体总线码配置为 V4L2_MBUS_FMT_SGRBG_1X8。驱动将",
"   driver propagates the format to the frontend source pad.":
"   该格式传播到前端 source pad。",
"3. The application configures the scaler sink pad format's size to":
"3. 应用程序将缩放器 sink pad 格式的尺寸配置为",
"   2046x1534 and the media bus code to V4L2_MBUS_FMT_SGRBG_1X8 to":
"   2046x1534，并将媒体总线码配置为 V4L2_MBUS_FMT_SGRBG_1X8，以",
"   match the frontend source size and media bus code. The media bus code":
"   匹配前端 source 的尺寸和媒体总线码。sink pad 上的",
"   on the sink pad is set to V4L2_MBUS_FMT_SGRBG_1X8. The driver":
"   媒体总线码被设置为 V4L2_MBUS_FMT_SGRBG_1X8。驱动将",
"   propagates the size to the compose selection rectangle on the":
"   尺寸传播到缩放器 sink pad 上的合成选择矩形，",
"   scaler's sink pad, and the format to the scaler source pad.":
"   并将格式传播到缩放器 source pad。",
"4. The application configures the size of the compose selection":
"4. 应用程序将缩放器 sink pad 的合成选择",
"   rectangle of the scaler's sink pad 1280x960. The driver propagates":
"   矩形尺寸配置为 1280x960。驱动将",
"   the size to the scaler's source pad format.":
"   该尺寸传播到缩放器 source pad 格式。",
"When satisfied with the try results, applications can set the active":
"当对 try 结果满意后，应用程序可以设置活动",
"formats by setting the `which` argument to":
"格式，方法是将 `which` 参数设置为",
"`V4L2_SUBDEV_FORMAT_ACTIVE`. Active formats are changed exactly as try":
"`V4L2_SUBDEV_FORMAT_ACTIVE`。活动格式被驱动修改的方式与 try",
"formats by drivers. To avoid modifying the hardware state during format":
"格式完全相同。为了避免在格式",
"negotiation, applications should negotiate try formats first and then":
"协商期间修改硬件状态，应用程序应先协商 try 格式，然后",
"modify the active settings using the try formats returned during the":
"使用协商最后一轮迭代返回的 try 格式来修改",
"last negotiation iteration. This guarantees that the active format will":
"活动设置。这保证活动格式将",
"be applied as-is by the driver without being modified.":
"被驱动按原样应用而不会被修改。",
"### Selections: cropping, scaling and composition":
"### 选择（Selections）：裁剪、缩放与合成",
"Many sub-devices support cropping frames on their input or output pads":
"许多子设备支持在其输入或输出 pads 上裁剪帧",
"(or possible even on both). Cropping is used to select the area of":
"（甚至可能同时支持两者）。裁剪用于选择图像中",
"interest in an image, typically on an image sensor or a video decoder.":
"感兴趣的区域，通常是在图像传感器或视频解码器上。",
"It can also be used as part of digital zoom implementations to select":
"它也可以作为数字变焦实现的一部分，用于选择",
"the area of the image that will be scaled up.":
"将被放大的图像区域。",
"Crop settings are defined by a crop rectangle and represented in a":
"裁剪设置由一个裁剪矩形定义，并在",
"struct `v4l2_rect` by the coordinates of the top":
"struct `v4l2_rect` 中由左上角的",
"left corner and the rectangle size. Both the coordinates and sizes are":
"坐标和矩形尺寸表示。坐标和尺寸",
"expressed in pixels.":
"都以像素为单位表示。",
"As for pad formats, drivers store try and active rectangles for the":
"与 pad 格式一样，驱动为",
"selection targets v4l2-selections-common.":
"selection targets v4l2-selections-common 存储 try 和 active 矩形。",
"On sink pads, cropping is applied relative to the current pad format.":
"在 sink pads 上，裁剪是相对于当前 pad 格式应用的。",
"The pad format represents the image size as received by the sub-device":
"pad 格式表示子设备从管线中前一个模块",
"from the previous block in the pipeline, and the crop rectangle":
"接收到的图像尺寸，而裁剪矩形",
"represents the sub-image that will be transmitted further inside the":
"表示将在子设备内部被进一步传输以进行",
"sub-device for processing.":
"处理的子图像。",
"The scaling operation changes the size of the image by scaling it to new":
"缩放操作通过将图像缩放到新的",
"dimensions. The scaling ratio isn't specified explicitly, but is implied":
"尺寸来改变图像大小。缩放比并未显式指定，而是从",
"from the original and scaled image sizes. Both sizes are represented by":
"原始和缩放后的图像尺寸中隐含得出。两种尺寸都由",
"struct `v4l2_rect`.":
"struct `v4l2_rect` 表示。",
"Scaling support is optional. When supported by a subdev, the crop":
"缩放支持是可选的。当子设备支持时，子设备 sink pad 上的裁剪",
"rectangle on the subdev's sink pad is scaled to the size configured":
"矩形会被缩放到使用",
"using the":
"以下方式配置的",
"VIDIOC_SUBDEV_S_SELECTION <VIDIOC_SUBDEV_G_SELECTION> IOCTL":
"VIDIOC_SUBDEV_S_SELECTION <VIDIOC_SUBDEV_G_SELECTION> IOCTL",
"using `V4L2_SEL_TGT_COMPOSE` selection target on the same pad. If the":
"在同一个 pad 上以 `V4L2_SEL_TGT_COMPOSE` 选择目标指定的尺寸。如果",
"subdev supports scaling but not composing, the top and left values are":
"子设备支持缩放但不支持合成，则 top 和 left 值",
"not used and must always be set to zero.":
"不会被使用，且必须始终设置为零。",
"On source pads, cropping is similar to sink pads, with the exception":
"在 source pads 上，裁剪与 sink pads 类似，区别在于",
"that the source size from which the cropping is performed, is the":
"执行裁剪所基于的源尺寸是",
"COMPOSE rectangle on the sink pad. In both sink and source pads, the":
"sink pad 上的 COMPOSE 矩形。在 sink 和 source pads 上，",
"crop rectangle must be entirely contained inside the source image size":
"裁剪矩形必须完全包含在源图像尺寸",
"for the crop operation.":
"之内，裁剪操作才有效。",
"The drivers should always use the closest possible rectangle the user":
"驱动应始终使用用户在所有选择目标上请求的",
"requests on all selection targets, unless specifically told otherwise.":
"最接近的可能矩形，除非另有明确说明。",
"`V4L2_SEL_FLAG_GE` and `V4L2_SEL_FLAG_LE` flags may be used to round":
"`V4L2_SEL_FLAG_GE` 和 `V4L2_SEL_FLAG_LE` 标志可用于将",
"the image size either up or down. v4l2-selection-flags":
"图像尺寸向上或向下取整。v4l2-selection-flags",
"### Types of selection targets":
"### 选择目标的类型",
"##### Actual targets":
"##### 实际目标（Actual targets）",
"Actual targets (without a postfix) reflect the actual hardware":
"实际目标（不带后缀）反映任意时刻实际的硬件",
"configuration at any point of time. There is a BOUNDS target":
"配置。每个实际目标都对应一个",
"corresponding to every actual target.":
"BOUNDS 目标。",
"##### BOUNDS targets":
"##### BOUNDS 目标",
"BOUNDS targets is the smallest rectangle that contains all valid actual":
"BOUNDS 目标是包含所有有效实际",
"rectangles. It may not be possible to set the actual rectangle as large":
"矩形的最小矩形。然而，可能无法将实际矩形设置为",
"as the BOUNDS rectangle, however. This may be because e.g. a sensor's":
"与 BOUNDS 矩形一样大。这可能是因为，例如，传感器的",
"pixel array is not rectangular but cross-shaped or round. The maximum":
"像素阵列不是矩形而是十字形或圆形。最大",
"size may also be smaller than the BOUNDS rectangle.":
"尺寸也可能小于 BOUNDS 矩形。",
"### Order of configuration and format propagation":
"### 配置顺序与格式传播",
"Inside subdevs, the order of image processing steps will always be from":
"在子设备内部，图像处理的步骤顺序始终是从",
"the sink pad towards the source pad. This is also reflected in the order":
"sink pad 朝向 source pad。这也反映在用户必须执行配置的",
"in which the configuration must be performed by the user: the changes":
"顺序中：所做的更改",
"made will be propagated to any subsequent stages. If this behaviour is":
"将被传播到任何后续阶段。如果不希望这种行为，",
"not desired, the user must set `V4L2_SEL_FLAG_KEEP_CONFIG` flag. This":
"用户必须设置 `V4L2_SEL_FLAG_KEEP_CONFIG` 标志。该",
"flag causes no propagation of the changes are allowed in any":
"标志意味着在任何情况下都不允许",
"circumstances. This may also cause the accessed rectangle to be adjusted":
"传播更改。根据底层硬件的特性，这还可能导致被访问的矩形被驱动",
"by the driver, depending on the properties of the underlying hardware.":
"调整。",
"The coordinates to a step always refer to the actual size of the":
"某一步骤的坐标始终指向上一步骤的",
"previous step. The exception to this rule is the sink compose":
"实际尺寸。此规则的唯一例外是 sink 的 compose",
"rectangle, which refers to the sink compose bounds rectangle --- if it":
"矩形，它指的是 sink compose bounds 矩形 --- 如果",
"is supported by the hardware.":
"硬件支持的话。",
"1. Sink pad format. The user configures the sink pad format. This format":
"1. Sink pad 格式。用户配置 sink pad 格式。该格式",
"   defines the parameters of the image the entity receives through the":
"   定义了实体通过 pad 接收以进行",
"   pad for further processing.":
"   进一步处理的图像参数。",
"2. Sink pad actual crop selection. The sink pad crop defines the crop":
"2. Sink pad 实际裁剪选择。Sink pad 裁剪定义了针对",
"   performed to the sink pad format.":
"   sink pad 格式执行的裁剪。",
"3. Sink pad actual compose selection. The size of the sink pad compose":
"3. Sink pad 实际合成选择。Sink pad 合成",
"   rectangle defines the scaling ratio compared to the size of the sink":
"   矩形的尺寸定义了相对于 sink pad",
"   pad crop rectangle. The location of the compose rectangle specifies":
"   裁剪矩形尺寸的缩放比。合成矩形的位置指定了",
"   the location of the actual sink compose rectangle in the sink compose":
"   实际 sink 合成矩形在 sink compose",
"   bounds rectangle.":
"   bounds 矩形中的位置。",
"4. Source pad actual crop selection. Crop on the source pad defines crop":
"4. Source pad 实际裁剪选择。Source pad 上的裁剪定义了针对",
"   performed to the image in the sink compose bounds rectangle.":
"   sink compose bounds 矩形中图像的裁剪。",
"5. Source pad format. The source pad format defines the output pixel":
"5. Source pad 格式。Source pad 格式定义了子设备的输出像素",
"   format of the subdev, as well as the other parameters with the":
"   格式，以及其他参数，但",
"   exception of the image width and height. Width and height are defined":
"   图像宽度和高度除外。宽度和高度由",
"   by the size of the source pad actual crop selection.":
"   source pad 实际裁剪选择的尺寸定义。",
"Accessing any of the above rectangles not supported by the subdev will":
"访问子设备不支持的上述任何矩形都将",
"return `EINVAL`. Any rectangle referring to a previous unsupported":
"返回 `EINVAL`。任何引用先前不支持的",
"rectangle coordinates will instead refer to the previous supported":
"矩形坐标的矩形，将改为引用先前支持的",
"rectangle. For example, if sink crop is not supported, the compose":
"矩形。例如，如果不支持 sink 裁剪，则 compose",
"selection will refer to the sink pad format dimensions instead.":
"选择将改为引用 sink pad 格式的尺寸。",
"    Image processing in subdevs: simple crop example":
"    子设备中的图像处理：简单裁剪示例",
"In the above example, the subdev supports cropping on its sink pad. To":
"在上面的示例中，子设备支持在其 sink pad 上进行裁剪。要",
"configure it, the user sets the media bus format on the subdev's sink":
"配置它，用户在子设备的 sink",
"pad. Now the actual crop rectangle can be set on the sink pad --- the":
"pad 上设置媒体总线格式。现在可以在 sink pad 上设置实际的裁剪矩形 --- 该",
"location and size of this rectangle reflect the location and size of a":
"矩形的位置和尺寸反映了要从 sink 格式中",
"rectangle to be cropped from the sink format. The size of the sink crop":
"裁剪出的矩形的位置和尺寸。Sink 裁剪",
"rectangle will also be the size of the format of the subdev's source":
"矩形的尺寸也将是子设备 source",
"pad.":
"pad 的格式尺寸。",
"    Image processing in subdevs: scaling with multiple sources":
"    子设备中的图像处理：多源缩放",
"In this example, the subdev is capable of first cropping, then scaling":
"在此示例中，子设备能够先裁剪，再缩放，",
"and finally cropping for two source pads individually from the resulting":
"最后从生成的缩放图像中分别为两个 source pads",
"scaled image. The location of the scaled image in the cropped image is":
"单独裁剪。缩放图像在裁剪图像中的位置",
"ignored in sink compose target. Both of the locations of the source crop":
"在 sink compose 目标中被忽略。两个 source 裁剪",
"rectangles refer to the sink scaling rectangle, independently cropping":
"矩形的位置都引用 sink 缩放矩形，分别",
"an area at location specified by the source crop rectangle from it.":
"从中裁剪出由 source 裁剪矩形指定位置的区域。",
"    Image processing in subdevs: scaling and composition with multiple sinks and sources":
"    子设备中的图像处理：多 sink 与多 source 的缩放与合成",
"The subdev driver supports two sink pads and two source pads. The images":
"该子设备驱动支持两个 sink pads 和两个 source pads。来自",
"from both of the sink pads are individually cropped, then scaled and":
"两个 sink pads 的图像被分别裁剪，然后缩放，",
"further composed on the composition bounds rectangle. From that, two":
"并在合成 bounds 矩形上进一步合成。由此，两条",
"independent streams are cropped and sent out of the subdev from the":
"独立的流被裁剪，并从子设备的",
"source pads.":
"source pads 输出。",
"## Streams, multiplexed media pads and internal routing":
"## 流、多路复用 media pads 与内部路由",
"Simple V4L2 sub-devices do not support multiple, unrelated video streams,":
"简单的 V4L2 子设备不支持多个不相关的视频流，",
"and only a single stream can pass through a media link and a media pad.":
"只有单个流可以通过一个 media link 和一个 media pad。",
"Thus each pad contains a format and selection configuration for that":
"因此每个 pad 包含该",
"single stream. A subdev can do stream processing and split a stream into":
"单个流的格式和选择配置。子设备可以进行流处理并将一个流拆分为",
"two or compose two streams into one, but the inputs and outputs for the":
"两个，或将两个流合成为一个，但子设备的",
"subdev are still a single stream per pad.":
"输入和输出仍然是每个 pad 一个流。",
"Some hardware, e.g. MIPI CSI-2, support multiplexed streams, that is, multiple":
"某些硬件（例如 MIPI CSI-2）支持多路复用流，即多个",
"data streams are transmitted on the same bus, which is represented by a media":
"数据流在同一总线上传输，这由一个连接发送端 source pad 与接收端",
"link connecting a transmitter source pad with a sink pad on the receiver. For":
"sink pad 的 media link 来表示。例如，",
"example, a camera sensor can produce two distinct streams, a pixel stream and a":
"摄像头传感器可以产生两个不同的流：像素流和",
"metadata stream, which are transmitted on the multiplexed data bus, represented":
"元数据流，它们在多路复用的数据总线上传输，由连接",
"by a media link which connects the single sensor's source pad with the receiver":
"单一传感器 source pad 与接收端",
"sink pad. The stream-aware receiver will de-multiplex the streams received on":
"sink pad 的 media link 表示。支持流的接收端会对其 sink pad 上",
"the its sink pad and allows to route them individually to one of its source":
"接收到的流进行解复用，并允许将它们分别",
"pads.":
"路由到其某个 source pad。",
"Subdevice drivers that support multiplexed streams are compatible with":
"支持多路复用流的子设备驱动与非",
"non-multiplexed subdev drivers. However, if the driver at the sink end of a link":
"多路复用子设备驱动兼容。但是，如果一条 link 的 sink 端的驱动",
"does not support streams, then only stream 0 of source end may be captured.":
"不支持流，则只能捕获 source 端的流 0。",
"There may be additional limitations specific to the sink device.":
"可能还存在特定于 sink 设备的其他限制。",
"### Understanding streams":
"### 理解流（streams）",
"A stream is a stream of content (e.g. pixel data or metadata) flowing through":
"流是内容（例如像素数据或元数据）的流，它流经",
"the media pipeline from a source (e.g. a sensor) towards the final sink (e.g. a":
"media 管线，从源（例如传感器）流向最终的 sink（例如",
"receiver and demultiplexer in a SoC). Each media link carries all the enabled":
"SoC 中的接收端和解复用器）。每条 media link 承载所有已启用的",
"streams from one end of the link to the other, and sub-devices have routing":
"流，从 link 的一端到另一端，子设备具有路由",
"tables which describe how the incoming streams from sink pads are routed to the":
"表，描述来自 sink pads 的传入流如何被路由到",
"source pads.":
"source pads。",
"A stream ID is a media pad-local identifier for a stream. Streams IDs of":
"流 ID 是流的 media pad 本地标识符。同一个",
"the same stream must be equal on both ends of a link. In other words,":
"流的流 ID 必须在 link 的两端相等。换句话说，",
"a particular stream ID must exist on both sides of a media":
"特定的流 ID 必须存在于 media",
"link, but another stream ID can be used for the same stream at the other side":
"link 的两侧，但子设备的",
"of the sub-device.":
"另一侧可以使用另一个流 ID 来表示同一个流。",
"A stream at a specific point in the media pipeline is identified by the":
"media 管线中特定位置的流由",
"sub-device and a (pad, stream) pair. For sub-devices that do not support":
"子设备和一个 (pad, stream) 对来标识。对于不支持",
"multiplexed streams the 'stream' field is always 0.":
"多路复用流的子设备，'stream' 字段始终为 0。",
"### Interaction between routes, streams, formats and selections":
"### 路由、流、格式与选择之间的交互",
"The addition of streams to the V4L2 sub-device interface moves the sub-device":
"向 V4L2 子设备接口添加流后，子设备的",
"formats and selections from pads to (pad, stream) pairs. Besides the":
"格式和选择从 pads 转移到 (pad, stream) 对。除了",
"usual pad, also the stream ID needs to be provided for setting formats and":
"通常的 pad 之外，设置格式和",
"selections. The order of configuring formats and selections along a stream is":
"选择时还需要提供流 ID。沿流配置格式和选择的顺序",
"the same as without streams (see format-propagation).":
"与没有流时相同（见 format-propagation）。",
"Instead of the sub-device wide merging of streams from all sink pads":
"与子设备范围内将所有 sink pads 的流合并到",
"towards all source pads, data flows for each route are separate from each":
"所有 source pads 不同，每条路由的数据流彼此",
"other. Any number of routes from streams on sink pads towards streams on":
"独立。在驱动支持的范围内，允许任意数量的从 sink pads 上的流到",
"source pads is allowed, to the extent supported by drivers. For every":
"source pads 上的流的路由。但是，对于",
"stream on a source pad, however, only a single route is allowed.":
"source pad 上的每个流，只允许一条路由。",
"Any configurations of a stream within a pad, such as format or selections,":
"pad 内某个流的任何配置（例如格式或选择）",
"are independent of similar configurations on other streams. This is":
"都独立于其他流上的类似配置。这一点",
"subject to change in the future.":
"将来可能会改变。",
"### Device types and routing setup":
"### 设备类型与路由设置",
"Different kinds of sub-devices have differing behaviour for route activation,":
"不同种类的子设备对于路由激活具有不同的行为，",
"depending on the hardware. In all cases, however, only routes that have the":
"这取决于硬件。但在所有情况下，只有设置了",
"`V4L2_SUBDEV_ROUTE_FL_ACTIVE` flag set are active.":
"`V4L2_SUBDEV_ROUTE_FL_ACTIVE` 标志的路由才是活动的。",
"Devices generating the streams may allow enabling and disabling some of the":
"生成流的设备可能允许启用和禁用某些",
"routes or have a fixed routing configuration. If the routes can be disabled, not":
"路由，或者具有固定的路由配置。如果路由可以被禁用，则不在",
"declaring the routes (or declaring them without `V4L2_SUBDEV_ROUTE_FL_ACTIVE`":
"`VIDIOC_SUBDEV_S_ROUTING` 中声明路由（或声明时不设置 `V4L2_SUBDEV_ROUTE_FL_ACTIVE`",
"flag set) in `VIDIOC_SUBDEV_S_ROUTING` will disable the routes.":
"标志）将禁用这些路由。",
"`VIDIOC_SUBDEV_S_ROUTING` will still return such routes back to the user in":
"`VIDIOC_SUBDEV_S_ROUTING` 仍会将这些路由返回给用户，",
"the routes array, with the `V4L2_SUBDEV_ROUTE_FL_ACTIVE` flag unset.":
"位于 routes 数组中，且 `V4L2_SUBDEV_ROUTE_FL_ACTIVE` 标志未设置。",
"Devices transporting the streams almost always have more configurability with":
"传输流的设备几乎总是在路由方面具有更高的",
"respect to routing. Typically any route between the sub-device's sink and source":
"可配置性。通常，子设备 sink 和 source",
"pads is possible, and multiple routes (usually up to certain limited number) may":
"pads 之间的任何路由都是可能的，并且多个路由（通常上限为某个有限数量）可以",
"be active simultaneously. For such devices, no routes are created by the driver":
"同时处于活动状态。对于此类设备，驱动不会创建任何路由，",
"and user-created routes are fully replaced when `VIDIOC_SUBDEV_S_ROUTING` is":
"当用户在子设备上调用 `VIDIOC_SUBDEV_S_ROUTING` 时，",
"called on the sub-device. Such newly created routes have the device's default":
"用户创建的路由会被完全替换。这些新创建的路由具有设备默认的",
"configuration for format and selection rectangles.":
"格式和选择矩形配置。",
"### Configuring streams":
"### 配置流",
"The configuration of the streams is done individually for each sub-device and":
"流的配置是针对每个子设备单独进行的，",
"the validity of the streams between sub-devices is validated when the pipeline":
"子设备之间流的有效性在管线",
"is started.":
"启动时进行验证。",
"There are three steps in configuring the streams:":
"配置流分为",
"1. Set up links. Connect the pads between sub-devices using the":
"1. 设置 links。使用",
"   Media Controller API <media_controller>":
"   Media Controller API <media_controller> 连接子设备之间的 pads。",
"2. Streams. Streams are declared and their routing is configured by setting the":
"2. 流。通过为子设备设置路由表来声明流并配置其路由，使用",
"   routing table for the sub-device using :ref:`VIDIOC_SUBDEV_S_ROUTING":
"   :ref:`VIDIOC_SUBDEV_S_ROUTING",
"   <VIDIOC_SUBDEV_G_ROUTING>` ioctl. Note that setting the routing table will":
"   <VIDIOC_SUBDEV_G_ROUTING>` ioctl。注意，设置路由表会",
"   reset formats and selections in the sub-device to default values.":
"   将子设备中的格式和选择重置为默认值。",
"3. Configure formats and selections. Formats and selections of each stream are":
"3. 配置格式和选择。每个流的格式和选择",
"   configured separately as documented for plain sub-devices in":
"   按照纯子设备的文档（见 format-propagation）分别配置。",
"   format-propagation. The stream ID is set to the same stream ID":
"   流 ID 被设置为与通过",
"   associated with either sink or source pads of routes configured using the":
"   VIDIOC_SUBDEV_S_ROUTING <VIDIOC_SUBDEV_G_ROUTING> ioctl 配置的路由的",
"   VIDIOC_SUBDEV_S_ROUTING <VIDIOC_SUBDEV_G_ROUTING> ioctl.":
"   sink 或 source pads 相关联的同一个流 ID。",
"### Multiplexed streams setup example":
"### 多路复用流配置示例",
"A simple example of a multiplexed stream setup might be as follows:":
"一个多路复用流配置的简单示例如下：",
"- Two identical sensors (Sensor A and Sensor B). Each sensor has a single source":
"- 两个相同的传感器（Sensor A 和 Sensor B）。每个传感器有一个 source",
"  pad (pad 0) which carries a pixel data stream.":
"  pad（pad 0），承载一个像素数据流。",
"- Multiplexer bridge (Bridge). The bridge has two sink pads, connected to the":
"- 多路复用器桥（Bridge）。该桥有两个 sink pads，连接到",
"  sensors (pads 0, 1), and one source pad (pad 2), which outputs two streams.":
"  传感器（pads 0、1），以及一个 source pad（pad 2），输出两个流。",
"- Receiver in the SoC (Receiver). The receiver has a single sink pad (pad 0),":
"- SoC 中的接收端（Receiver）。接收端有一个 sink pad（pad 0），",
"  connected to the bridge, and two source pads (pads 1-2), going to the DMA":
"  连接到桥，以及两个 source pads（pads 1-2），通向 DMA",
"  engine. The receiver demultiplexes the incoming streams to the source pads.":
"  引擎。接收端将传入的流解复用到 source pads。",
"- DMA Engines in the SoC (DMA Engine), one for each stream. Each DMA engine is":
"- SoC 中的 DMA 引擎（DMA Engine），每个流一个。每个 DMA 引擎",
"  connected to a single source pad in the receiver.":
"  连接到接收端中的一个 source pad。",
"The sensors, the bridge and the receiver are modeled as V4L2 sub-devices,":
"传感器、桥和接收端被建模为 V4L2 子设备，",
"exposed to userspace via /dev/v4l-subdevX device nodes. The DMA engines are":
"通过 /dev/v4l-subdevX 设备节点暴露给用户空间。DMA 引擎被",
"modeled as V4L2 devices, exposed to userspace via /dev/videoX nodes.":
"建模为 V4L2 设备，通过 /dev/videoX 节点暴露给用户空间。",
"To configure this pipeline, the userspace must take the following steps:":
"要配置此管线，用户空间必须采取以下步骤：",
"1. Set up media links between entities: connect the sensors to the bridge,":
"1. 在实体之间建立 media links：将传感器连接到桥，",
"   bridge to the receiver, and the receiver to the DMA engines. This step does":
"   桥连接到接收端，接收端连接到 DMA 引擎。此步骤与",
"   not differ from normal non-multiplexed media controller setup.":
"   普通的未多路复用 media controller 设置没有区别。",
"2. Configure routing":
"2. 配置路由",
"    - - Sink Pad/Stream":
"    - - Sink Pad/流",
"      - Source Pad/Stream":
"      - Source Pad/流",
"      - Routing Flags":
"      - 路由标志",
"      - Comments":
"      - 注释",
"      - Pixel data stream from Sensor A":
"      - 来自 Sensor A 的像素数据流",
"      - Pixel data stream from Sensor B":
"      - 来自 Sensor B 的像素数据流",
"3. Configure formats and selections":
"3. 配置格式和选择",
"   After configuring routing, the next step is configuring the formats and":
"   配置路由之后，下一步是配置流的格式和",
"   selections for the streams. This is similar to performing this step without":
"   选择。这与在没有流的情况下执行此步骤类似，",
"   streams, with just one exception: the `stream` field needs to be assigned":
"   只有一个例外：`stream` 字段需要被赋值为",
"   to the value of the stream ID.":
"   流 ID 的值。",
"   A common way to accomplish this is to start from the sensors and propagate":
"   实现这一点的常见方法是从传感器开始，沿流",
"   the configurations along the stream towards the receiver, using":
"   向接收端传播配置，使用",
"   VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctls to configure each":
"   VIDIOC_SUBDEV_S_FMT <VIDIOC_SUBDEV_G_FMT> ioctl 来配置每个",
"   stream endpoint in each sub-device.":
"   子设备中的每个流端点。",
}

src = open(F, encoding='utf-8').read()
out_lines = []
for line in src.split('\n'):
    key = line.rstrip()
    out_lines.append(T.get(key, line))
new = '\n'.join(out_lines)

n = new.count('```')
assert n % 2 == 0, "fence odd: %d" % n

tmp = F + '.tmp'
open(tmp, 'w', encoding='utf-8').write(new)
os.replace(tmp, F)
print("dev-subdev done; fences:", n)