const fs = require('fs');
let content = fs.readFileSync('D:/WORKSPACE/fakeToys/oa4rust-web/apps/desktop/src/views/ProcessDesigner.vue', 'utf8');
const marker = 'onUnmounted(() => {\n  document.removeEventListener';
const idx = content.indexOf(marker);
if (idx === -1) { console.log('NOT FOUND'); process.exit(1); }
const L = [];
L.push('');
L.push('// --- Canvas Annotations ---');
L.push('interface Annotation { id: string; x: number; y: number; text: string; color: string; w: number; h: number }');
L.push('const annotations = ref<Annotation[]>([])');
L.push('const showAnnotations = ref(false)');
L.push('const newAnnotation = ref({ text: "", color: "#f59e0b" })');
L.push('function addAnnotation() {');
L.push('  if (!processDef.value) return');
L.push('  const rect = canvasRef.value?.getBoundingClientRect()');
L.push('  if (!rect) return');
L.push('  const cx = (rect.width/2 - panX.value) / zoom.value');
L.push('  const cy = (rect.height/2 - panY.value) / zoom.value');
L.push('  annotations.value.push({ id: genId(), x: cx - 60, y: cy - 20, text: newAnnotation.value.text || "备注", color: newAnnotation.value.color, w: 120, h: 60 })');
L.push('  newAnnotation.value = { text: "", color: "#f59e0b" }');
L.push('}');
L.push('function deleteAnnotation(idx: number) { annotations.value.splice(idx, 1) }');
L.push('function updateAnnotation(idx: number, prop: keyof Annotation, val: any) { if (annotations.value[idx]) annotations.value[idx][prop] = val }');
L.push('');
L.push('// --- Snap to Grid ---');
L.push('const snapToGrid = ref(true)');
L.push('const gridSnapThreshold = ref(15)');
L.push('const showGrid = ref(true)');
L.push('const customGridSize = ref(GRID_SIZE)');
L.push('function toggleSnap() { snapToGrid.value = !snapToGrid.value }');
L.push('function setGridSize(size: number) { if (customGridSize) customGridSize.value = Math.max(10, Math.min(50, size)) }');
L.push('');
L.push('// --- Node Alignment ---');
L.push('type AlignDir = "left"|"right"|"top"|"bottom"|"center-x"|"center-y"|"distribute-h"|"distribute-v"');
L.push('function alignNodes(dir: AlignDir) {');
L.push('  if (!processDef.value) return');
L.push('  const ids = selectedNode.value !== null ? [processDef.value.nodes[selectedNode.value]!.id] : Array.from(multiSelected.value)');
L.push('  if (ids.length < 2) return');
L.push('  const nodes = ids.map(id => processDef.value!.nodes.find(n => n.id === id)).filter(Boolean) as PDNode[]');
L.push('  switch(dir) {');
L.push('    case "left": { const minX = Math.min(...nodes.map(n => n.x)); nodes.forEach(n => n.x = minX) break }');
L.push('    case "right": { const maxX = Math.max(...nodes.map(n => n.x + (n.w||120))); nodes.forEach(n => n.x = maxX - (n.w||120)) break }');
L.push('    case "top": { const minY = Math.min(...nodes.map(n => n.y)); nodes.forEach(n => n.y = minY) break }');
L.push('    case "bottom": { const maxY = Math.max(...nodes.map(n => n.y + (n.h||50))); nodes.forEach(n => n.y = maxY - (n.h||50)) break }');
L.push('    case "center-x": { const cx = nodes.reduce((s,n) => s + n.x + (n.w||120)/2, 0) / nodes.length; nodes.forEach(n => n.x = cx - (n.w||120)/2) break }');
L.push('    case "center-y": { const cy = nodes.reduce((s,n) => s + n.y + (n.h||50)/2, 0) / nodes.length; nodes.forEach(n => n.y = cy - (n.h||50)/2) break }');
L.push('  }');
L.push('  pushHistory()');
L.push('}');
L.push('');
L.push('// --- Batch Operations ---');
L.push('function batchSetProperty(prop: string, val: any) {');
L.push('  if (!processDef.value) return');
L.push('  const ids = selectedNode.value !== null ? [processDef.value.nodes[selectedNode.value]!.id] : Array.from(multiSelected.value)');
L.push('  for (const id of ids) { const n = processDef.value.nodes.find(nd => nd.id === id); if (n) (n as any)[prop] = val }');
L.push('  pushHistory()');
L.push('}');
L.push('function batchSetColor(color: string) { batchSetProperty("style", color) }');
L.push('');
L.push('// --- Connection Validation ---');
L.push('interface ValidationResult { valid: boolean; issues: Array<{type: string; message: string; severity: "error"|"warning"}>; stats: {totalNodes: number; totalEdges: number; isolatedNodes: number; missingStart: boolean; missingEnd: boolean; unreachableNodes: string[]} }');
L.push('function validateConnections(): ValidationResult {');
L.push('  if (!processDef.value) return { valid: false, issues: [], stats: {totalNodes:0,totalEdges:0,isolatedNodes:0,missingStart:true,missingEnd:true,unreachableNodes:[]} }');
L.push('  const nodes = processDef.value.nodes, edges = processDef.value.edges || []');
L.push('  const issues: Array<{type:string;message:string;severity:"error"|"warning"}> = []');
L.push('  const starts = nodes.filter(n => n.type === "start")');
L.push('  if (starts.length === 0) issues.push({ type: "missing-start", message: "流程缺少开始节点", severity: "error" })');
L.push('  const ends = nodes.filter(n => n.type === "end")');
L.push('  if (ends.length === 0) issues.push({ type: "missing-end", message: "流程缺少结束节点", severity: "error" })');
L.push('  const connectedIds = new Set<string>()');
L.push('  for (const e of edges) { connectedIds.add(e.from); connectedIds.add(e.to) }');
L.push('  const isolated = nodes.filter(n => !connectedIds.has(n.id) && n.type !== "start" && n.type !== "end")');
L.push('  for (const n of isolated) issues.push({ type: "isolated", message: "未连接: " + (n.label||n.id), severity: "warning" })');
L.push('  const reachable = new Set<string>()');
L.push('  if (starts.length > 0) { const q = [starts[0].id]; while(q.length){ const c=q.shift()!; if(reachable.has(c))continue; reachable.add(c); for(const e of edges){ if(e.from===c&&!reachable.has(e.to))q.push(e.to) } } }');
L.push('  const unreachable = nodes.filter(n => !reachable.has(n.id) && n.type!=="start").map(n=>n.label||n.id)');
L.push('  for (const id of unreachable) issues.push({ type: "unreachable", message: "无法到达: " + id, severity: "warning" })');
L.push('  const es = new Set<string>()');
L.push('  for (const e of edges) { const k=e.from+"-"+e.to; if(es.has(k)) issues.push({type:"dup",message:"重复连线",severity:"warning"}); else es.add(k) }');
L.push('  for (const e of edges) { if(e.from===e.to) issues.push({type:"loop",message:"自环",severity:"warning"}) }');
L.push('  const valid = issues.filter(i=>i.severity==="error").length===0');
L.push('  return { valid, issues, stats: {totalNodes:nodes.length,totalEdges:edges.length,isolatedNodes:isolated.length,missingStart:starts.length===0,missingEnd:ends.length===0,unreachableNodes:unreachable} }');
L.push('}');
L.push('');
L.push('// --- Dimension Presets ---');
L.push('const dimPresets = [{name:"窄型",w:80,h:40},{name:"标准",w:120,h:50},{name:"宽型",w:160,h:50},{name:"高型",w:120,h:80},{name:"大方块",w:140,h:140},{name:"标签",w:100,h:30}]');
L.push('function applyDimPreset(idx: number) {');
L.push('  if (selectedNode.value===null||!processDef.value) return');
L.push('  const p = dimPresets[idx]; if(!p) return');
L.push('  const n = processDef.value.nodes[selectedNode.value]; n.w=p.w; n.h=p.h; pushHistory()');
L.push('}');
L.push('');
L.push('// --- Flow Analysis ---');
L.push('interface FlowInfo { nodeId:string; label:string; inDegree:number; outDegree:number; role:string }');
L.push('function computeFlowInfo(): FlowInfo[] {');
L.push('  if (!processDef.value) return []');
L.push('  const nodes = processDef.value.nodes, edges = processDef.value.edges||[]');
L.push('  return nodes.map(n => {');
L.push('    const inD = edges.filter(e=>e.to===n.id).length, outD = edges.filter(e=>e.from===n.id).length');
L.push('    let role = "内部节点"');
L.push('    if (n.type==="start") role="入口"');
L.push('    else if (n.type==="end") role="出口"');
L.push('    else if (inD===0&&outD>0) role="起始"');
L.push('    else if (inD>0&&outD===0) role="终止"');
L.push('    else if (inD===0&&outD===0) role="孤立"');
L.push('    return {nodeId:n.id, label:n.label||n.id, inDegree:inD, outDegree:outD, role}');
L.push('  }).sort((a,b)=>b.outDegree-a.outDegree||a.inDegree-b.inDegree)');
L.push('}');
L.push('const flowInfo = computed(() => computeFlowInfo())');
L.push('');
L.push('// --- Process Archive ---');
L.push('interface ProcessArchive { id:string; timestamp:number; name:string; nodeCount:number; edgeCount:number; snapshot:{nodes:PDNode[];edges:PDEdge[]} }');
L.push('const processArchive = ref<ProcessArchive[]>([])');
L.push('function archiveCurrent() {');
L.push('  if (!processDef.value||!currentProcess.value) return');
L.push('  processArchive.value.unshift({id:genId(),timestamp:Date.now(),name:currentProcess.value.name||"未命名",nodeCount:processDef.value.nodes.length,edgeCount:(processDef.value.edges||[]).length,snapshot:JSON.parse(JSON.stringify(processDef.value))})');
L.push('  if (processArchive.value.length>50) processArchive.value.pop()');
L.push('}');
L.push('function restoreArchive(idx:number) {');
L.push('  if (idx>=processArchive.value.length||!processDef.value) return');
L.push('  const snap = processArchive.value[idx].snapshot');
L.push('  processDef.value = {nodes:snap.nodes, edges:snap.edges||[]}');
L.push('  selectedNode.value=null; selectedEdge.value=null; pushHistory()');
L.push('}');
L.push('function deleteArchive(idx:number) { processArchive.value.splice(idx,1) }');
const nc = content.substring(0, idx) + L.join('\n') + content.substring(idx);
fs.writeFileSync('D:/WORKSPACE/fakeToys/oa4rust-web/apps/desktop/src/views/ProcessDesigner.vue', nc);
console.log('Lines:', nc.split('\n').length);
