/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.portal.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.portal.core.entity.Page.class)
public class Page_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Page,String> alias;
    public static volatile SingularAttribute<Page,String> category;
    public static volatile SingularAttribute<Page,String> data;
    public static volatile SingularAttribute<Page,String> description;
    public static volatile SingularAttribute<Page,Boolean> hasMobile;
    public static volatile SingularAttribute<Page,String> id;
    public static volatile SingularAttribute<Page,String> mobileData;
    public static volatile SingularAttribute<Page,String> name;
    public static volatile SingularAttribute<Page,String> portal;
    public static volatile SingularAttribute<Page,PageProperties> properties;
}
