/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.portal.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.portal.core.entity.PageVersion.class)
public class PageVersion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<PageVersion,String> data;
    public static volatile SingularAttribute<PageVersion,String> id;
    public static volatile SingularAttribute<PageVersion,String> page;
    public static volatile SingularAttribute<PageVersion,String> person;
}
