/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity.message;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.message.DocumentEvent.class)
public class DocumentEvent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DocumentEvent,String> appInfo;
    public static volatile SingularAttribute<DocumentEvent,String> document;
    public static volatile SingularAttribute<DocumentEvent,String> id;
    public static volatile SingularAttribute<DocumentEvent,String> type;
}
