#!/usr/bin/env python3
"""Cluster behavior-compare FAIL diffs into candidate rename pairs.

Reads a behavior-report.md (generated by `cargo test --test behavior_compare`),
parses the markdown table failures, and clusters field-level diffs into
candidate rename pairs (field-A missing-in-Java + field-B missing-in-Rust).

Outputs (to target/):
  - diff_candidates.tsv   (machine-readable: pair, frequency, example endpoints)
  - diff_candidates.md    (human-reviewable: sorted by frequency, evidence excerpts)

Usage:
    python oa4rust/scripts/cluster_behavior_diffs.py [path/to/behavior-report.md]

If no path given, defaults to target/debug/behavior-report.md.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# Diff pattern classification
# ──────────────────────────────────────────────────────────────────────────────

# Matches: "field: missing in Java" or "field.sub: missing in Java"
MISSING_IN_JAVA_RE = re.compile(r'([\w.]+):\s*missing in Java')
# Matches: "field: missing in Rust" or "field.sub: missing in Rust"
MISSING_IN_RUST_RE = re.compile(r'([\w.]+):\s*missing in Rust')
# Matches: "field: array length differs ..." or "field: type differs"
TYPE_DIFFERS_RE = re.compile(r'([\w.]+):\s*(?:array length differs|type differs)')

REPORT_DEFAULT = Path(__file__).resolve().parent.parent / 'target' / 'debug' / 'behavior-report.md'
OUTPUT_DIR = Path(__file__).resolve().parent.parent / 'target'


def parse_report(report_path: Path) -> list[dict]:
    """Parse behavior-report.md into a list of failure records.

    Each record: {crate, method, endpoint, diffs: [str]}
    """
    if not report_path.exists():
        print(f"Error: report not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    text = report_path.read_text(encoding='utf-8')
    failures = []
    current_crate = None

    for line in text.splitlines():
        # Crate header: ### Crate: `name`
        m = re.match(r'^###\s+Crate:\s*`([^`]+)`', line)
        if m:
            current_crate = m.group(1)
            continue

        # Table data row: | METHOD | /jaxrs/... | diff1<br>diff2 |
        if line.startswith('|') and not line.startswith('| Method') and not line.startswith('|---'):
            cols = [c.strip() for c in line.split('|')[1:-1]]
            if len(cols) >= 3 and current_crate:
                method = cols[0].strip()
                endpoint = cols[1].strip()
                raw_diffs = cols[2]
                # Split on <br> or <br/> (markdown line breaks in table cells)
                diffs = [d.strip() for d in re.split(r'<br\s*/?>', raw_diffs) if d.strip()]
                failures.append({
                    'crate': current_crate,
                    'method': method,
                    'endpoint': endpoint,
                    'diffs': diffs,
                })

    return failures


def classify_diff(diff_str: str) -> tuple[str, str] | None:
    """Classify a single diff string into (category, field_name) or None.

    Categories:
      - ('missing_java', field)  → field present in Rust, missing in Java
      - ('missing_rust', field)  → field present in Java, missing in Rust
      - ('type_differs', field)  → type/shape mismatch
    """
    m = MISSING_IN_JAVA_RE.search(diff_str)
    if m:
        return ('missing_java', m.group(1))
    m = MISSING_IN_RUST_RE.search(diff_str)
    if m:
        return ('missing_rust', m.group(1))
    m = TYPE_DIFFERS_RE.search(diff_str)
    if m:
        return ('type_differs', m.group(1))
    return None


def cluster_pairs(failures: list[dict]) -> dict:
    """Cluster failures into candidate rename pairs and other categories.

    Returns dict with keys:
      - pairs: {(field_a, field_b): {freq, examples: [{crate, method, endpoint}]}}
      - single_missing_java: {field: {freq, examples}}
      - single_missing_rust: {field: {freq, examples}}
      - type_differs: {field: {freq, examples}}
    """
    # Per-endpoint analysis: collect missing_java and missing_rust fields
    # A "pair" = same endpoint has BOTH missing_java(A) and missing_rust(B)
    endpoint_fields = defaultdict(lambda: {'missing_java': set(), 'missing_rust': set(), 'type_differs': set()})

    for f in failures:
        key = (f['crate'], f['method'], f['endpoint'])
        for diff in f['diffs']:
            classified = classify_diff(diff)
            if classified:
                cat, field = classified
                endpoint_fields[key][cat].add(field)

    # Find pairs: endpoints that have both missing_java(A) and missing_rust(B)
    pair_count = defaultdict(lambda: {'freq': 0, 'examples': []})
    single_java = defaultdict(lambda: {'freq': 0, 'examples': []})
    single_rust = defaultdict(lambda: {'freq': 0, 'examples': []})
    type_diff = defaultdict(lambda: {'freq': 0, 'examples': []})

    for (crate, method, endpoint), fields in endpoint_fields.items():
        mj = fields['missing_java']
        mr = fields['missing_rust']
        td = fields['type_differs']

        # Cross-product pairs: each A in missing_java × each B in missing_rust
        # if same endpoint has both → candidate rename pair
        if mj and mr:
            for a in sorted(mj):
                for b in sorted(mr):
                    pair_key = (a, b)
                    pair_count[pair_key]['freq'] += 1
                    if len(pair_count[pair_key]['examples']) < 3:
                        pair_count[pair_key]['examples'].append({
                            'crate': crate, 'method': method, 'endpoint': endpoint
                        })

        # Singles: fields that appear only on one side
        paired_java = set()
        paired_rust = set()
        if mj and mr:
            # These are already counted as pairs
            paired_java = mj
            paired_rust = mr

        for a in mj - paired_java:
            single_java[a]['freq'] += 1
            if len(single_java[a]['examples']) < 3:
                single_java[a]['examples'].append({
                    'crate': crate, 'method': method, 'endpoint': endpoint
                })

        for b in mr - paired_rust:
            single_rust[b]['freq'] += 1
            if len(single_rust[b]['examples']) < 3:
                single_rust[b]['examples'].append({
                    'crate': crate, 'method': method, 'endpoint': endpoint
                })

        for field in td:
            type_diff[field]['freq'] += 1
            if len(type_diff[field]['examples']) < 3:
                type_diff[field]['examples'].append({
                    'crate': crate, 'method': method, 'endpoint': endpoint
                })

    return {
        'pairs': dict(pair_count),
        'single_missing_java': dict(single_java),
        'single_missing_rust': dict(single_rust),
        'type_differs': dict(type_diff),
    }


def write_tsv(clusters: dict, output_path: Path) -> None:
    """Write machine-readable TSV of candidate pairs."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('pair_a\tpair_b\tfreq\texample_endpoints\n')
        for (a, b), data in sorted(clusters['pairs'].items(), key=lambda x: -x[1]['freq']):
            examples = '; '.join(
                f"{e['crate']}/{e['method']} {e['endpoint']}"
                for e in data['examples']
            )
            f.write(f"{a}\t{b}\t{data['freq']}\t{examples}\n")


def write_markdown(clusters: dict, output_path: Path) -> None:
    """Write human-reviewable Markdown report."""
    lines = [
        '# Behavior Diff Clustering Report',
        '',
        f'Generated by: `oa4rust/scripts/cluster_behavior_diffs.py`',
        '',
    ]

    # Section 1: Candidate rename pairs
    pairs = clusters['pairs']
    lines.append(f'## Candidate Rename Pairs ({len(pairs)} unique)')
    lines.append('')
    if pairs:
        lines.append('| Rank | Field A (missing in Java) | Field B (missing in Rust) | Freq | Example Endpoints |')
        lines.append('|------|--------------------------|--------------------------|------|-------------------|')
        for rank, ((a, b), data) in enumerate(
            sorted(pairs.items(), key=lambda x: -x[1]['freq']), 1
        ):
            examples = '; '.join(
                f"`{e['method']} {e['endpoint']}`"
                for e in data['examples']
            )
            lines.append(f'| {rank} | `{a}` | `{b}` | {data["freq"]} | {examples} |')
    else:
        lines.append('No paired diffs found.')
    lines.append('')

    # Section 2: Single-side missing (Java only)
    sj = clusters['single_missing_java']
    lines.append(f'## Missing in Java Only ({len(sj)} unique fields)')
    lines.append('')
    if sj:
        lines.append('| Field | Freq | Example Endpoints |')
        lines.append('|-------|------|-------------------|')
        for field, data in sorted(sj.items(), key=lambda x: -x[1]['freq']):
            examples = '; '.join(
                f"`{e['method']} {e['endpoint']}`" for e in data['examples']
            )
            lines.append(f'| `{field}` | {data["freq"]} | {examples} |')
    lines.append('')

    # Section 3: Single-side missing (Rust only)
    sr = clusters['single_missing_rust']
    lines.append(f'## Missing in Rust Only ({len(sr)} unique fields)')
    lines.append('')
    if sr:
        lines.append('| Field | Freq | Example Endpoints |')
        lines.append('|-------|------|-------------------|')
        for field, data in sorted(sr.items(), key=lambda x: -x[1]['freq']):
            examples = '; '.join(
                f"`{e['method']} {e['endpoint']}`" for e in data['examples']
            )
            lines.append(f'| `{field}` | {data["freq"]} | {examples} |')
    lines.append('')

    # Section 4: Type differs
    td = clusters['type_differs']
    lines.append(f'## Type / Shape Differs ({len(td)} unique fields)')
    lines.append('')
    if td:
        lines.append('| Field | Freq | Example Endpoints |')
        lines.append('|-------|------|-------------------|')
        for field, data in sorted(td.items(), key=lambda x: -x[1]['freq']):
            examples = '; '.join(
                f"`{e['method']} {e['endpoint']}`" for e in data['examples']
            )
            lines.append(f'| `{field}` | {data["freq"]} | {examples} |')
    lines.append('')

    output_path.write_text('\n'.join(lines), encoding='utf-8')


# ──────────────────────────────────────────────────────────────────────────────
# Self-test with synthetic report fragment
# ──────────────────────────────────────────────────────────────────────────────

def self_test() -> bool:
    """Run a minimal test with a synthetic report fragment."""
    synthetic = """# Behavior Comparison Report

**Generated:** 2026-08-26T00:00:00+00:00

## Summary

- **Total endpoints:** 10
- **Passed:** 5
- **Failed:** 5
- **Skipped:** 0

## Failures

### Crate: `control`

| Method | Endpoint | Differences |
|--------|----------|-------------|
| GET | /jaxrs/control/unit/list/{flag} | data.owner: missing in Java<br>data.creator: missing in Rust |
| GET | /jaxrs/control/person/list/{flag} | data.owner: missing in Java<br>data.creator: missing in Rust |
| GET | /jaxrs/control/group/list/{flag} | data.label: missing in Java |
| GET | /jaxrs/control/role/list/{flag} | data.count: missing in Rust |

### Crate: `express`

| Method | Endpoint | Differences |
|--------|----------|-------------|
| GET | /jaxrs/express/delivery/list | data.total: type differs<br>data.count: missing in Java<br>data.size: missing in Rust |
"""
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False, encoding='utf-8') as f:
        f.write(synthetic)
        tmp = Path(f.name)

    try:
        failures = parse_report(tmp)
        assert len(failures) == 5, f"Expected 5 failures, got {len(failures)}"

        clusters = cluster_pairs(failures)

        # owner/creator should be a pair (freq=2: unit + person endpoints)
        pairs = clusters['pairs']
        assert ('data.owner', 'data.creator') in pairs, \
            f"Expected (data.owner, data.creator) pair, got: {list(pairs.keys())}"
        assert pairs[('data.owner', 'data.creator')]['freq'] == 2

        # label should be single_missing_java (freq=1)
        assert 'data.label' in clusters['single_missing_java']

        # size pairs with count in express endpoint
        assert ('data.count', 'data.size') in pairs

        # count also appears as single_missing_rust in control (no paired missing_java there)
        assert 'data.count' in clusters['single_missing_rust']

        # type differs: total
        assert 'data.total' in clusters['type_differs']

        # Write test outputs
        out_tsv = OUTPUT_DIR / 'diff_candidates_test.tsv'
        out_md = OUTPUT_DIR / 'diff_candidates_test.md'
        write_tsv(clusters, out_tsv)
        write_markdown(clusters, out_md)
        assert out_tsv.exists()
        assert out_md.exists()

        print("self_test: PASSED")
        return True
    finally:
        tmp.unlink()


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) > 1 and sys.argv[1] == '--test':
        ok = self_test()
        sys.exit(0 if ok else 1)

    report_path = Path(sys.argv[1]) if len(sys.argv) > 1 else REPORT_DEFAULT
    failures = parse_report(report_path)
    print(f"Parsed {len(failures)} failure records from {report_path}")

    clusters = cluster_pairs(failures)

    n_pairs = len(clusters['pairs'])
    n_sj = len(clusters['single_missing_java'])
    n_sr = len(clusters['single_missing_rust'])
    n_td = len(clusters['type_differs'])
    print(f"Clusters: {n_pairs} candidate pairs, {n_sj} single-Java, {n_sr} single-Rust, {n_td} type-differs")

    out_tsv = OUTPUT_DIR / 'diff_candidates.tsv'
    out_md = OUTPUT_DIR / 'diff_candidates.md'
    write_tsv(clusters, out_tsv)
    write_markdown(clusters, out_md)
    print(f"Written: {out_tsv}")
    print(f"Written: {out_md}")


if __name__ == '__main__':
    main()
