#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_mcp_tools.py — 从 oa4rust crates 源码扫描路由定义，生成 MCP 工具注册代码。

输出：
  - crates/mcp_server/src/generated_routes.rs（Rust 代码，可直接 include!）

用法：
  python scripts/gen_mcp_tools.py
"""

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CRATES_DIR = ROOT / "crates"
OUTPUT_FILE = CRATES_DIR / "mcp_server" / "src" / "generated_routes.rs"

# 权限级别映射（路径前缀 -> 是否需要认证）
PUBLIC_PREFIXES = [
    "/jaxrs/authentication",
    "/jaxrs/authentication/captcha",
    "/jaxrs/authentication/oauth",
    "/jaxrs/authentication/code",
    "/jaxrs/authentication/refresh",
    "/jaxrs/reset",
    "/jaxrs/secret/check",
    "/jaxrs/secret/set",
    "/health",
]

def is_public_path(path: str) -> bool:
    for prefix in PUBLIC_PREFIXES:
        if path.startswith(prefix):
            return True
    return False

def parse_routes_from_file(filepath: Path) -> list:
    """从 Rust 源码中提取路由定义。"""
    try:
        text = filepath.read_text(encoding="utf-8")
    except Exception:
        return []

    routes = []
    # 匹配 .route("METHOD path", handler) 模式
    pattern = r'\.route\(\s*"([^"]+)",\s*(\w+)\((\w+)\)'
    for match in re.finditer(pattern, text):
        path = match.group(1)
        method_str = match.group(2)  # get, post, put, delete
        handler = match.group(3)
        method = method_str.upper()
        routes.append((path, method, handler))
    return routes

def extract_crate_name(filepath: Path) -> str:
    """从文件路径提取 crate 名称。"""
    parts = filepath.parts
    # crates/<crate_name>/src/...
    for i, part in enumerate(parts):
        if part == "crates" and i + 1 < len(parts):
            return parts[i + 1]
    return "unknown"

def path_to_tool_name(crate: str, path: str, method: str) -> str:
    """将路由路径转换为 MCP 工具名称。"""
    # 移除 /jaxrs/ 前缀
    p = path.replace("/jaxrs/", "")
    # 将路径段转换为下划线命名
    parts = p.split("/")
    tool_parts = []
    for part in parts:
        # 处理路径参数 {param}
        param_match = re.match(r"\{(.+?)\}", part)
        if param_match:
            tool_parts.append(param_match.group(1).lower())
        else:
            # 转换 camelCase 为 snake_case
            s = re.sub(r'([A-Z])', r'_\1', part).lower().strip("_")
            tool_parts.append(s)
    return f"jaxrs_{crate}_{'_'.join(tool_parts)}"

def extract_path_params(path: str) -> list:
    """从路径提取路径参数名称。"""
    return re.findall(r"\{(.+?)\}", path)

def infer_body_params(method: str, path: str) -> list:
    """根据 HTTP method 推断 body 参数。"""
    if method in ("GET", "HEAD"):
        return []
    # POST/PUT/DELETE 通常有 body
    # 简单启发式：根据路径段推断常见参数名
    params = []
    path_lower = path.lower()
    if "password" in path_lower:
        params.append("password")
    if "credential" in path_lower:
        params.append("credential")
    if "name" in path_lower:
        params.append("name")
    if "token" in path_lower:
        params.append("token")
    return params

def main():
    all_routes = []

    # 扫描所有 crate 的 src 目录
    for crate_dir in sorted(CRATES_DIR.iterdir()):
        if not crate_dir.is_dir():
            continue
        src_dir = crate_dir / "src"
        if not src_dir.is_dir():
            continue

        crate_name = crate_dir.name
        for rs_file in src_dir.rglob("*.rs"):
            routes = parse_routes_from_file(rs_file)
            for path, method, handler in routes:
                all_routes.append({
                    "crate": crate_name,
                    "path": path,
                    "method": method,
                    "handler": handler,
                })

    # 去重
    seen = set()
    unique_routes = []
    for r in all_routes:
        key = (r["crate"], r["path"], r["method"])
        if key not in seen:
            seen.add(key)
            unique_routes.append(r)

    # 生成 Rust 代码
    lines = []
    lines.append("// AUTO-GENERATED by scripts/gen_mcp_tools.py — DO NOT EDIT")
    lines.append("// This file defines GENERATED_ROUTE_DEFS as a Vec<RouteDef>")
    lines.append("")
    lines.append("/// 自动生成的 MCP 工具路由定义（Vec 版本，避免宏依赖）")
    lines.append("pub static GENERATED_ROUTE_DEFS: &[RouteDef] = &[")

    for r in sorted(unique_routes, key=lambda x: (x["crate"], x["method"], x["path"])):
        tool_name = path_to_tool_name(r["crate"], r["path"], r["method"])
        path_params = extract_path_params(r["path"])
        body_params = infer_body_params(r["method"], r["path"])
        http_method = r["method"].capitalize()
        requires_auth = not is_public_path(r["path"])

    lines.append(f'    RouteDef {{')
    lines.append(f'        tool_name: "{tool_name}",')
    lines.append(f'        method: HttpMethod::{http_method},')
    lines.append(f'        path: "{r["path"]}",')
    lines.append(f'        description: "{r["handler"]} handler",')
    lines.append(f'        path_params: &[{", ".join(f'"{p}"' for p in path_params)}],')
    lines.append(f'        body_params: &[{", ".join(f'"{p}"' for p in body_params)}],')
    lines.append(f'    }},')

    lines.append("];")
    lines.append("")
    lines.append(f"/// 生成的工具总数")
    lines.append(f"pub const GENERATED_TOOL_COUNT: usize = {len(unique_routes)};")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated {len(unique_routes)} MCP tool definitions -> {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
