/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.general.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.general.core.entity.ApplicationDict.class)
public class ApplicationDict_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ApplicationDict,String> alias;
    public static volatile SingularAttribute<ApplicationDict,String> application;
    public static volatile SingularAttribute<ApplicationDict,String> description;
    public static volatile SingularAttribute<ApplicationDict,String> id;
    public static volatile SingularAttribute<ApplicationDict,String> name;
    public static volatile SingularAttribute<ApplicationDict,String> project;
}
