/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.general.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.general.core.entity.GeneralFile.class)
public class GeneralFile_ extends StorageObject_  {
    public static volatile SingularAttribute<GeneralFile,Boolean> deepPath;
    public static volatile SingularAttribute<GeneralFile,String> extension;
    public static volatile SingularAttribute<GeneralFile,String> id;
    public static volatile SingularAttribute<GeneralFile,Date> lastUpdateTime;
    public static volatile SingularAttribute<GeneralFile,Long> length;
    public static volatile SingularAttribute<GeneralFile,String> name;
    public static volatile SingularAttribute<GeneralFile,String> person;
    public static volatile SingularAttribute<GeneralFile,String> storage;
}
