/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.general.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.general.core.entity.Invoice.class)
public class Invoice_ extends StorageObject_  {
    public static volatile SingularAttribute<Invoice,Double> amount;
    public static volatile SingularAttribute<Invoice,String> applyStatus;
    public static volatile SingularAttribute<Invoice,String> buyerAccount;
    public static volatile SingularAttribute<Invoice,String> buyerAddress;
    public static volatile SingularAttribute<Invoice,String> buyerCode;
    public static volatile SingularAttribute<Invoice,String> buyerName;
    public static volatile SingularAttribute<Invoice,String> code;
    public static volatile SingularAttribute<Invoice,String> date;
    public static volatile SingularAttribute<Invoice,Boolean> deepPath;
    public static volatile SingularAttribute<Invoice,String> detail;
    public static volatile SingularAttribute<Invoice,String> drawer;
    public static volatile SingularAttribute<Invoice,String> endStation;
    public static volatile SingularAttribute<Invoice,String> extension;
    public static volatile SingularAttribute<Invoice,String> id;
    public static volatile SingularAttribute<Invoice,Date> invoiceDate;
    public static volatile SingularAttribute<Invoice,Date> lastUpdateTime;
    public static volatile SingularAttribute<Invoice,Long> length;
    public static volatile SingularAttribute<Invoice,String> name;
    public static volatile SingularAttribute<Invoice,String> number;
    public static volatile SingularAttribute<Invoice,String> person;
    public static volatile SingularAttribute<Invoice,InvoiceProperties> properties;
    public static volatile SingularAttribute<Invoice,String> remark;
    public static volatile SingularAttribute<Invoice,String> rider;
    public static volatile SingularAttribute<Invoice,String> sellerAccount;
    public static volatile SingularAttribute<Invoice,String> sellerAddress;
    public static volatile SingularAttribute<Invoice,String> sellerCode;
    public static volatile SingularAttribute<Invoice,String> sellerName;
    public static volatile SingularAttribute<Invoice,String> startStation;
    public static volatile SingularAttribute<Invoice,String> storage;
    public static volatile SingularAttribute<Invoice,Double> taxAmount;
    public static volatile SingularAttribute<Invoice,String> title;
    public static volatile SingularAttribute<Invoice,Double> totalAmount;
    public static volatile SingularAttribute<Invoice,String> totalAmountString;
    public static volatile SingularAttribute<Invoice,String> type;
}
