-- Rollback for 020_create_processplatform_tables.sql
DROP TABLE IF EXISTS x_job CASCADE;
DROP TABLE IF EXISTS x_process_definition CASCADE;
DROP TABLE IF EXISTS x_document_version CASCADE;
DROP TABLE IF EXISTS x_attachment CASCADE;
DROP TABLE IF EXISTS x_readcompleted CASCADE;
DROP TABLE IF EXISTS x_read CASCADE;
DROP TABLE IF EXISTS x_draft CASCADE;
DROP TABLE IF EXISTS x_workcompleted CASCADE;
DROP TABLE IF EXISTS x_record CASCADE;
DROP TABLE IF EXISTS x_snap CASCADE;
DROP TABLE IF EXISTS x_review CASCADE;
DROP TABLE IF EXISTS x_task CASCADE;
DROP TABLE IF EXISTS x_work CASCADE;
