-- migration 036: create 9 additional missing x_* tables referenced by handlers.

CREATE TABLE IF NOT EXISTS "x_general_assemble_excel_result" (
    "id" VARCHAR PRIMARY KEY,
    "Debug" VARCHAR,
    "allowRegistration" VARCHAR,
    "allow_registration" VARCHAR,
    "can_delete" VARCHAR,
    "can_edit" VARCHAR,
    "can_view" VARCHAR,
    "city" VARCHAR,
    "content" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "creator" VARCHAR,
    "date" TIMESTAMPTZ,
    "description" VARCHAR,
    "district" VARCHAR,
    "enabled" BOOLEAN,
    "excelName" VARCHAR,
    "excel_id" VARCHAR,
    "excel_name" VARCHAR,
    "file_url" VARCHAR,
    "flag" VARCHAR,
    "height" VARCHAR,
    "htmlContent" VARCHAR,
    "html_content" VARCHAR,
    "is_holiday" VARCHAR,
    "is_workday" VARCHAR,
    "is_worktime" VARCHAR,
    "level" VARCHAR,
    "maintenanceMode" VARCHAR,
    "maintenance_mode" VARCHAR,
    "minutes" VARCHAR,
    "module_name" VARCHAR,
    "name" VARCHAR,
    "object" VARCHAR,
    "parentId" VARCHAR,
    "parent_id" VARCHAR,
    "province" VARCHAR,
    "result" VARCHAR,
    "sheet_name" VARCHAR,
    "size" BIGINT,
    "status" VARCHAR,
    "subject" VARCHAR,
    "system_name" VARCHAR,
    "text" VARCHAR,
    "total" BIGINT,
    "type" VARCHAR,
    "unit_id" VARCHAR,
    "user_id" VARCHAR,
    "value" VARCHAR,
    "version" VARCHAR,
    "width" VARCHAR,
    "word_flag" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_general_assemble_excel_result" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_general_assemble_general_file" (
    "id" VARCHAR PRIMARY KEY,
    "Debug" VARCHAR,
    "allowRegistration" VARCHAR,
    "allow_registration" VARCHAR,
    "can_delete" VARCHAR,
    "can_edit" VARCHAR,
    "can_view" VARCHAR,
    "city" VARCHAR,
    "content" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "creator" VARCHAR,
    "date" TIMESTAMPTZ,
    "description" VARCHAR,
    "district" VARCHAR,
    "enabled" BOOLEAN,
    "excelName" VARCHAR,
    "excel_id" VARCHAR,
    "excel_name" VARCHAR,
    "file_url" VARCHAR,
    "flag" VARCHAR,
    "height" VARCHAR,
    "htmlContent" VARCHAR,
    "html_content" VARCHAR,
    "is_holiday" VARCHAR,
    "is_workday" VARCHAR,
    "is_worktime" VARCHAR,
    "level" VARCHAR,
    "maintenanceMode" VARCHAR,
    "maintenance_mode" VARCHAR,
    "minutes" VARCHAR,
    "module_name" VARCHAR,
    "name" VARCHAR,
    "object" VARCHAR,
    "parentId" VARCHAR,
    "parent_id" VARCHAR,
    "province" VARCHAR,
    "result" VARCHAR,
    "sheet_name" VARCHAR,
    "size" BIGINT,
    "status" VARCHAR,
    "subject" VARCHAR,
    "system_name" VARCHAR,
    "text" VARCHAR,
    "total" BIGINT,
    "type" VARCHAR,
    "unit_id" VARCHAR,
    "user_id" VARCHAR,
    "value" VARCHAR,
    "version" VARCHAR,
    "width" VARCHAR,
    "word_flag" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_general_assemble_general_file" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_meeting_checkin_code" (
    "id" VARCHAR PRIMARY KEY,
    "String" VARCHAR,
    "address" VARCHAR,
    "checkin_code" VARCHAR,
    "checkin_id" VARCHAR,
    "completed" BOOLEAN,
    "completedTime" TIMESTAMPTZ,
    "config" VARCHAR,
    "configKey" VARCHAR,
    "configValue" VARCHAR,
    "config_key" VARCHAR,
    "config_value" VARCHAR,
    "content" VARCHAR,
    "controlType" VARCHAR,
    "control_type" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "creator" VARCHAR,
    "day" VARCHAR,
    "description" VARCHAR,
    "enabled" BOOLEAN,
    "endTime" TIMESTAMPTZ,
    "end_date" TIMESTAMPTZ,
    "end_time" TIMESTAMPTZ,
    "expire_time" TIMESTAMPTZ,
    "flag" VARCHAR,
    "i32" VARCHAR,
    "i64" VARCHAR,
    "invite_id" VARCHAR,
    "invitee" VARCHAR,
    "limit" VARCHAR,
    "meetingId" VARCHAR,
    "meeting_id" VARCHAR,
    "month" VARCHAR,
    "name" VARCHAR,
    "page" VARCHAR,
    "person" VARCHAR,
    "photo_name" VARCHAR,
    "photo_url" VARCHAR,
    "pinyin" VARCHAR,
    "pinyin_initial" VARCHAR,
    "room" VARCHAR,
    "start" VARCHAR,
    "startTime" TIMESTAMPTZ,
    "start_date" TIMESTAMPTZ,
    "start_time" TIMESTAMPTZ,
    "status" VARCHAR,
    "title" VARCHAR,
    "year" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_meeting_checkin_code" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_meeting_room_photo" (
    "id" VARCHAR PRIMARY KEY,
    "String" VARCHAR,
    "address" VARCHAR,
    "checkin_code" VARCHAR,
    "checkin_id" VARCHAR,
    "completed" BOOLEAN,
    "completedTime" TIMESTAMPTZ,
    "completed_time" TIMESTAMPTZ,
    "config" VARCHAR,
    "configKey" VARCHAR,
    "configValue" VARCHAR,
    "config_key" VARCHAR,
    "config_value" VARCHAR,
    "content" VARCHAR,
    "controlType" VARCHAR,
    "control_type" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "creator" VARCHAR,
    "day" VARCHAR,
    "description" VARCHAR,
    "enabled" BOOLEAN,
    "endTime" TIMESTAMPTZ,
    "end_date" TIMESTAMPTZ,
    "end_time" TIMESTAMPTZ,
    "expire_time" TIMESTAMPTZ,
    "flag" VARCHAR,
    "i32" VARCHAR,
    "i64" VARCHAR,
    "invite_id" VARCHAR,
    "invitee" VARCHAR,
    "limit" VARCHAR,
    "meetingId" VARCHAR,
    "meeting_id" VARCHAR,
    "month" VARCHAR,
    "name" VARCHAR,
    "page" VARCHAR,
    "person" VARCHAR,
    "photo_name" VARCHAR,
    "photo_url" VARCHAR,
    "pinyin" VARCHAR,
    "pinyin_initial" VARCHAR,
    "room" VARCHAR,
    "start" VARCHAR,
    "startTime" TIMESTAMPTZ,
    "start_date" TIMESTAMPTZ,
    "start_time" TIMESTAMPTZ,
    "status" VARCHAR,
    "title" VARCHAR,
    "year" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_meeting_room_photo" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_message_config" (
    "id" VARCHAR PRIMARY KEY,
    "String" VARCHAR,
    "business_id" VARCHAR,
    "config_key" VARCHAR,
    "config_value" VARCHAR,
    "consume" VARCHAR,
    "consume_time" TIMESTAMPTZ,
    "content" VARCHAR,
    "conversationId" VARCHAR,
    "conversation_id" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "enabled" BOOLEAN,
    "fileName" VARCHAR,
    "fileSize" VARCHAR,
    "fileUrl" VARCHAR,
    "file_name" VARCHAR,
    "file_size" BIGINT,
    "file_url" VARCHAR,
    "icon_name" VARCHAR,
    "icon_url" VARCHAR,
    "idList" VARCHAR,
    "join_time" TIMESTAMPTZ,
    "last_message" VARCHAR,
    "mass_id" VARCHAR,
    "messageId" VARCHAR,
    "message_id" VARCHAR,
    "msg_type" VARCHAR,
    "name" VARCHAR,
    "note" VARCHAR,
    "person" VARCHAR,
    "person_id" VARCHAR,
    "read_status" VARCHAR,
    "role" VARCHAR,
    "sender" VARCHAR,
    "title" VARCHAR,
    "true" VARCHAR,
    "type" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_message_config" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_message_conversation_icon" (
    "id" VARCHAR PRIMARY KEY,
    "String" VARCHAR,
    "business_id" VARCHAR,
    "config_key" VARCHAR,
    "config_value" VARCHAR,
    "consume" VARCHAR,
    "consume_time" TIMESTAMPTZ,
    "content" VARCHAR,
    "conversationId" VARCHAR,
    "conversation_id" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "enabled" BOOLEAN,
    "fileName" VARCHAR,
    "fileSize" VARCHAR,
    "fileUrl" VARCHAR,
    "file_name" VARCHAR,
    "file_size" BIGINT,
    "file_url" VARCHAR,
    "icon_name" VARCHAR,
    "icon_url" VARCHAR,
    "idList" VARCHAR,
    "join_time" TIMESTAMPTZ,
    "last_message" VARCHAR,
    "mass_id" VARCHAR,
    "messageId" VARCHAR,
    "message_id" VARCHAR,
    "msg_type" VARCHAR,
    "name" VARCHAR,
    "note" VARCHAR,
    "person" VARCHAR,
    "person_id" VARCHAR,
    "read_status" VARCHAR,
    "role" VARCHAR,
    "sender" VARCHAR,
    "title" VARCHAR,
    "type" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_message_conversation_icon" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_process_bam" (
    "id" VARCHAR PRIMARY KEY,
    "application" VARCHAR,
    "completed" BOOLEAN,
    "expired" BOOLEAN,
    "organization_id" VARCHAR,
    "organization_name" VARCHAR,
    "process_count" VARCHAR,
    "process_key" VARCHAR,
    "process_name" VARCHAR,
    "running" VARCHAR,
    "total" BIGINT,
    "create_time" TIMESTAMPTZ,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_process_bam" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_process_organization" (
    "id" VARCHAR PRIMARY KEY,
    "application" VARCHAR,
    "completed" BOOLEAN,
    "expired" BOOLEAN,
    "organization_id" VARCHAR,
    "organization_name" VARCHAR,
    "process_count" VARCHAR,
    "process_key" VARCHAR,
    "process_name" VARCHAR,
    "running" VARCHAR,
    "total" BIGINT,
    "create_time" TIMESTAMPTZ,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_process_organization" IS 'auto-created for parity';

CREATE TABLE IF NOT EXISTS "x_program_deploy_server" (
    "id" VARCHAR PRIMARY KEY,
    "app_data" VARCHAR,
    "app_id" VARCHAR,
    "app_name" VARCHAR,
    "application" VARCHAR,
    "category" VARCHAR,
    "content" VARCHAR,
    "create_time" TIMESTAMPTZ,
    "creator" VARCHAR,
    "cron_expression" VARCHAR,
    "disable" VARCHAR,
    "entity" VARCHAR,
    "error_type" VARCHAR,
    "eventType" VARCHAR,
    "exception_class" VARCHAR,
    "field_count" VARCHAR,
    "field_label" VARCHAR,
    "field_name" VARCHAR,
    "field_type" VARCHAR,
    "flag" VARCHAR,
    "imported_content" VARCHAR,
    "key" VARCHAR,
    "key_name" VARCHAR,
    "logger_name" VARCHAR,
    "message" VARCHAR,
    "name" VARCHAR,
    "orgId" VARCHAR,
    "page" VARCHAR,
    "path" VARCHAR,
    "person_id" VARCHAR,
    "resource_name" VARCHAR,
    "resource_type" VARCHAR,
    "schedule_id" VARCHAR,
    "select_file" VARCHAR,
    "server_node" VARCHAR,
    "server_url" VARCHAR,
    "stack_trace" VARCHAR,
    "status" VARCHAR,
    "table_name" VARCHAR,
    "threshold" VARCHAR,
    "title" VARCHAR,
    "url" VARCHAR,
    "userId" VARCHAR,
    "value" VARCHAR,
    "version" VARCHAR,
    "update_time" TIMESTAMPTZ,
    "creator_person" VARCHAR,
    "creator_unit" VARCHAR,
    "last_update_person" VARCHAR,
    "sequence" VARCHAR,
    "xid" VARCHAR,
    "xcreateTime" TIMESTAMPTZ,
    "xupdateTime" TIMESTAMPTZ,
    "xowner" VARCHAR
);
COMMENT ON TABLE "x_program_deploy_server" IS 'auto-created for parity';
