/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.IMConversationExt.class)
public class IMConversationExt_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<IMConversationExt,String> conversationId;
    public static volatile SingularAttribute<IMConversationExt,String> id;
    public static volatile SingularAttribute<IMConversationExt,Boolean> isDeleted;
    public static volatile SingularAttribute<IMConversationExt,Boolean> isTop;
    public static volatile SingularAttribute<IMConversationExt,Date> lastDeleteTime;
    public static volatile SingularAttribute<IMConversationExt,Date> lastReadTime;
    public static volatile SingularAttribute<IMConversationExt,String> person;
}
