/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.IMMsgFile.class)
public class IMMsgFile_ extends StorageObject_  {
    public static volatile SingularAttribute<IMMsgFile,String> conversationId;
    public static volatile SingularAttribute<IMMsgFile,Boolean> deepPath;
    public static volatile SingularAttribute<IMMsgFile,String> extension;
    public static volatile SingularAttribute<IMMsgFile,String> id;
    public static volatile SingularAttribute<IMMsgFile,Date> lastUpdateTime;
    public static volatile SingularAttribute<IMMsgFile,Long> length;
    public static volatile SingularAttribute<IMMsgFile,String> name;
    public static volatile SingularAttribute<IMMsgFile,String> person;
    public static volatile SingularAttribute<IMMsgFile,String> storage;
    public static volatile SingularAttribute<IMMsgFile,String> type;
}
