/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.IMMsg.class)
public class IMMsg_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<IMMsg,String> body;
    public static volatile SingularAttribute<IMMsg,String> bodyFileId;
    public static volatile SingularAttribute<IMMsg,String> conversationId;
    public static volatile SingularAttribute<IMMsg,String> createPerson;
    public static volatile SingularAttribute<IMMsg,String> id;
    public static volatile SingularAttribute<IMMsg,String> quoteMessageId;
}
