/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.IMMsgCollection.class)
public class IMMsgCollection_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<IMMsgCollection,String> createPerson;
    public static volatile SingularAttribute<IMMsgCollection,String> id;
    public static volatile SingularAttribute<IMMsgCollection,String> messageId;
}
