/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.Instant.class)
public class Instant_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Instant,String> body;
    public static volatile SingularAttribute<Instant,Boolean> consumed;
    public static volatile SingularAttribute<Instant,String> id;
    public static volatile SingularAttribute<Instant,String> person;
    public static volatile SingularAttribute<Instant,String> title;
    public static volatile SingularAttribute<Instant,String> type;
}
