/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.message.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.message.core.entity.Message.class)
public class Message_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Message,String> body;
    public static volatile SingularAttribute<Message,Boolean> consumed;
    public static volatile SingularAttribute<Message,String> consumer;
    public static volatile SingularAttribute<Message,String> id;
    public static volatile SingularAttribute<Message,String> instant;
    public static volatile SingularAttribute<Message,String> person;
    public static volatile SingularAttribute<Message,MessageProperties> properties;
    public static volatile SingularAttribute<Message,String> title;
    public static volatile SingularAttribute<Message,String> type;
}
