/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSSubjectContent.class)
public class BBSSubjectContent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSSubjectContent,String> content;
    public static volatile SingularAttribute<BBSSubjectContent,String> id;
}
