/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSShutup.class)
public class BBSShutup_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSShutup,String> id;
    public static volatile SingularAttribute<BBSShutup,String> operator;
    public static volatile SingularAttribute<BBSShutup,String> person;
    public static volatile SingularAttribute<BBSShutup,String> reason;
    public static volatile SingularAttribute<BBSShutup,String> unmuteDate;
    public static volatile SingularAttribute<BBSShutup,Date> unmuteDateTime;
}
