#[cfg(test)]
mod tests {

    // SKIPPED: create_design not accessible
    // SKIPPED: get_design not accessible
    // SKIPPED: list_designs not accessible
    // SKIPPED: save_design not accessible
    // SKIPPED: list_pages_by_category not accessible
    // SKIPPED: get_page not accessible
    // SKIPPED: create_page not accessible
    // SKIPPED: save_page not accessible
    // SKIPPED: delete_page not accessible
    // SKIPPED: design_list not accessible
    // SKIPPED: design_get not accessible
    // SKIPPED: design_save not accessible
    // SKIPPED: designer_search not accessible
    // SKIPPED: dict_list_paging_page_size_size not accessible
    // SKIPPED: dict_list_portal_portalId not accessible
    // SKIPPED: dict_id not accessible
    // SKIPPED: file_list_application_applicationFlag not accessible
    // SKIPPED: file_list_id_next_count not accessible
    // SKIPPED: file_list_id_prev_count not accessible
    // SKIPPED: file_flag not accessible
    // SKIPPED: file_id not accessible
    // SKIPPED: file_id_download not accessible
    // SKIPPED: file_id_upload not accessible
    // SKIPPED: id_count not accessible
    // SKIPPED: input_compare not accessible
    // SKIPPED: input_cover not accessible
    // SKIPPED: input_create not accessible
    // SKIPPED: input_prepare_cover not accessible
    // SKIPPED: input_prepare_create not accessible
    // SKIPPED: output_list not accessible
    // SKIPPED: output_flag_select_file not accessible
    // SKIPPED: output_portalFlag_select not accessible
    // SKIPPED: page_list_portal_portalId not accessible
    // SKIPPED: page_id not accessible
    // SKIPPED: pageversion_list_page_pageId not accessible
    // SKIPPED: pageversion_id not accessible
    // SKIPPED: portal_list not accessible
    // SKIPPED: portal_list_portalcategory_portalCategory not accessible
    // SKIPPED: portal_list_summary not accessible
    // SKIPPED: portal_list_summary_portalcategory_portalCategory not accessible
    // SKIPPED: portal_list_summary_v2 not accessible
    // SKIPPED: portal_id not accessible
    // SKIPPED: portal_id_icon not accessible
    // SKIPPED: portal_id_permission not accessible
    // SKIPPED: portalcategory_list not accessible
    // SKIPPED: script_list_manager not accessible
    // SKIPPED: script_list_paging_page_size_size not accessible
    // SKIPPED: script_list_portal_portalId not accessible
    // SKIPPED: script_id not accessible
    // SKIPPED: scriptversion_list_script_scriptId not accessible
    // SKIPPED: scriptversion_id not accessible
    // SKIPPED: templatepage_list not accessible
    // SKIPPED: templatepage_list_category not accessible
    // SKIPPED: templatepage_id not accessible
    // SKIPPED: widget_list_portal_portalId not accessible
    // SKIPPED: widget_id not accessible
}