/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.index;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.index.State.class)
public class State_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<State,String> freq;
    public static volatile SingularAttribute<State,String> id;
    public static volatile SingularAttribute<State,Date> latestUpdateTime;
    public static volatile SingularAttribute<State,String> mode;
    public static volatile SingularAttribute<State,String> node;
    public static volatile SingularAttribute<State,StateProperties> properties;
    public static volatile SingularAttribute<State,String> type;
}
