use std::sync::Arc;
use std::time::Duration;

use reqwest::Client;
use serde_json::json;
use tracing::info;

use crate::integration_tests::db::{TestPool, TEST_DB};

// ──────────────────────────────────────────────────────────────────────────────
// BPMN / workflow execution semantics (U2.2 core)
//
// Proves a minimal real workflow against PostgreSQL through the HTTP layer:
//   work/create  →  execute (gateway/task generation)  →  task query
//                →  agree(approve)  →  process/complex reload
//
// Every step performs genuine DB reads/writes via the routed
// processplatform_service_processing handlers. The work and task state must
// progress: work starts "running", the executed task is created, and after
// agree() the task is "completed" and the work is archived as "completed".
//
// See also `bpmn_task_actions_flow` for the disagree / transfer / return
// (reject / reassign / 退回) decision semantics.
// ──────────────────────────────────────────────────────────────────────────────

#[tokio::test]
#[ignore = "requires a running database server"]
pub async fn bpmn_process_flow() {
    let pool = TEST_DB
        .as_pg().unwrap().get()
        .expect("test database not initialized; call init_test_database() first")
        .clone();

    let (_addr, server_handle, token) = crate::integration_tests::helpers::setup_test_server(pool.clone())
        .await
        .expect("failed to start test server");

    let client = Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .expect("failed to build reqwest client");

    let base = format!("http://{}", _addr);
    let auth_header = format!("Bearer {}", token);

    let run_id = std::process::id();
    let process_id = format!("bpmn-it-process-{}", run_id);
    let application_id = format!("bpmn-it-app-{}", run_id);

    // Step 1: Start a process (work/create). Inserts x_work (status=running).
    let create_resp = client
        .post(format!("{}/jaxrs/processplatform/service/processing/work/create", base))
        .header("Authorization", &auth_header)
        .json(&json!({
            "processId": process_id,
            "applicationId": application_id,
            "creator": "it-admin"
        }))
        .send()
        .await
        .expect("work/create request failed");

    assert_eq!(
        create_resp.status(),
        reqwest::StatusCode::OK,
        "work/create failed: {}",
        create_resp.text().await.unwrap_or_default()
    );
    let create_body: serde_json::Value = create_resp.json().await.expect("invalid work/create response");
    let work_id = create_body["data"]["id"]
        .as_str()
        .expect("work/create did not return a work id")
        .to_string();
    assert_eq!(create_body["data"]["status"].as_str(), Some("running"));
    info!(work_id = %work_id, "work created");

    // Step 2: Gateway evaluation / task generation (execute/{id}).
    // Sets work to processing and inserts an x_task.
    let exec_resp = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/execute/{}",
            base, work_id
        ))
        .header("Authorization", &auth_header)
        .send()
        .await
        .expect("execute request failed");
    assert_eq!(
        exec_resp.status(),
        reqwest::StatusCode::OK,
        "execute failed: {}",
        exec_resp.text().await.unwrap_or_default()
    );
    let exec_body: serde_json::Value = exec_resp.json().await.expect("invalid execute response");
    let task_id = exec_body["data"]["taskId"]
        .as_str()
        .expect("execute did not return a task id")
        .to_string();
    assert_eq!(exec_body["data"]["status"].as_str(), Some("processing"));
    info!(task_id = %task_id, "task generated by gateway");

    // Step 3: Task query (task/v2/{id}). Must return real DB row.
    let task_resp = client
        .get(format!(
            "{}/jaxrs/processplatform/service/processing/task/v2/{}",
            base, task_id
        ))
        .header("Authorization", &auth_header)
        .send()
        .await
        .expect("task query request failed");
    assert_eq!(task_resp.status(), reqwest::StatusCode::OK);
    let task_body: serde_json::Value = task_resp.json().await.expect("invalid task query response");
    assert_eq!(task_body["data"]["id"].as_str(), Some(task_id.as_str()));
    assert_eq!(task_body["data"]["work"].as_str(), Some(work_id.as_str()));
    info!(task_status = %task_body["data"]["task_status"], "task queried");

    // Step 4: agree(approve) the task. Completes the task and archives the work.
    let agree_resp = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/agree",
            base, task_id
        ))
        .header("Authorization", &auth_header)
        .send()
        .await
        .expect("agree request failed");
    assert_eq!(
        agree_resp.status(),
        reqwest::StatusCode::OK,
        "agree failed: {}",
        agree_resp.text().await.unwrap_or_default()
    );
    let agree_body: serde_json::Value = agree_resp.json().await.expect("invalid agree response");
    assert_eq!(agree_body["data"]["agreed"].as_bool(), Some(true));
    assert_eq!(agree_body["data"]["taskStatus"].as_str(), Some("completed"));
    assert_eq!(agree_body["data"]["workStatus"].as_str(), Some("completed"));
    info!(task_status = %agree_body["data"]["taskStatus"], work_status = %agree_body["data"]["workStatus"], "task agreed and work archived");

    // Step 5: Process definition reload (process/{id}/complex) — tasks must be
    // present and reflect the completed task.
    let complex_resp = client
        .get(format!(
            "{}/jaxrs/processplatform/service/processing/process/{}/complex",
            base, work_id
        ))
        .header("Authorization", &auth_header)
        .send()
        .await
        .expect("process complex request failed");
    assert_eq!(complex_resp.status(), reqwest::StatusCode::OK);
    let complex_body: serde_json::Value = complex_resp.json().await.expect("invalid complex response");
    let tasks = complex_body["data"]["tasks"]
        .as_array()
        .expect("process complex missing tasks array");
    assert!(
        tasks.iter().any(|t| t["id"].as_str() == Some(task_id.as_str())),
        "completed task not present in process complex view"
    );
    info!(task_count = %tasks.len(), "process complex reloaded with task");

    server_handle.abort();
    let _ = server_handle.await;
}

// ──────────────────────────────────────────────────────────────────────────────
// BPMN task decision semantics: disagree / transfer / return (U2.2 core)
//
// Proves the three user-task decision actions perform genuine DB writes and
// drive correct x_task / x_work / x_record state:
//   - transfer(commission): reassign task to a new person, task stays pending.
//   - return(退回): non-terminal — current task becomes `returned`, an
//     x_record(type='return') is written, the flow reactivates the previous
//     step (or the task itself when it is the first step) to `pending`, and the
//     work returns to `processing`.
//   - disagree(reject): terminal — task becomes `rejected`, x_record(type=
//     'disagree') written, work becomes `rejected`.
//
// Crucially, each action is verified against the real database (x_record rows
// and x_task/x_work status), not just the HTTP 200 response.
// ──────────────────────────────────────────────────────────────────────────────
#[tokio::test]
#[ignore = "requires a running database server"]
pub async fn bpmn_task_actions_flow() {
    let pool = TEST_DB
        .as_pg().unwrap().get()
        .expect("test database not initialized; call init_test_database() first")
        .clone();

    let (_addr, server_handle, token) = crate::integration_tests::helpers::setup_test_server(pool.clone())
        .await
        .expect("failed to start test server");

    let client = Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .expect("failed to build reqwest client");

    let base = format!("http://{}", _addr);
    let auth_header = format!("Bearer {}", token);

    async fn start_work(client: &Client, base: &str, auth_header: &str, suffix: &str) -> (String, String) {
        let pid = format!("bpmn-it-{}-{}", suffix, std::process::id());
        let aid = format!("bpmn-it-{}-app-{}", suffix, std::process::id());
        let create = client
            .post(format!(
                "{}/jaxrs/processplatform/service/processing/work/create",
                base
            ))
            .header("Authorization", auth_header)
            .json(&json!({"processId": pid, "applicationId": aid, "creator": "it-admin"}))
            .send()
            .await
            .expect("work/create failed");
        assert_eq!(
            create.status(),
            reqwest::StatusCode::OK,
            "work/create failed: {}",
            create.text().await.unwrap_or_default()
        );
        let create_body: serde_json::Value = create.json().await.expect("bad work/create");
        let work_id: String = create_body["data"]["id"]
            .as_str()
            .expect("work/create did not return an id")
            .to_string();
        let exec = client
            .post(format!(
                "{}/jaxrs/processplatform/service/processing/execute/{}",
                base, work_id
            ))
            .header("Authorization", auth_header)
            .send()
            .await
            .expect("execute failed");
        assert_eq!(
            exec.status(),
            reqwest::StatusCode::OK,
            "execute failed: {}",
            exec.text().await.unwrap_or_default()
        );
        let exec_body: serde_json::Value = exec.json().await.expect("bad execute");
        let task_id: String = exec_body["data"]["taskId"]
            .as_str()
            .expect("execute did not return a task id")
            .to_string();
        (work_id, task_id)
    }

    // ── Part A: transfer + return (non-terminal path) ──────────────────────────
    let (_work_a, task_a) = start_work(&client, &base, &auth_header, "xfer").await;
    info!(task_a = %task_a, "work A executed");

    // transfer → reassign to "bob"
    let xfer = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/transfer",
            base, task_a
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"person": "bob"}))
        .send()
        .await
        .expect("transfer failed");
    assert_eq!(
        xfer.status(),
        reqwest::StatusCode::OK,
        "transfer failed: {}",
        xfer.text().await.unwrap_or_default()
    );
    let xfer_body: serde_json::Value = xfer.json().await.expect("bad transfer response");
    assert_eq!(xfer_body["data"]["person"].as_str(), Some("bob"));
    info!(task_a = %task_a, "task transferred to bob");

    // return(退回) → single-task work reactivates itself; work returns to processing
    let ret = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/return",
            base, task_a
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"opinion": "please redo from the start"}))
        .send()
        .await
        .expect("return failed");
    assert_eq!(
        ret.status(),
        reqwest::StatusCode::OK,
        "return failed: {}",
        ret.text().await.unwrap_or_default()
    );
    let ret_body: serde_json::Value = ret.json().await.expect("bad return response");
    assert_eq!(ret_body["data"]["returned"].as_bool(), Some(true));
    assert_eq!(ret_body["data"]["workStatus"].as_str(), Some("processing"));
    assert_eq!(ret_body["data"]["taskStatus"].as_str(), Some("pending"));
    // genuine DB writes: x_record(type='return') must exist
    let rec = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_opt(
            "SELECT record_type FROM x_record WHERE task_id = $1 AND record_type = 'return'",
            &[&task_a],
        )
        .await
        .expect("record query failed");
    assert!(rec.is_some(), "x_record of type 'return' was not written");
    // reactivated task is pending in DB
    let tk = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_one("SELECT task_status FROM x_task WHERE id = $1", &[&task_a])
        .await
        .expect("task query failed");
    let tk_status: String = tk.get("task_status");
    assert_eq!(tk_status, "pending");
    info!(task_a = %task_a, "task returned and reactivated");

    // ── Part B: disagree (terminal reject path) ────────────────────────────────
    let (_work_b, task_b) = start_work(&client, &base, &auth_header, "dis").await;
    info!(task_b = %task_b, "work B executed");

    let dis = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/disagree",
            base, task_b
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"opinion": "rejected by reviewer"}))
        .send()
        .await
        .expect("disagree failed");
    assert_eq!(
        dis.status(),
        reqwest::StatusCode::OK,
        "disagree failed: {}",
        dis.text().await.unwrap_or_default()
    );
    let dis_body: serde_json::Value = dis.json().await.expect("bad disagree response");
    assert_eq!(dis_body["data"]["disagreed"].as_bool(), Some(true));
    assert_eq!(dis_body["data"]["taskStatus"].as_str(), Some("rejected"));
    assert_eq!(dis_body["data"]["workStatus"].as_str(), Some("rejected"));
    // genuine DB write: x_record(type='disagree') must exist
    let rec_b = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_opt(
            "SELECT record_type FROM x_record WHERE task_id = $1 AND record_type = 'disagree'",
            &[&task_b],
        )
        .await
        .expect("record B query failed");
    assert!(rec_b.is_some(), "x_record of type 'disagree' was not written");
    info!(task_b = %task_b, "task disagreed and work rejected");

    server_handle.abort();
    let _ = server_handle.await;
}

// ──────────────────────────────────────────────────────────────────────────────
// BPMN countersign (会签) semantics (U2.2 core)
//
// Proves that a task with multiple assignees (o2server stores them as a
// comma-separated `person` list) only completes, and only advances the work,
// once *every* approver has agreed:
//   - approver A agrees  → task/work stay `processing` (waiting), allAgreed=false
//   - approver B agrees  → task `completed`, work `completed`, allAgreed=true
//
// And that a single reject aborts the whole countersign:
//   - approver A agrees (waiting) → approver B disagrees → work `rejected`.
//
// Every state transition is verified against the real database (x_task /
// x_work status and x_record agree rows), not just the HTTP 200 response.
// ──────────────────────────────────────────────────────────────────────────────
#[tokio::test]
#[ignore = "requires a running database server"]
pub async fn bpmn_countersign_flow() {
    let pool = TEST_DB
        .as_pg().unwrap().get()
        .expect("test database not initialized; call init_test_database() first")
        .clone();

    let (_addr, server_handle, token) = crate::integration_tests::helpers::setup_test_server(pool.clone())
        .await
        .expect("failed to start test server");

    let client = Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .expect("failed to build reqwest client");

    let base = format!("http://{}", _addr);
    let auth_header = format!("Bearer {}", token);

    async fn start_work(client: &Client, base: &str, auth_header: &str, suffix: &str) -> (String, String) {
        let pid = format!("bpmn-cs-{}-{}", suffix, std::process::id());
        let aid = format!("bpmn-cs-{}-app-{}", suffix, std::process::id());
        let create = client
            .post(format!(
                "{}/jaxrs/processplatform/service/processing/work/create",
                base
            ))
            .header("Authorization", auth_header)
            .json(&json!({"processId": pid, "applicationId": aid, "creator": "it-admin"}))
            .send()
            .await
            .expect("work/create failed");
        assert_eq!(
            create.status(),
            reqwest::StatusCode::OK,
            "work/create failed: {}",
            create.text().await.unwrap_or_default()
        );
        let create_body: serde_json::Value = create.json().await.expect("bad work/create");
        let work_id: String = create_body["data"]["id"]
            .as_str()
            .expect("work/create did not return an id")
            .to_string();
        let exec = client
            .post(format!(
                "{}/jaxrs/processplatform/service/processing/execute/{}",
                base, work_id
            ))
            .header("Authorization", auth_header)
            .send()
            .await
            .expect("execute failed");
        assert_eq!(
            exec.status(),
            reqwest::StatusCode::OK,
            "execute failed: {}",
            exec.text().await.unwrap_or_default()
        );
        let exec_body: serde_json::Value = exec.json().await.expect("bad execute");
        let task_id: String = exec_body["data"]["taskId"]
            .as_str()
            .expect("execute did not return a task id")
            .to_string();
        (work_id, task_id)
    }

    // Turn a generated task into a countersign task by setting a comma-separated
    // assignee list (o2server's representation of 会签). `pool` is passed as a
    // parameter because nested functions cannot capture the outer `pool`.
    async fn set_countersign(pool: &Arc<TestPool>, task_id: &str, assignees: &str) {
        pool.as_ref()
            .as_pg()
            .unwrap()
            .get()
            .await
            .expect("pg client")
            .execute(
                "UPDATE x_task SET person = $1, task_status = 'pending' WHERE id = $2",
                &[&assignees, &task_id],
            )
            .await
            .expect("failed to set countersign assignees");
    }

    // ── Part A: both approvers must agree before the work completes ────────────
    let (_work_a, task_a) = start_work(&client, &base, &auth_header, "cs").await;
    set_countersign(&pool, &task_a, "alice,bob").await;
    info!(task_a = %task_a, "countersign task created (alice,bob)");

    // approver A (alice) agrees → still waiting
    let a1 = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/agree",
            base, task_a
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"person": "alice"}))
        .send()
        .await
        .expect("agree A failed");
    assert_eq!(
        a1.status(),
        reqwest::StatusCode::OK,
        "agree A failed: {}",
        a1.text().await.unwrap_or_default()
    );
    let a1_body: serde_json::Value = a1.json().await.expect("bad agree A response");
    assert_eq!(a1_body["data"]["agreed"].as_bool(), Some(true));
    assert_eq!(a1_body["data"]["allAgreed"].as_bool(), Some(false));
    assert_eq!(a1_body["data"]["agreedCount"].as_i64(), Some(1));
    assert_eq!(a1_body["data"]["total"].as_i64(), Some(2));
    assert_eq!(a1_body["data"]["taskStatus"].as_str(), Some("processing"));
    assert_eq!(a1_body["data"]["workStatus"].as_str(), Some("processing"));
    // genuine DB: task is processing, exactly one agree record so far
    let tk_a = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_one("SELECT task_status FROM x_task WHERE id = $1", &[&task_a])
        .await
        .expect("task query failed");
    assert_eq!(tk_a.get::<_, &str>("task_status"), "processing");
    let agreed_n: i64 = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_one(
            "SELECT COUNT(*) FROM x_record WHERE task_id = $1 AND record_type = 'agree'",
            &[&task_a],
        )
        .await
        .expect("agree count failed")
        .get(0);
    assert_eq!(agreed_n, 1);
    info!(task_a = %task_a, "alice agreed, waiting for bob");

    // approver B (bob) agrees → all agreed, work completes
    let a2 = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/agree",
            base, task_a
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"person": "bob"}))
        .send()
        .await
        .expect("agree B failed");
    assert_eq!(
        a2.status(),
        reqwest::StatusCode::OK,
        "agree B failed: {}",
        a2.text().await.unwrap_or_default()
    );
    let a2_body: serde_json::Value = a2.json().await.expect("bad agree B response");
    assert_eq!(a2_body["data"]["allAgreed"].as_bool(), Some(true));
    assert_eq!(a2_body["data"]["agreedCount"].as_i64(), Some(2));
    assert_eq!(a2_body["data"]["taskStatus"].as_str(), Some("completed"));
    assert_eq!(a2_body["data"]["workStatus"].as_str(), Some("completed"));
    let agreed_n2: i64 = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_one(
            "SELECT COUNT(*) FROM x_record WHERE task_id = $1 AND record_type = 'agree'",
            &[&task_a],
        )
        .await
        .expect("agree count failed")
        .get(0);
    assert_eq!(agreed_n2, 2);
    info!(task_a = %task_a, "bob agreed, countersign complete");

    // ── Part B: a single reject aborts the countersign ─────────────────────────
    let (_work_b, task_b) = start_work(&client, &base, &auth_header, "csr").await;
    set_countersign(&pool, &task_b, "carol,dave").await;
    info!(task_b = %task_b, "countersign task created (carol,dave)");

    // carol agrees → waiting
    let b1 = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/agree",
            base, task_b
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"person": "carol"}))
        .send()
        .await
        .expect("agree carol failed");
    assert_eq!(b1.status(), reqwest::StatusCode::OK);
    let b1_body: serde_json::Value = b1.json().await.expect("bad agree carol");
    assert_eq!(b1_body["data"]["allAgreed"].as_bool(), Some(false));
    assert_eq!(b1_body["data"]["workStatus"].as_str(), Some("processing"));

    // dave disagrees → work rejected (countersign aborted)
    let b2 = client
        .post(format!(
            "{}/jaxrs/processplatform/service/processing/task/{}/disagree",
            base, task_b
        ))
        .header("Authorization", &auth_header)
        .json(&json!({"opinion": "dave rejects"}))
        .send()
        .await
        .expect("disagree dave failed");
    assert_eq!(
        b2.status(),
        reqwest::StatusCode::OK,
        "disagree dave failed: {}",
        b2.text().await.unwrap_or_default()
    );
    let b2_body: serde_json::Value = b2.json().await.expect("bad disagree dave");
    assert_eq!(b2_body["data"]["disagreed"].as_bool(), Some(true));
    assert_eq!(b2_body["data"]["taskStatus"].as_str(), Some("rejected"));
    assert_eq!(b2_body["data"]["workStatus"].as_str(), Some("rejected"));
    let rec_b: Option<String> = pool
        .as_pg().unwrap().get()
        .await
        .expect("pg client")
        .query_opt(
            "SELECT record_type FROM x_record WHERE task_id = $1 AND record_type = 'disagree'",
            &[&task_b],
        )
        .await
        .expect("record B query failed")
        .map(|r| r.get("record_type"));
    assert!(rec_b.is_some(), "x_record of type 'disagree' was not written");
    info!(task_b = %task_b, "dave disagreed, countersign aborted");

    server_handle.abort();
    let _ = server_handle.await;
}
