use axum::{
    extract::Extension,
    routing::{get, post, put},
    Router,
};
use deadpool_postgres::Pool;

use crate::{
    cancel_process_instance, create_process, execute_process,
    get_process, get_process_instance, list_processes,
    task_claim, task_complete, task_reject, task_transfer,
    work_complete, work_id_processing, work_start,
    gateway_join, gateway_fork,
    work_list, process_id_complex,
    work_v2_id_terminate, work_v2_id_retract,
    start_timer, cancel_timer, timer::TimerRegistry,
};

pub fn router(pool: Pool) -> Router {
    let timer = TimerRegistry::with_pool(pool.clone());
    timer.start_background();
    let timer_for_router = timer.clone();

    Router::new()
        .route("/jaxrs/processplatform/service/processing/get/{id}", get(get_process))
        .route("/jaxrs/processplatform/service/processing/create", post(create_process))
        .route("/jaxrs/processplatform/service/processing/list/{category}", get(list_processes))
        .route("/jaxrs/processplatform/service/processing/execute/{id}", post(execute_process))
        .route("/jaxrs/processplatform/service/processing/instance/{executionId}", get(get_process_instance))
        .route("/jaxrs/processplatform/service/processing/cancel/{executionId}", post(cancel_process_instance))
        .route("/jaxrs/work/{id}/processing", put(work_id_processing))
        .route("/jaxrs/work/{id}/terminate", post(work_v2_id_terminate))
        .route("/jaxrs/work/{id}/retract", post(work_v2_id_retract))
        .route("/jaxrs/processplatform/service/processing/work/list", get(work_list))
        .route("/jaxrs/processplatform/service/processing/process/{id}/complex", get(process_id_complex))
        .route("/jaxrs/work/{id}/start", post(work_start))
        .route("/jaxrs/work/{id}/complete", post(work_complete))
        .route("/jaxrs/task/{id}/claim", post(task_claim))
        .route("/jaxrs/task/{id}/complete", post(task_complete))
        .route("/jaxrs/task/{id}/reject", post(task_reject))
        .route("/jaxrs/task/{id}/transfer/{person}", post(task_transfer))
        .route("/jaxrs/gateway/{work_id}/{activity_token}/join", post(gateway_join))
        .route("/jaxrs/processplatform/service/processing/gateway/fork/{gateway_instance_id}", post(gateway_fork))
        .route("/jaxrs/processplatform/service/processing/timer/start", post(start_timer))
        .route("/jaxrs/processplatform/service/processing/timer/{job_id}/cancel", post(cancel_timer))
        .route("/jaxrs/processplatform/service/processing/applicationdict/{id}", get(crate::applicationdict_id))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/data/{id}", get(crate::applicationdict_id_path0_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/data/{id}", get(crate::applicationdict_id_path0_path1_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/data/{id}", get(crate::applicationdict_id_path0_path1_path2_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/path3/data/{id}", get(crate::applicationdict_id_path0_path1_path2_path3_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/path3/path4/data/{id}", get(crate::applicationdict_id_path0_path1_path2_path3_path4_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/path3/path4/path5/data/{id}", get(crate::applicationdict_id_path0_path1_path2_path3_path4_path5_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/path3/path4/path5/path6/data/{id}", get(crate::applicationdict_id_path0_path1_path2_path3_path4_path5_path6_data))
        .route("/jaxrs/processplatform/service/processing/applicationdict/path0/path1/path2/path3/path4/path5/path6/path7/data/{id}", get(crate::applicationdict_id_path0_path1_path2_path3_path4_path5_path6_path7_data))
        .route("/jaxrs/processplatform/service/processing/attachment/copy/{work}/{workId}", post(crate::attachment_copy_work_workId))
        .route("/jaxrs/processplatform/service/processing/attachment/copy/workcompleted/{workCompletedId}", post(crate::attachment_copy_workcompleted_workCompletedId))
        .route("/jaxrs/processplatform/service/processing/attachment/edit/text/{id}", post(crate::attachment_edit_id_text))
        .route("/jaxrs/processplatform/service/processing/attachment/{id}", get(crate::attachment_id))
        .route("/jaxrs/processplatform/service/processing/attachment/{id}/{work}/{workId}", get(crate::attachment_id_work_workId))
        .route("/jaxrs/processplatform/service/processing/attachment/workcompleted/{id}/{workCompletedId}", get(crate::attachment_id_workcompleted_workCompletedId))
        .route("/jaxrs/processplatform/service/processing/data/{job}/{job}", get(crate::data_job_job))
        .route("/jaxrs/processplatform/service/processing/data/path/{job}/{job}", get(crate::data_job_job_path))
        .route("/jaxrs/processplatform/service/processing/data/delete/{work}/{id}", post(crate::data_work_id_delete))
        .route("/jaxrs/processplatform/service/processing/data/path/delete/{work}/{id}", post(crate::data_work_id_path_delete))
        .route("/jaxrs/processplatform/service/processing/data/workcompleted/{id}", get(crate::data_workcompleted_id))
        .route("/jaxrs/processplatform/service/processing/data/workcompleted/path/{id}", get(crate::data_workcompleted_id_path))
        .route("/jaxrs/processplatform/service/processing/documentversion/{work}/{work}", get(crate::documentversion_work_work))
        .route("/jaxrs/processplatform/service/processing/form/suitable/activity/{activityId}", get(crate::form_suitable_activity_activityId))
        .route("/jaxrs/processplatform/service/processing/{job}/{job}", get(crate::job_job))
        .route("/jaxrs/processplatform/service/processing/v2/{job}/{job}/{person}/{person}/{view}", get(crate::job_v2_job_person_person_view))
        .route("/jaxrs/processplatform/service/processing/v2/projection/{job}/{job}", get(crate::job_v2_job_projection))
        .route("/jaxrs/processplatform/service/processing/readcompleted/{id}", get(crate::readcompleted_id))
        .route("/jaxrs/processplatform/service/processing/record/{id}", get(crate::record_id))
        .route("/jaxrs/processplatform/service/processing/record/{job}/{job}", get(crate::record_job_job))
        .route("/jaxrs/processplatform/service/processing/record/task/processing", post(crate::record_task_processing))
        .route("/jaxrs/processplatform/service/processing/record/processing/{work}", post(crate::record_work_processing))
        .route("/jaxrs/processplatform/service/processing/record/terminate/{work}", get(crate::record_work_terminate))
        .route("/jaxrs/processplatform/service/processing/review/{id}", get(crate::review_id))
        .route("/jaxrs/processplatform/service/processing/review/init/review", get(crate::review_init_review))
        .route("/jaxrs/processplatform/service/processing/service/touch/{work}/{id}", post(crate::service_work_id_touch))
        .route("/jaxrs/processplatform/service/processing/snap/{id}", get(crate::snap_id))
        .route("/jaxrs/processplatform/service/processing/snap/restore/{id}", get(crate::snap_id_restore))
        .route("/jaxrs/processplatform/service/processing/snap/abandoned/{work}/{workId}/{type}", get(crate::snap_work_workId_type_abandoned))
        .route("/jaxrs/processplatform/service/processing/snap/snap/{work}/{workId}/{type}", get(crate::snap_work_workId_type_snap))
        .route("/jaxrs/processplatform/service/processing/snap/suspend/{work}/{workId}/{type}", get(crate::snap_work_workId_type_suspend))
        .route("/jaxrs/processplatform/service/processing/snap/workcompleted/abandonedworkcompleted/{workCompletedId}/{type}", get(crate::snap_workcompleted_workCompletedId_type_abandonedworkcompleted))
        .route("/jaxrs/processplatform/service/processing/snap/workcompleted/snapworkcompleted/{workCompletedId}/{type}", get(crate::snap_workcompleted_workCompletedId_type_snapworkcompleted))
        .route("/jaxrs/processplatform/service/processing/task/{id}", get(crate::task_id))
        .route("/jaxrs/processplatform/service/processing/task/expire/{id}", get(crate::task_id_expire))
        .route("/jaxrs/processplatform/service/processing/task/pass/expired/{id}", get(crate::task_id_pass_expired))
        .route("/jaxrs/processplatform/service/processing/task/press/{id}", post(crate::task_id_press))
        .route("/jaxrs/processplatform/service/processing/task/processing/{id}", post(crate::task_id_processing))
        .route("/jaxrs/processplatform/service/processing/task/replace/{id}", get(crate::task_id_replace))
        .route("/jaxrs/processplatform/service/processing/task/urge/{id}", get(crate::task_id_urge))
        .route("/jaxrs/processplatform/service/processing/task/will/{id}", post(crate::task_id_will))
        .route("/jaxrs/processplatform/service/processing/task/v2/{id}", get(crate::task_v2_id))
        .route("/jaxrs/processplatform/service/processing/task/v2/pause/{id}", get(crate::task_v2_id_pause))
        .route("/jaxrs/processplatform/service/processing/task/v2/reset/{id}", post(crate::task_v2_id_reset))
        .route("/jaxrs/processplatform/service/processing/task/v2/resume/{id}", post(crate::task_v2_id_resume))
        .route("/jaxrs/processplatform/service/processing/task/v3/add/{id}", post(crate::task_v3_id_add))
        .route("/jaxrs/processplatform/service/processing/taskcompleted/{id}", get(crate::taskcompleted_id))
        .route("/jaxrs/processplatform/service/processing/taskcompleted/press/{id}/{work}/{work}", post(crate::taskcompleted_id_press_work_work))
        .route("/jaxrs/processplatform/service/processing/taskcompleted/task/identity/{next}", get(crate::taskcompleted_next_task_identity))
        .route("/jaxrs/processplatform/service/processing/touch/deletedraft", post(crate::touch_deletedraft))
        .route("/jaxrs/processplatform/service/processing/touch/handoverjob", post(crate::touch_handoverjob))
        .route("/jaxrs/processplatform/service/processing/touch/merge", post(crate::touch_merge))
        .route("/jaxrs/processplatform/service/processing/touch/mergeitem", post(crate::touch_mergeitem))
        .route("/jaxrs/processplatform/service/processing/touch/touchdelay", post(crate::touch_touchdelay))
        .route("/jaxrs/processplatform/service/processing/touch/urge", post(crate::touch_urge))
        .route("/jaxrs/processplatform/service/processing/draft/{work}/{id}", get(crate::work_id_draft))
        .route("/jaxrs/processplatform/service/processing/manual/append/identity/{work}/{id}", get(crate::work_id_manual_append_identity))
        .route("/jaxrs/processplatform/service/processing/projection/{work}/{id}", get(crate::work_id_projection))
        .route("/jaxrs/processplatform/service/processing/series/series/activitytoken/processing/signal/{work}/{id}/{activityToken}", post(crate::work_id_series_series_activitytoken_activityToken_processing_signal))
        .route("/jaxrs/processplatform/service/processing/manual/after/processing/{work}", post(crate::work_manual_after_processing))
        .route("/jaxrs/processplatform/service/processing/process/{work}/{processId}", get(crate::work_process_processId))
        .route("/jaxrs/processplatform/service/processing/process/{work}/{processId}/{name}/{name}/{serial}", get(crate::work_process_processId_name_name_serial))
        .route("/jaxrs/processplatform/service/processing/v2/add/split/{work}/{id}", post(crate::work_v2_id_add_split))
        .route("/jaxrs/processplatform/service/processing/v2/goback/{work}/{id}", get(crate::work_v2_id_goback))
        .route("/jaxrs/processplatform/service/processing/v2/reroute/{work}/{id}", get(crate::work_v2_id_reroute))
        .route("/jaxrs/processplatform/service/processing/v2/rollback/{work}/{id}", get(crate::work_v2_id_rollback))
        .route("/jaxrs/processplatform/service/processing/v3/retract/{work}", get(crate::work_v3_retract))
        .route("/jaxrs/processplatform/service/processing/workcompleted/merge/{flag}", post(crate::workcompleted_flag_merge))
        .route("/jaxrs/processplatform/service/processing/workcompleted/rollback/{flag}", get(crate::workcompleted_flag_rollback))
        .route("/jaxrs/processplatform/service/processing/workcompleted/process/{processFlag}", get(crate::workcompleted_process_processFlag))
        .route("/jaxrs/processplatform/service/processing/workcompleted/shift/time", get(crate::workcompleted_shift_time))
        .layer(Extension(pool))
        .layer(Extension(timer_for_router))
}
