/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.InValue.class)
public class InValue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<InValue,Integer> count;
    public static volatile SingularAttribute<InValue,String> id;
    public static volatile SingularAttribute<InValue,Integer> inTextSerial;
    public static volatile SingularAttribute<InValue,String> model;
    public static volatile SingularAttribute<InValue,Integer> serial;
    public static volatile SingularAttribute<InValue,String> text;
}
