/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.Model.class)
public class Model_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Model,String> alias;
    public static volatile SingularAttribute<Model,String> analyzeType;
    public static volatile ListAttribute<Model,String> applicationList;
    public static volatile SingularAttribute<Model,String> attachmentScriptText;
    public static volatile SingularAttribute<Model,String> dataType;
    public static volatile SingularAttribute<Model,String> description;
    public static volatile SingularAttribute<Model,Integer> effectiveEntryCount;
    public static volatile SingularAttribute<Model,Date> endDate;
    public static volatile SingularAttribute<Model,Integer> entryCount;
    public static volatile SingularAttribute<Model,Integer> generatingPercent;
    public static volatile SingularAttribute<Model,String> id;
    public static volatile SingularAttribute<Model,Integer> inValueCount;
    public static volatile SingularAttribute<Model,String> inValueScriptText;
    public static volatile SingularAttribute<Model,String> intermediateNnet;
    public static volatile SingularAttribute<Model,Integer> learnEntryCount;
    public static volatile SingularAttribute<Model,Integer> maxResult;
    public static volatile SingularAttribute<Model,String> name;
    public static volatile SingularAttribute<Model,String> neuralNetworkType;
    public static volatile SingularAttribute<Model,String> nnet;
    public static volatile SingularAttribute<Model,Integer> outValueCount;
    public static volatile SingularAttribute<Model,String> outValueScriptText;
    public static volatile ListAttribute<Model,String> processList;
    public static volatile MapAttribute<Model,String,String> propertyMap;
    public static volatile SingularAttribute<Model,Date> startDate;
    public static volatile SingularAttribute<Model,String> status;
    public static volatile SingularAttribute<Model,Double> totalError;
    public static volatile SingularAttribute<Model,Integer> validationEntryCount;
    public static volatile SingularAttribute<Model,Double> validationMeanSquareError;
}
