/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.OutValue.class)
public class OutValue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OutValue,Integer> count;
    public static volatile SingularAttribute<OutValue,String> id;
    public static volatile SingularAttribute<OutValue,String> model;
    public static volatile SingularAttribute<OutValue,Integer> serial;
    public static volatile SingularAttribute<OutValue,String> text;
}
