#[cfg(test)]
mod tests {

    // SKIPPED: list_control_rules not accessible
    // SKIPPED: toggle_control_rule not accessible
    // SKIPPED: attendanceadmin_list_all not accessible
    // SKIPPED: attendanceadmin_id not accessible
    // SKIPPED: attendanceappealInfo_appeal_id not accessible
    // SKIPPED: attendanceconfig_list not accessible
    // SKIPPED: attendanceconfig_save not accessible
    // SKIPPED: attendanceappealInfo_archive_id not accessible
    // SKIPPED: attendanceappealInfo_audit not accessible
    // SKIPPED: attendanceappealInfo_check not accessible
    // SKIPPED: attendanceappealInfo_filter_list_id_next_count not accessible
    // SKIPPED: attendanceappealInfo_filter_list_id_prev_count not accessible
    // SKIPPED: attendanceappealInfo_manager_list_id_next_count not accessible
    // SKIPPED: attendanceappealInfo_workflow_appeal_id not accessible
    // SKIPPED: attendanceappealInfo_workflow_sync not accessible
    // SKIPPED: attendanceappealInfo_id not accessible
    // SKIPPED: attendancedetail_analyse not accessible
    // SKIPPED: attendancedetail_analyse_id_id not accessible
    // SKIPPED: attendancedetail_analyse_redo not accessible
    // SKIPPED: attendancedetail_analyse_startDate_endDate not accessible
    // SKIPPED: attendancedetail_archive_id not accessible
    // SKIPPED: attendancedetail_checkDetailWithPersonByCycle_cycleYear_cycleMonth not accessible
    // SKIPPED: attendancedetail_filter_list not accessible
    // SKIPPED: attendancedetail_filter_list_topUnit not accessible
    // SKIPPED: attendancedetail_filter_list_unit not accessible
    // SKIPPED: attendancedetail_filter_list_user not accessible
    // SKIPPED: attendancedetail_filter_list_id_next_count not accessible
    // SKIPPED: attendancedetail_filter_list_id_prev_count not accessible
    // SKIPPED: attendancedetail_list_persons_nonesign not accessible
    // SKIPPED: attendancedetail_list_file_id not accessible
    // SKIPPED: attendancedetail_mobile_filter_list_page_page_count_count not accessible
    // SKIPPED: attendancedetail_mobile_mobilepreview not accessible
    // SKIPPED: attendancedetail_mobile_my not accessible
    // SKIPPED: attendancedetail_mobile_recive not accessible
    // SKIPPED: attendancedetail_mobile_id not accessible
    // SKIPPED: attendancedetail_recive not accessible
    // SKIPPED: attendancedetail_reciveSingle not accessible
    // SKIPPED: attendancedetail_id not accessible
    // SKIPPED: attendanceemployeeconfig_list_all not accessible
    // SKIPPED: attendanceemployeeconfig_id not accessible
    // SKIPPED: attendanceimportfileinfo_list_all not accessible
    // SKIPPED: attendanceimportfileinfo_id not accessible
    // SKIPPED: attendanceschedulesetting_list_all not accessible
    // SKIPPED: attendanceschedulesetting_list_topUnit_name not accessible
    // SKIPPED: attendanceschedulesetting_list_unit_name not accessible
    // SKIPPED: attendanceschedulesetting_id not accessible
    // SKIPPED: attendanceselfholiday_filter_list_id_next_count not accessible
    // SKIPPED: attendanceselfholiday_filter_list_id_prev_count not accessible
    // SKIPPED: attendanceselfholiday_list_all not accessible
    // SKIPPED: attendanceselfholiday_id not accessible
    // SKIPPED: attendancesetting_code_code not accessible
    // SKIPPED: attendancesetting_enable_type not accessible
    // SKIPPED: attendancesetting_list_all not accessible
    // SKIPPED: attendancesetting_id not accessible
    // SKIPPED: attendancestatisticalcycle_cycleDetail_year_month not accessible
    // SKIPPED: attendancestatisticalcycle_list_all not accessible
    // SKIPPED: attendancestatisticalcycle_id not accessible
    // SKIPPED: attendancestatisticrequirelog_list_all not accessible
    // SKIPPED: attendancestatisticrequirelog_id not accessible
    // SKIPPED: attendanceworkdayconfig_filter not accessible
    // SKIPPED: attendanceworkdayconfig_list_all not accessible
    // SKIPPED: attendanceworkdayconfig_id not accessible
    // SKIPPED: selfholidaysimple_docId_docId not accessible
    // SKIPPED: statistic_do not accessible
    // SKIPPED: statisticshow_filter_personMonth_list_id_next_count not accessible
    // SKIPPED: statisticshow_filter_personMonth_list_id_prev_count not accessible
    // SKIPPED: statisticshow_filter_topUnitDay_list_id_next_count not accessible
    // SKIPPED: statisticshow_filter_topUnitDay_list_id_prev_count not accessible
    // SKIPPED: statisticshow_filter_topUnitMonth_list_id_next_count not accessible
    // SKIPPED: statisticshow_filter_topUnitMonth_list_id_prev_count not accessible
    // SKIPPED: statisticshow_filter_unitDay_list_id_next_count not accessible
    // SKIPPED: statisticshow_filter_unitDay_list_id_prev_count not accessible
    // SKIPPED: statisticshow_filter_unitMonth_list_id_next_count not accessible
    // SKIPPED: statisticshow_filter_unitMonth_list_id_prev_count not accessible
    // SKIPPED: statisticshow_person_name_year_month not accessible
    // SKIPPED: statisticshow_persons_unit_subnested_name_year_month not accessible
    // SKIPPED: statisticshow_persons_unit_name_year_month not accessible
    // SKIPPED: statisticshow_topUnit_day_name_year_month not accessible
    // SKIPPED: statisticshow_topUnit_name_year_month not accessible
    // SKIPPED: statisticshow_unit_day_topUnit_name_date not accessible
    // SKIPPED: statisticshow_unit_day_name_date not accessible
    // SKIPPED: statisticshow_unit_day_name_year_month not accessible
    // SKIPPED: statisticshow_unit_subnested_name_year_month not accessible
    // SKIPPED: statisticshow_unit_sum_name_year_month not accessible
    // SKIPPED: statisticshow_unit_topUnit_name_year_month not accessible
    // SKIPPED: statisticshow_unit_name_year_month not accessible
    // SKIPPED: uuid_random not accessible
    // SKIPPED: workplace_list_all not accessible
    // SKIPPED: workplace_id not accessible
}