/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.personal;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.personal.Attachment2.class)
public class Attachment2_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Attachment2,String> description;
    public static volatile SingularAttribute<Attachment2,String> extension;
    public static volatile SingularAttribute<Attachment2,Integer> fileVersion;
    public static volatile SingularAttribute<Attachment2,String> folder;
    public static volatile SingularAttribute<Attachment2,String> id;
    public static volatile SingularAttribute<Attachment2,String> lastUpdatePerson;
    public static volatile SingularAttribute<Attachment2,Date> lastUpdateTime;
    public static volatile SingularAttribute<Attachment2,Long> length;
    public static volatile SingularAttribute<Attachment2,String> name;
    public static volatile SingularAttribute<Attachment2,String> originFile;
    public static volatile SingularAttribute<Attachment2,String> person;
    public static volatile SingularAttribute<Attachment2,String> status;
    public static volatile SingularAttribute<Attachment2,String> type;
}
