/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.personal;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.personal.Folder2.class)
public class Folder2_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Folder2,String> id;
    public static volatile SingularAttribute<Folder2,Date> lastUpdateTime;
    public static volatile SingularAttribute<Folder2,String> name;
    public static volatile SingularAttribute<Folder2,String> person;
    public static volatile SingularAttribute<Folder2,String> status;
    public static volatile SingularAttribute<Folder2,String> superior;
}
