/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.personal;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.personal.Recycle.class)
public class Recycle_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Recycle,String> extension;
    public static volatile SingularAttribute<Recycle,String> fileId;
    public static volatile SingularAttribute<Recycle,String> fileType;
    public static volatile SingularAttribute<Recycle,String> id;
    public static volatile SingularAttribute<Recycle,Long> length;
    public static volatile SingularAttribute<Recycle,String> name;
    public static volatile SingularAttribute<Recycle,String> person;
    public static volatile SingularAttribute<Recycle,Date> validTime;
}
