/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity.log;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.log.TokenThreshold.class)
public class TokenThreshold_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<TokenThreshold,String> id;
    public static volatile SingularAttribute<TokenThreshold,String> person;
    public static volatile SingularAttribute<TokenThreshold,Date> threshold;
}
