/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.FormVersion.class)
public class FormVersion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<FormVersion,String> data;
    public static volatile SingularAttribute<FormVersion,String> form;
    public static volatile SingularAttribute<FormVersion,String> id;
    public static volatile SingularAttribute<FormVersion,String> person;
}
