/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.Mapping.class)
public class Mapping_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Mapping,String> application;
    public static volatile SingularAttribute<Mapping,String> data;
    public static volatile SingularAttribute<Mapping,String> description;
    public static volatile SingularAttribute<Mapping,Boolean> enable;
    public static volatile SingularAttribute<Mapping,String> id;
    public static volatile SingularAttribute<Mapping,String> name;
    public static volatile SingularAttribute<Mapping,String> process;
    public static volatile SingularAttribute<Mapping,String> tableName;
}
