/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.ProcessVersion.class)
public class ProcessVersion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ProcessVersion,String> data;
    public static volatile SingularAttribute<ProcessVersion,String> id;
    public static volatile SingularAttribute<ProcessVersion,String> person;
    public static volatile SingularAttribute<ProcessVersion,String> process;
}
