/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.Publish.class)
public class Publish_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Publish,String> afterArriveScript;
    public static volatile SingularAttribute<Publish,String> afterArriveScriptText;
    public static volatile SingularAttribute<Publish,String> afterExecuteScript;
    public static volatile SingularAttribute<Publish,String> afterExecuteScriptText;
    public static volatile SingularAttribute<Publish,String> afterInquireScript;
    public static volatile SingularAttribute<Publish,String> afterInquireScriptText;
    public static volatile SingularAttribute<Publish,String> alias;
    public static volatile SingularAttribute<Publish,Boolean> allowReroute;
    public static volatile SingularAttribute<Publish,Boolean> allowRerouteTo;
    public static volatile SingularAttribute<Publish,String> authorDataPathList;
    public static volatile SingularAttribute<Publish,String> beforeArriveScript;
    public static volatile SingularAttribute<Publish,String> beforeArriveScriptText;
    public static volatile SingularAttribute<Publish,String> beforeExecuteScript;
    public static volatile SingularAttribute<Publish,String> beforeExecuteScriptText;
    public static volatile SingularAttribute<Publish,String> beforeInquireScript;
    public static volatile SingularAttribute<Publish,String> beforeInquireScriptText;
    public static volatile SingularAttribute<Publish,String> categoryId;
    public static volatile SingularAttribute<Publish,String> categoryIdDataPath;
    public static volatile SingularAttribute<Publish,String> categorySelectType;
    public static volatile SingularAttribute<Publish,String> cmsCreatorIdentity;
    public static volatile SingularAttribute<Publish,String> cmsCreatorScript;
    public static volatile SingularAttribute<Publish,String> cmsCreatorScriptText;
    public static volatile SingularAttribute<Publish,PublishCmsCreatorType> cmsCreatorType;
    public static volatile SingularAttribute<Publish,String> description;
    public static volatile SingularAttribute<Publish,String> displayLogScript;
    public static volatile SingularAttribute<Publish,String> displayLogScriptText;
    public static volatile SingularAttribute<Publish,String> edition;
    public static volatile SingularAttribute<Publish,String> extension;
    public static volatile SingularAttribute<Publish,String> form;
    public static volatile SingularAttribute<Publish,String> group;
    public static volatile SingularAttribute<Publish,String> id;
    public static volatile SingularAttribute<Publish,Boolean> inheritAttachment;
    public static volatile SingularAttribute<Publish,String> name;
    public static volatile SingularAttribute<Publish,String> notifyDataPathList;
    public static volatile SingularAttribute<Publish,String> opinionGroup;
    public static volatile SingularAttribute<Publish,String> pictureDataPathList;
    public static volatile SingularAttribute<Publish,String> position;
    public static volatile SingularAttribute<Publish,String> process;
    public static volatile SingularAttribute<Publish,PublishProperties> properties;
    public static volatile SingularAttribute<Publish,String> publishTarget;
    public static volatile ListAttribute<Publish,String> readDataPathList;
    public static volatile SingularAttribute<Publish,String> readDuty;
    public static volatile ListAttribute<Publish,String> readGroupList;
    public static volatile ListAttribute<Publish,String> readIdentityList;
    public static volatile SingularAttribute<Publish,String> readScript;
    public static volatile SingularAttribute<Publish,String> readScriptText;
    public static volatile ListAttribute<Publish,String> readUnitList;
    public static volatile SingularAttribute<Publish,String> readerDataPathList;
    public static volatile ListAttribute<Publish,String> reviewDataPathList;
    public static volatile SingularAttribute<Publish,String> reviewDuty;
    public static volatile ListAttribute<Publish,String> reviewGroupList;
    public static volatile ListAttribute<Publish,String> reviewIdentityList;
    public static volatile SingularAttribute<Publish,String> reviewScript;
    public static volatile SingularAttribute<Publish,String> reviewScriptText;
    public static volatile ListAttribute<Publish,String> reviewUnitList;
    public static volatile SingularAttribute<Publish,String> route;
    public static volatile SingularAttribute<Publish,String> targetAssignDataScript;
    public static volatile SingularAttribute<Publish,String> targetAssignDataScriptText;
    public static volatile SingularAttribute<Publish,String> titleDataPath;
    public static volatile SingularAttribute<Publish,String> unique;
    public static volatile SingularAttribute<Publish,Boolean> useProcessForm;
}
