/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.ScriptVersion.class)
public class ScriptVersion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ScriptVersion,String> data;
    public static volatile SingularAttribute<ScriptVersion,String> id;
    public static volatile SingularAttribute<ScriptVersion,String> script;
}
