/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.ImportModel.class)
public class ImportModel_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ImportModel,String> alias;
    public static volatile ListAttribute<ImportModel,String> availableGroupList;
    public static volatile ListAttribute<ImportModel,String> availableIdentityList;
    public static volatile ListAttribute<ImportModel,String> availableUnitList;
    public static volatile SingularAttribute<ImportModel,String> code;
    public static volatile SingularAttribute<ImportModel,Integer> count;
    public static volatile SingularAttribute<ImportModel,String> data;
    public static volatile SingularAttribute<ImportModel,String> description;
    public static volatile SingularAttribute<ImportModel,Boolean> display;
    public static volatile SingularAttribute<ImportModel,Boolean> enableValid;
    public static volatile SingularAttribute<ImportModel,String> id;
    public static volatile SingularAttribute<ImportModel,String> layout;
    public static volatile SingularAttribute<ImportModel,String> name;
    public static volatile SingularAttribute<ImportModel,Integer> orderNumber;
    public static volatile SingularAttribute<ImportModel,String> processStatus;
    public static volatile SingularAttribute<ImportModel,String> query;
    public static volatile SingularAttribute<ImportModel,String> type;
}
