/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.ImportRecordItem.class)
public class ImportRecordItem_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ImportRecordItem,String> data;
    public static volatile SingularAttribute<ImportRecordItem,String> distribution;
    public static volatile SingularAttribute<ImportRecordItem,String> docId;
    public static volatile SingularAttribute<ImportRecordItem,String> docTitle;
    public static volatile SingularAttribute<ImportRecordItem,String> docType;
    public static volatile SingularAttribute<ImportRecordItem,String> id;
    public static volatile SingularAttribute<ImportRecordItem,String> modelId;
    public static volatile SingularAttribute<ImportRecordItem,String> query;
    public static volatile SingularAttribute<ImportRecordItem,String> recordId;
    public static volatile SingularAttribute<ImportRecordItem,String> srcData;
    public static volatile SingularAttribute<ImportRecordItem,String> status;
}
