/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.ImportRecord.class)
public class ImportRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ImportRecord,Integer> count;
    public static volatile SingularAttribute<ImportRecord,String> creatorPerson;
    public static volatile SingularAttribute<ImportRecord,String> data;
    public static volatile SingularAttribute<ImportRecord,String> distribution;
    public static volatile SingularAttribute<ImportRecord,Integer> failCount;
    public static volatile SingularAttribute<ImportRecord,String> id;
    public static volatile SingularAttribute<ImportRecord,String> modelId;
    public static volatile SingularAttribute<ImportRecord,String> name;
    public static volatile SingularAttribute<ImportRecord,String> query;
    public static volatile SingularAttribute<ImportRecord,String> status;
}
