/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import com.x.base.core.entity.dataitem.ItemCategory;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.ItemAccess.class)
public class ItemAccess_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ItemAccess,String> appId;
    public static volatile SingularAttribute<ItemAccess,String> id;
    public static volatile SingularAttribute<ItemAccess,ItemCategory> itemCategory;
    public static volatile SingularAttribute<ItemAccess,String> itemCategoryId;
    public static volatile SingularAttribute<ItemAccess,String> path;
    public static volatile SingularAttribute<ItemAccess,ItemAccessProperties> properties;
}
