/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.calendar.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.calendar.core.entity.Calendar_EventComment.class)
public class Calendar_EventComment_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Calendar_EventComment,Date> checkTime;
    public static volatile SingularAttribute<Calendar_EventComment,String> id;
    public static volatile SingularAttribute<Calendar_EventComment,String> lobValue;
}
