/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.DataRecord.class)
public class DataRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DataRecord,String> application;
    public static volatile SingularAttribute<DataRecord,String> id;
    public static volatile SingularAttribute<DataRecord,String> job;
    public static volatile SingularAttribute<DataRecord,String> path;
    public static volatile SingularAttribute<DataRecord,String> process;
    public static volatile SingularAttribute<DataRecord,DataRecordProperties> properties;
    public static volatile SingularAttribute<DataRecord,Integer> updateNum;
}
