/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.DocSignScrawl.class)
public class DocSignScrawl_ extends StorageObject_  {
    public static volatile SingularAttribute<DocSignScrawl,String> activity;
    public static volatile SingularAttribute<DocSignScrawl,String> activityName;
    public static volatile SingularAttribute<DocSignScrawl,Date> commitTime;
    public static volatile SingularAttribute<DocSignScrawl,Boolean> deepPath;
    public static volatile SingularAttribute<DocSignScrawl,String> extension;
    public static volatile SingularAttribute<DocSignScrawl,String> height;
    public static volatile SingularAttribute<DocSignScrawl,String> id;
    public static volatile SingularAttribute<DocSignScrawl,String> job;
    public static volatile SingularAttribute<DocSignScrawl,Date> lastUpdateTime;
    public static volatile SingularAttribute<DocSignScrawl,Long> length;
    public static volatile SingularAttribute<DocSignScrawl,String> name;
    public static volatile SingularAttribute<DocSignScrawl,String> person;
    public static volatile SingularAttribute<DocSignScrawl,String> signId;
    public static volatile SingularAttribute<DocSignScrawl,String> storage;
    public static volatile SingularAttribute<DocSignScrawl,String> type;
    public static volatile SingularAttribute<DocSignScrawl,String> width;
}
