/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.DocSign.class)
public class DocSign_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DocSign,String> activity;
    public static volatile SingularAttribute<DocSign,String> activityName;
    public static volatile SingularAttribute<DocSign,String> application;
    public static volatile SingularAttribute<DocSign,Date> commitTime;
    public static volatile SingularAttribute<DocSign,String> id;
    public static volatile SingularAttribute<DocSign,String> job;
    public static volatile SingularAttribute<DocSign,String> person;
    public static volatile SingularAttribute<DocSign,String> process;
    public static volatile SingularAttribute<DocSign,DocSignProperties> properties;
    public static volatile SingularAttribute<DocSign,String> signScrawlId;
    public static volatile SingularAttribute<DocSign,Integer> status;
    public static volatile SingularAttribute<DocSign,String> taskId;
    public static volatile SingularAttribute<DocSign,String> title;
}
