/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.Draft.class)
public class Draft_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Draft,String> application;
    public static volatile SingularAttribute<Draft,String> applicationAlias;
    public static volatile SingularAttribute<Draft,String> applicationName;
    public static volatile SingularAttribute<Draft,String> id;
    public static volatile SingularAttribute<Draft,String> identity;
    public static volatile SingularAttribute<Draft,String> person;
    public static volatile SingularAttribute<Draft,String> process;
    public static volatile SingularAttribute<Draft,String> processAlias;
    public static volatile SingularAttribute<Draft,String> processName;
    public static volatile SingularAttribute<Draft,DraftProperties> properties;
    public static volatile SingularAttribute<Draft,String> title;
    public static volatile SingularAttribute<Draft,String> unit;
}
