/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.Handover.class)
public class Handover_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Handover,String> creator;
    public static volatile ListAttribute<Handover,String> handoverJobList;
    public static volatile SingularAttribute<Handover,String> id;
    public static volatile SingularAttribute<Handover,String> person;
    public static volatile SingularAttribute<Handover,HandoverProperties> properties;
    public static volatile SingularAttribute<Handover,String> scheme;
    public static volatile SingularAttribute<Handover,String> status;
    public static volatile SingularAttribute<Handover,String> targetIdentity;
    public static volatile SingularAttribute<Handover,String> targetPerson;
    public static volatile SingularAttribute<Handover,String> title;
    public static volatile SingularAttribute<Handover,String> type;
}
