/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.KeyLock.class)
public class KeyLock_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<KeyLock,String> id;
    public static volatile SingularAttribute<KeyLock,String> key;
    public static volatile SingularAttribute<KeyLock,String> person;
}
