/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import com.x.processplatform.core.entity.element.ActivityType;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.Record.class)
public class Record_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Record,String> application;
    public static volatile SingularAttribute<Record,Boolean> completed;
    public static volatile SingularAttribute<Record,Boolean> display;
    public static volatile SingularAttribute<Record,String> fromActivity;
    public static volatile SingularAttribute<Record,String> fromActivityAlias;
    public static volatile SingularAttribute<Record,String> fromActivityName;
    public static volatile SingularAttribute<Record,String> fromActivityToken;
    public static volatile SingularAttribute<Record,ActivityType> fromActivityType;
    public static volatile SingularAttribute<Record,String> id;
    public static volatile SingularAttribute<Record,String> identity;
    public static volatile SingularAttribute<Record,String> job;
    public static volatile SingularAttribute<Record,Long> order;
    public static volatile SingularAttribute<Record,String> person;
    public static volatile SingularAttribute<Record,String> process;
    public static volatile SingularAttribute<Record,RecordProperties> properties;
    public static volatile SingularAttribute<Record,Date> recordTime;
    public static volatile SingularAttribute<Record,String> type;
    public static volatile SingularAttribute<Record,String> unit;
    public static volatile SingularAttribute<Record,String> work;
    public static volatile SingularAttribute<Record,String> workCompleted;
}
