/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import com.x.processplatform.core.entity.element.ActivityType;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.Snap.class)
public class Snap_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Snap,String> activity;
    public static volatile SingularAttribute<Snap,String> activityAlias;
    public static volatile SingularAttribute<Snap,String> activityDescription;
    public static volatile SingularAttribute<Snap,String> activityName;
    public static volatile SingularAttribute<Snap,String> activityToken;
    public static volatile SingularAttribute<Snap,ActivityType> activityType;
    public static volatile SingularAttribute<Snap,String> application;
    public static volatile SingularAttribute<Snap,String> applicationAlias;
    public static volatile SingularAttribute<Snap,String> applicationName;
    public static volatile SingularAttribute<Snap,String> creatorIdentity;
    public static volatile SingularAttribute<Snap,String> creatorPerson;
    public static volatile SingularAttribute<Snap,String> creatorUnit;
    public static volatile SingularAttribute<Snap,String> id;
    public static volatile SingularAttribute<Snap,String> job;
    public static volatile SingularAttribute<Snap,String> person;
    public static volatile SingularAttribute<Snap,String> process;
    public static volatile SingularAttribute<Snap,String> processAlias;
    public static volatile SingularAttribute<Snap,String> processName;
    public static volatile SingularAttribute<Snap,SnapProperties> properties;
    public static volatile SingularAttribute<Snap,Date> startTime;
    public static volatile SingularAttribute<Snap,String> title;
    public static volatile SingularAttribute<Snap,String> type;
}
