/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.TaskProcessMode.class)
public class TaskProcessMode_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<TaskProcessMode,String> action;
    public static volatile SingularAttribute<TaskProcessMode,String> activity;
    public static volatile SingularAttribute<TaskProcessMode,String> activityAlias;
    public static volatile SingularAttribute<TaskProcessMode,String> activityName;
    public static volatile SingularAttribute<TaskProcessMode,Integer> hitCount;
    public static volatile SingularAttribute<TaskProcessMode,String> id;
    public static volatile SingularAttribute<TaskProcessMode,String> person;
    public static volatile SingularAttribute<TaskProcessMode,String> process;
    public static volatile SingularAttribute<TaskProcessMode,String> processName;
    public static volatile SingularAttribute<TaskProcessMode,TaskProcessModeProperties> properties;
    public static volatile SingularAttribute<TaskProcessMode,String> routeId;
    public static volatile SingularAttribute<TaskProcessMode,String> routeName;
}
