[package]
publish.workspace = true
name = "processplatform_assemble_surface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
shared = { path = "../shared" }
axum = { workspace = true, features = ["multipart"] }
tokio.workspace = true
deadpool-postgres.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
bcrypt.workspace = true
base64.workspace = true
uuid.workspace = true
anyhow.workspace = true
chrono.workspace = true
md5.workspace = true
urlencoding.workspace = true
tower.workspace = true
zip = "2"
cfb = "0.15.0"
image = { version = "0.23.12", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dds", "farbfeld", "jpeg_rayon", "tiff"] }
genpdf = { version = "0.2.0", features = ["images"] }
