/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.mind.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.mind.entity.MindVersionContent.class)
public class MindVersionContent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MindVersionContent,String> content;
    public static volatile SingularAttribute<MindVersionContent,String> id;
}
