/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.mind.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.mind.entity.MindIconInfo.class)
public class MindIconInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MindIconInfo,String> content;
    public static volatile SingularAttribute<MindIconInfo,String> id;
}
