/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.Custom.class)
public class Custom_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Custom,String> data;
    public static volatile SingularAttribute<Custom,String> id;
    public static volatile SingularAttribute<Custom,String> name;
    public static volatile SingularAttribute<Custom,String> person;
}
