/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.OauthCode.class)
public class OauthCode_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OauthCode,String> accessToken;
    public static volatile SingularAttribute<OauthCode,String> clientId;
    public static volatile SingularAttribute<OauthCode,String> code;
    public static volatile SingularAttribute<OauthCode,Boolean> codeUsed;
    public static volatile SingularAttribute<OauthCode,String> id;
    public static volatile SingularAttribute<OauthCode,String> person;
    public static volatile SingularAttribute<OauthCode,String> scope;
}
