/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.PersonExtend.class)
public class PersonExtend_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<PersonExtend,String> id;
    public static volatile SingularAttribute<PersonExtend,String> person;
    public static volatile SingularAttribute<PersonExtend,PersonExtendProperties> properties;
    public static volatile SingularAttribute<PersonExtend,String> type;
}
