use axum::{
    extract::Extension,
    routing::{get, post},
    Router,
};
use deadpool_postgres::Pool;

use crate::{
    create_surface, get_surface, list_surfaces, preview_surface, publish_surface, save_surface, delete_surface, anonymous_read_count_credential, anonymous_task_count_credential, application_flag,
    application_flag_icon, application_flag_is_manager, application_flag_onlyRemoveNotCompleted, application_list_complex_manage_person, application_list_key_key, application_list_terminal_terminal, applicationdict_applicationDictFlag_application_applicationFlag, applicationdict_applicationDictFlag_application_applicationFlag_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_data_mockdeletetoget,
    applicationdict_applicationDictFlag_application_applicationFlag_path0_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data_mockputtopost,
    applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data_mockputtopost, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data,
    applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockdeletetoget, applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockputtopost, applicationdict_list_application_applicationFlag, control_workorworkcompleted_workOrWorkCompleted, correlation_job_job, correlation_job_job_delete, correlation_list_job_job, correlation_list_job_job_site_site, correlation_update_job_job, data_fetch_job_job,
    data_job_job, data_job_job_array_data, data_job_job_mockputtopost, data_job_job_path0, data_job_job_path0_mockputtopost, data_job_job_path0_path1, data_job_job_path0_path1_mockputtopost, data_job_job_path0_path1_path2, data_job_job_path0_path1_path2_mockputtopost, data_job_job_path0_path1_path2_path3,
    data_job_job_path0_path1_path2_path3_mockputtopost, data_job_job_path0_path1_path2_path3_path4, data_job_job_path0_path1_path2_path3_path4_mockputtopost, data_job_job_path0_path1_path2_path3_path4_path5, data_job_job_path0_path1_path2_path3_path4_path5_mockputtopost, data_job_job_path0_path1_path2_path3_path4_path5_path6, data_job_job_path0_path1_path2_path3_path4_path5_path6_mockputtopost, data_job_job_path0_path1_path2_path3_path4_path5_path6_path7, data_job_job_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost, data_work_id,
    data_work_id_mockdeletetoget, data_work_id_mockputtopost, data_work_id_path0, data_work_id_path0_mockdeletetoget, data_work_id_path0_mockputtopost, data_work_id_path0_path1, data_work_id_path0_path1_mockdeletetoget, data_work_id_path0_path1_mockputtopost, data_work_id_path0_path1_path2, data_work_id_path0_path1_path2_mockdeletetoget,
    data_work_id_path0_path1_path2_mockputtopost, data_work_id_path0_path1_path2_path3, data_work_id_path0_path1_path2_path3_mockdeletetoget, data_work_id_path0_path1_path2_path3_mockputtopost, data_work_id_path0_path1_path2_path3_path4, data_work_id_path0_path1_path2_path3_path4_mockdeletetoget, data_work_id_path0_path1_path2_path3_path4_mockputtopost, data_work_id_path0_path1_path2_path3_path4_path5, data_work_id_path0_path1_path2_path3_path4_path5_mockdeletetoget, data_work_id_path0_path1_path2_path3_path4_path5_mockputtopost,
    data_work_id_path0_path1_path2_path3_path4_path5_path6, data_work_id_path0_path1_path2_path3_path4_path5_path6_mockdeletetoget, data_work_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost, data_work_id_path0_path1_path2_path3_path4_path5_path6_path7, data_work_id_path0_path1_path2_path3_path4_path5_path6_path7_mockdeletetoget, data_work_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost, data_workcompleted_id, data_workcompleted_id_from_data, data_workcompleted_id_from_item, data_workcompleted_id_mockputtopost,
    data_workcompleted_id_path0, data_workcompleted_id_path0_mockputtopost, data_workcompleted_id_path0_path1, data_workcompleted_id_path0_path1_mockputtopost, data_workcompleted_id_path0_path1_path2, data_workcompleted_id_path0_path1_path2_mockputtopost, data_workcompleted_id_path0_path1_path2_path3, data_workcompleted_id_path0_path1_path2_path3_mockputtopost, data_workcompleted_id_path0_path1_path2_path3_path4, data_workcompleted_id_path0_path1_path2_path3_path4_mockputtopost,
    data_workcompleted_id_path0_path1_path2_path3_path4_path5, data_workcompleted_id_path0_path1_path2_path3_path4_path5_mockputtopost, data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6, data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost, data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_path7, data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost, datarecord_get_job_job_path_path, datarecord_list_job_job, documentversion_id, documentversion_list_job_job,
    documentversion_list_job_job_category_category, documentversion_list_workorworkcompleted_workOrWorkCompleted, documentversion_list_workorworkcompleted_workOrWorkCompleted_category_category, documentversion_work_work, draft_id, draft_id_mockdeletetoget, draft_id_start, draft_list_id_next_count, draft_list_id_prev_count, draft_list_my_paging_page_size_size,
    draft_mockputtopost, draft_process_processFlag, file_flag_application_applicationFlag_content, file_flag_application_applicationFlag_download, file_list_application_applicationFlag, form_flag, form_flag_application_applicationFlag, form_flag_application_applicationFlag_mobile, form_flag_mobile, form_v2_id,
    form_v2_id_mobile, form_v2_lookup_taskcompleted_taskcompleted, form_v2_lookup_taskcompleted_taskcompleted_mobile, form_v2_lookup_workorworkcompleted_workOrWorkCompleted, form_v2_lookup_workorworkcompleted_workOrWorkCompleted_mobile, handover_id, handover_id_cancel, handover_id_process, handover_list_paging_page_size_size, job_job_allow_visit_person_person,
    job_job_find_work_workcompleted, job_latest_work_workcompleted_serial_serial, job_v2_job_projection, keylock_lock, keylock_lock_mockputtopost, mode_clear_person_person_manager, mode_id_delete, mode_save, process_activity_activity_activityType_activityType, process_flag,
    process_flag_allowrerouteto, process_flag_application_applicationFlag, process_flag_complex, process_flag_onlyRemoveNotCompleted, process_list_application_applicationFlag, process_list_application_applicationFlag_filter, process_list_available_identity_process_flag, process_list_controllable_application_applicationFlag, read_count_credential, read_filter_attribute,
    read_filter_attribute_filter, read_id, read_id_manage, read_id_manage_mockdeletetoget, read_id_mockputtopost, read_id_opinion_manage, read_id_opinion_manage_mockputtopost, read_id_processing, read_id_processing_manage, read_id_processing_manage_mockputtopost,
    read_id_reference, read_id_reset_manage, read_id_reset_manage_mockputtopost, read_list_count_application_applicationFlag_process, read_list_date_date_manage, read_list_filter_page_size_size_manage, read_list_id_next_count, read_list_id_next_count_application_applicationFlag, read_list_id_next_count_filter, read_list_id_next_count_process_processFlag,
    read_list_id_prev_count, read_list_id_prev_count_application_applicationFlag, read_list_id_prev_count_filter, read_list_id_prev_count_process_processFlag, read_list_job_job, read_list_my_filter_page_size_size, read_list_my_paging_page_size_size, read_list_person_person_manage, read_list_work_work, read_list_workorworkcompleted_workOrWorkCompleted,
    read_v2_list_create_id_next_count, read_v2_list_create_id_prev_count, read_v2_list_create_paging_page_size_size, read_v2_list_id_next_count, read_v2_list_id_prev_count, read_v2_list_paging_page_size_size, read_work_workId, read_workcompleted_workCompletedId, readcompleted_count_credential, readcompleted_filter_attribute,
    readcompleted_filter_attribute_filter, readcompleted_id, readcompleted_id_manage, readcompleted_id_manage_mockdeletetoget, readcompleted_id_opinion_manage, readcompleted_id_reference, readcompleted_list_count_application_applicationFlag_process, readcompleted_list_date_date_manage, readcompleted_list_filter_page_size_size_manage, readcompleted_list_id_next_count,
    readcompleted_list_id_next_count_application_applicationFlag, readcompleted_list_id_next_count_filter, readcompleted_list_id_next_count_process_processFlag, readcompleted_list_id_prev_count, readcompleted_list_id_prev_count_application_applicationFlag, readcompleted_list_id_prev_count_filter, readcompleted_list_id_prev_count_process_processFlag, readcompleted_list_job_job, readcompleted_list_my_filter_page_size_size, readcompleted_list_my_paging_page_size_size,
    readcompleted_list_work_work, readcompleted_list_workorworkcompleted_workOrWorkCompleted, readcompleted_v2_list_create_id_next_count, readcompleted_v2_list_create_id_prev_count, readcompleted_v2_list_create_paging_page_size_size, readcompleted_v2_list_id_next_count, readcompleted_v2_list_id_prev_count, readcompleted_v2_list_paging_page_size_size, readrecord_list_job_job, readrecord_list_workorworkcompleted_workOrWorkCompleted,
    record_id_manage, record_id_manage_mockdeletetoget, record_id_manage_mockputtopost, record_job_job_manage, record_list_job_job, record_list_job_job_paging_page_size_size, record_list_workorworkcompleted_workOrWorkCompleted, record_list_workorworkcompleted_workOrWorkCompleted_paging_page_size_size, review_count_person_credential, review_create_work,
    review_create_workcompleted, review_filter_attribute, review_filter_create_entry, review_filter_entry, review_id, review_id_application_applicationFlag_manage, review_id_application_applicationFlag_manage_mockdeletetoget, review_list_job_job, review_v2_list_create_id_next_count, review_v2_list_create_id_prev_count,
    review_v2_list_create_paging_page_size_size, review_v2_list_id_next_count, review_v2_list_id_prev_count, review_v2_list_paging_page_size_size, review_v2_list_paging_page_size_size_manage, review_v2_search, review_workorworkcompleted_workOrWorkCompleted, route_id, route_id_selectconfig, route_list_mockputtopost,
    script_flag_application_applicationFlag, script_flag_application_applicationFlag_imported, serialnumber_generate_process_processId_name_name_serial, serialnumber_id, serialnumber_id_mockdeletetoget, serialnumber_id_mockputtopost, serialnumber_list_application_applicationFlag, serialnumber_list_paging_page_size_size, service_work_id_touch, service_work_id_touch_mockputtopost,
    sign_download_scrawlId, sign_id, sign_id_mockdeletetoget, sign_list_job_job, sign_save_task_taskId, sign_task_taskId, sign_task_taskId_mockdeletetoget, task_count_credential, task_filter_attribute, task_filter_attribute_filter,
    task_id, task_id_manage, task_id_manage_mockdeletetoget, task_id_mockputtopost, task_id_opinion_manage, task_id_opinion_manage_mockputtopost, task_id_press_manage, task_id_processing, task_id_processing_manage, task_id_processing_manage_mockputtopost,
    task_id_processing_neural, task_id_reference, task_id_reset_manage, task_id_reset_manage_mockputtopost, task_id_will, task_list_count_application_applicationFlag_process, task_list_date_date_hour_hour_exclude_draft_isExcludeDraft_manage, task_list_filter_page_size_size_manage, task_list_id_next_count, task_list_id_next_count_application_applicationFlag,
    task_list_id_next_count_filter, task_list_id_next_count_filter_manage, task_list_id_next_count_manage, task_list_id_next_count_process_processFlag, task_list_id_prev_count, task_list_id_prev_count_application_applicationFlag, task_list_id_prev_count_filter, task_list_id_prev_count_filter_manage, task_list_id_prev_count_manage, task_list_id_prev_count_process_processFlag,
    task_list_job_job, task_list_my_filter_page_size_size, task_list_my_paging_page_size_size, task_list_person_person_exclude_draft_isExcludeDraft_manage, task_list_work_work, task_v2_id_pause, task_v2_id_reset, task_v2_id_reset_mockputtopost, task_v2_id_resume, task_v2_id_trigger_processing,
    task_v2_list_create_id_next_count, task_v2_list_create_id_prev_count, task_v2_list_create_paging_page_size_size, task_v2_list_id_next_count, task_v2_list_id_prev_count, task_v2_list_paging_page_size_size, task_v3_id_add, task_v3_id_pin, taskcompleted_count_credential, taskcompleted_filter_attribute,
    taskcompleted_filter_attribute_filter, taskcompleted_id, taskcompleted_id_manage, taskcompleted_id_manage_mockdeletetoget, taskcompleted_id_opinion_manage, taskcompleted_id_opinion_manage_mockputtopost, taskcompleted_id_reference, taskcompleted_id_reference_control, taskcompleted_list_count_application_applicationFlag_process, taskcompleted_list_date_date_hour_hour_manage,
    taskcompleted_list_filter_page_size_size_manage, taskcompleted_list_id_next_count, taskcompleted_list_id_next_count_application_applicationFlag, taskcompleted_list_id_next_count_filter, taskcompleted_list_id_next_count_process_processFlag, taskcompleted_list_id_prev_count, taskcompleted_list_id_prev_count_application_applicationFlag, taskcompleted_list_id_prev_count_filter, taskcompleted_list_id_prev_count_process_processFlag, taskcompleted_list_job_job,
    taskcompleted_list_my_filter_page_size_size, taskcompleted_list_my_paging_page_size_size, taskcompleted_list_prev_manual_flag, taskcompleted_list_work_work, taskcompleted_list_workorworkcompleted_workOrWorkCompleted, taskcompleted_press_work_work, taskcompleted_v2_list_create_id_next_count, taskcompleted_v2_list_create_id_prev_count, taskcompleted_v2_list_create_paging_page_size_size, taskcompleted_v2_list_id_next_count,
    taskcompleted_v2_list_id_prev_count, taskcompleted_v2_list_paging_page_size_size, work_application_applicationFlag_process_processFlag, work_count_credential, work_count_credential_application_appId, work_filter_attribute_application_applicationFlag, work_filter_attribute_application_applicationFlag_manage, work_id, work_id_assignment_manage, work_id_close_check,
    work_id_manage, work_id_mockdeletetoget, work_id_processing, work_id_processing_mockputtopost, work_id_projection, work_id_refer, work_id_relative_manage, work_id_relative_manage_mockdeletetoget, work_id_single_manage, work_id_single_manage_mockdeletetoget,
    work_list_count_application_applicationFlag_process, work_list_count_application_applicationFlag_process_manage, work_list_filter_page_size_size_manage, work_list_id_next_count_application_applicationFlag, work_list_id_next_count_application_applicationFlag_filter, work_list_id_next_count_application_applicationFlag_filter_manage, work_list_id_next_count_application_applicationFlag_manage, work_list_id_next_count_creator_current, work_list_id_next_count_creator_current_filter, work_list_id_next_count_process_processFlag,
    work_list_id_prev_count_application_applicationFlag, work_list_id_prev_count_application_applicationFlag_filter, work_list_id_prev_count_application_applicationFlag_filter_manage, work_list_id_prev_count_application_applicationFlag_manage, work_list_id_prev_count_creator_current, work_list_id_prev_count_creator_current_filter, work_list_id_prev_count_process_processFlag, work_list_my_paging_page_size_size, work_list_paging_page_size_size_application_applicationFlag_filter_manage, work_process_processFlag,
    work_process_processFlag_force, work_v2_id_add_split, work_v2_id_add_split_mockputtopost, work_v2_id_reroute, work_v2_id_reroute_mockputtopost, work_v2_id_retract, work_v2_id_retract_mockputtopost, work_v2_id_rollback, work_v2_id_rollback_mockputtopost, work_v2_id_terminate,
    work_v2_id_terminate_manage, work_v2_id_trigger_processing, work_v2_list_id_activity_goback, work_v2_list_id_next_count, work_v2_list_id_prev_count, work_v2_list_paging_page_size_size, work_v2_workorworkcompleted_workOrWorkCompleted, work_v3_retract, work_v3_retract_stage_job_job, work_v3_workorworkcompleted_workOrWorkCompleted_permission,
    work_workorworkcompleted_workOrWorkCompleted, workcompleted_filter_attribute_application_applicationFlag, workcompleted_filter_attribute_application_applicationFlag_manage, workcompleted_filter_list_id_prev_count_application_applicationFlag, workcompleted_flag_rollback, workcompleted_flag_rollback_mockputtopost, workcompleted_id, workcompleted_id_assignment_manage, workcompleted_id_delete_manage, workcompleted_id_delete_manage_mockdeletetoget,
    workcompleted_id_manage, workcompleted_list_count_application_applicationFlag_process, workcompleted_list_count_application_applicationFlag_process_manage, workcompleted_list_filter_page_size_size_manage, workcompleted_list_id_next_count_application_applicationFlag, workcompleted_list_id_next_count_application_applicationFlag_filter, workcompleted_list_id_next_count_application_applicationFlag_filter_manage, workcompleted_list_id_next_count_application_applicationFlag_manage, workcompleted_list_id_prev_count_application_applicationFlag, workcompleted_list_id_prev_count_application_applicationFlag_filter,
    workcompleted_list_id_prev_count_application_applicationFlag_manage, workcompleted_list_paging_page_size_size_application_applicationFlag_filter_manage, workcompleted_process_processFlag, workcompleted_shift_time, worklog_list_add_split_work_workId, worklog_list_job_job, worklog_list_rollback_workorworkcompleted_workOrWorkCompleted, worklog_list_workorworkcompleted_workOrWorkCompleted,};


pub fn router(pool: Pool) -> Router {
    Router::new()
        .route("/jaxrs/processplatform/assemble/surface/get/{id}", get(get_surface))
        .route("/jaxrs/processplatform/assemble/surface/create", post(create_surface))
        .route("/jaxrs/processplatform/assemble/surface/list/{category}", get(list_surfaces))
        .route("/jaxrs/processplatform/assemble/surface/save/{id}", post(save_surface))
        .route("/jaxrs/processplatform/assemble/surface/preview/{id}", get(preview_surface))
        .route("/jaxrs/processplatform/assemble/surface/publish/{id}", post(publish_surface))
        .route("/jaxrs/processplatform/assemble/surface/delete/{id}", post(delete_surface))
                .route("/jaxrs/processplatform/assemble/surface/anonymous/read/{count}/{credential}", get(anonymous_read_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/anonymous/task/{count}/{credential}", get(anonymous_task_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/application/{flag}", get(application_flag))
        .route("/jaxrs/processplatform/assemble/surface/application/icon/{flag}", get(application_flag_icon))
        .route("/jaxrs/processplatform/assemble/surface/application/is/manager/{flag}", get(application_flag_is_manager))
        .route("/jaxrs/processplatform/assemble/surface/application/{flag}/{onlyRemoveNotCompleted}", get(application_flag_onlyRemoveNotCompleted))
        .route("/jaxrs/processplatform/assemble/surface/application/list/complex/manage/person", get(application_list_complex_manage_person))
        .route("/jaxrs/processplatform/assemble/surface/application/list/key/key", get(application_list_key_key))
        .route("/jaxrs/processplatform/assemble/surface/application/list/terminal/terminal", get(application_list_terminal_terminal))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/path7/data/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/path7/data/mockdeletetoget/{applicationDictFlag}/{applicationFlag}", post(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/application/path0/path1/path2/path3/path4/path5/path6/path7/data/mockputtopost/{applicationDictFlag}/{applicationFlag}", get(applicationdict_applicationDictFlag_application_applicationFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/applicationdict/list/application/{applicationFlag}", get(applicationdict_list_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/control/workorworkcompleted/{workOrWorkCompleted}", get(control_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/correlation/job/job", get(correlation_job_job))
        .route("/jaxrs/processplatform/assemble/surface/correlation/job/job/delete", post(correlation_job_job_delete))
        .route("/jaxrs/processplatform/assemble/surface/correlation/list/job/job", get(correlation_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/correlation/list/job/job/site/site", get(correlation_list_job_job_site_site))
        .route("/jaxrs/processplatform/assemble/surface/correlation/update/job/job", post(correlation_update_job_job))
        .route("/jaxrs/processplatform/assemble/surface/data/fetch/job/job", get(data_fetch_job_job))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job", get(data_job_job))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/array/data", get(data_job_job_array_data))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/mockputtopost", get(data_job_job_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0", get(data_job_job_path0))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/mockputtopost", get(data_job_job_path0_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1", get(data_job_job_path0_path1))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/mockputtopost", get(data_job_job_path0_path1_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2", get(data_job_job_path0_path1_path2))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/mockputtopost", get(data_job_job_path0_path1_path2_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3", get(data_job_job_path0_path1_path2_path3))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/mockputtopost", get(data_job_job_path0_path1_path2_path3_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4", get(data_job_job_path0_path1_path2_path3_path4))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/mockputtopost", get(data_job_job_path0_path1_path2_path3_path4_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5", get(data_job_job_path0_path1_path2_path3_path4_path5))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5/mockputtopost", get(data_job_job_path0_path1_path2_path3_path4_path5_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5/path6", get(data_job_job_path0_path1_path2_path3_path4_path5_path6))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5/path6/mockputtopost", get(data_job_job_path0_path1_path2_path3_path4_path5_path6_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5/path6/path7", get(data_job_job_path0_path1_path2_path3_path4_path5_path6_path7))
        .route("/jaxrs/processplatform/assemble/surface/data/job/job/path0/path1/path2/path3/path4/path5/path6/path7/mockputtopost", get(data_job_job_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/{id}", get(data_work_id))
        .route("/jaxrs/processplatform/assemble/surface/data/work/mockdeletetoget/{id}", post(data_work_id_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/mockputtopost/{id}", get(data_work_id_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/{id}", get(data_work_id_path0))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/mockdeletetoget/{id}", post(data_work_id_path0_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/mockputtopost/{id}", get(data_work_id_path0_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/{id}", get(data_work_id_path0_path1))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/mockdeletetoget/{id}", post(data_work_id_path0_path1_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/mockputtopost/{id}", get(data_work_id_path0_path1_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/{id}", get(data_work_id_path0_path1_path2))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/mockputtopost/{id}", get(data_work_id_path0_path1_path2_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/{id}", get(data_work_id_path0_path1_path2_path3))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_path3_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/mockputtopost/{id}", get(data_work_id_path0_path1_path2_path3_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/{id}", get(data_work_id_path0_path1_path2_path3_path4))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_path3_path4_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/mockputtopost/{id}", get(data_work_id_path0_path1_path2_path3_path4_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_path3_path4_path5_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/mockputtopost/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5_path6))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_path3_path4_path5_path6_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/mockputtopost/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/path7/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5_path6_path7))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/path7/mockdeletetoget/{id}", post(data_work_id_path0_path1_path2_path3_path4_path5_path6_path7_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/data/work/path0/path1/path2/path3/path4/path5/path6/path7/mockputtopost/{id}", get(data_work_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/{id}", get(data_workcompleted_id))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/from/data/{id}", get(data_workcompleted_id_from_data))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/from/item/{id}", get(data_workcompleted_id_from_item))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/mockputtopost/{id}", get(data_workcompleted_id_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/{id}", get(data_workcompleted_id_path0))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/mockputtopost/{id}", get(data_workcompleted_id_path0_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/{id}", get(data_workcompleted_id_path0_path1))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/{id}", get(data_workcompleted_id_path0_path1_path2))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/{id}", get(data_workcompleted_id_path0_path1_path2_path3))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_path3_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/path6/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/path6/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/path6/path7/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_path7))
        .route("/jaxrs/processplatform/assemble/surface/data/workcompleted/path0/path1/path2/path3/path4/path5/path6/path7/mockputtopost/{id}", get(data_workcompleted_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/datarecord/get/job/job/path/path", get(datarecord_get_job_job_path_path))
        .route("/jaxrs/processplatform/assemble/surface/datarecord/list/job/job", get(datarecord_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/{id}", get(documentversion_id))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/list/job/job", get(documentversion_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/list/job/job/{category}/{category}", get(documentversion_list_job_job_category_category))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/list/workorworkcompleted/{workOrWorkCompleted}", get(documentversion_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/list/workorworkcompleted/{workOrWorkCompleted}/{category}/{category}", get(documentversion_list_workorworkcompleted_workOrWorkCompleted_category_category))
        .route("/jaxrs/processplatform/assemble/surface/documentversion/work/work", get(documentversion_work_work))
        .route("/jaxrs/processplatform/assemble/surface/draft/{id}", get(draft_id))
        .route("/jaxrs/processplatform/assemble/surface/draft/mockdeletetoget/{id}", post(draft_id_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/draft/start/{id}", post(draft_id_start))
        .route("/jaxrs/processplatform/assemble/surface/draft/list/next/{id}/{count}", get(draft_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/draft/list/prev/{id}/{count}", get(draft_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/draft/list/my/paging/{page}/{size}/{size}", get(draft_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/draft/mockputtopost", get(draft_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/draft/process/{processFlag}", get(draft_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/file/application/content/{flag}/{applicationFlag}", get(file_flag_application_applicationFlag_content))
        .route("/jaxrs/processplatform/assemble/surface/file/application/download/{flag}/{applicationFlag}", get(file_flag_application_applicationFlag_download))
        .route("/jaxrs/processplatform/assemble/surface/file/list/application/{applicationFlag}", get(file_list_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/form/{flag}", get(form_flag))
        .route("/jaxrs/processplatform/assemble/surface/form/application/{flag}/{applicationFlag}", get(form_flag_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/form/application/mobile/{flag}/{applicationFlag}", get(form_flag_application_applicationFlag_mobile))
        .route("/jaxrs/processplatform/assemble/surface/form/mobile/{flag}", get(form_flag_mobile))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/{id}", get(form_v2_id))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/mobile/{id}", get(form_v2_id_mobile))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/lookup/taskcompleted/taskcompleted", get(form_v2_lookup_taskcompleted_taskcompleted))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/lookup/taskcompleted/taskcompleted/mobile", get(form_v2_lookup_taskcompleted_taskcompleted_mobile))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/lookup/workorworkcompleted/{workOrWorkCompleted}", get(form_v2_lookup_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/form/v2/lookup/workorworkcompleted/mobile/{workOrWorkCompleted}", get(form_v2_lookup_workorworkcompleted_workOrWorkCompleted_mobile))
        .route("/jaxrs/processplatform/assemble/surface/handover/{id}", get(handover_id))
        .route("/jaxrs/processplatform/assemble/surface/handover/cancel/{id}", get(handover_id_cancel))
        .route("/jaxrs/processplatform/assemble/surface/handover/process/{id}", get(handover_id_process))
        .route("/jaxrs/processplatform/assemble/surface/handover/list/paging/{page}/{size}/{size}", get(handover_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/job/job/allow/visit/person/person", get(job_job_allow_visit_person_person))
        .route("/jaxrs/processplatform/assemble/surface/job/job/find/work/workcompleted", get(job_job_find_work_workcompleted))
        .route("/jaxrs/processplatform/assemble/surface/job/latest/work/workcompleted/serial/serial", get(job_latest_work_workcompleted_serial_serial))
        .route("/jaxrs/processplatform/assemble/surface/job/v2/job/projection", get(job_v2_job_projection))
        .route("/jaxrs/processplatform/assemble/surface/keylock/lock", get(keylock_lock))
        .route("/jaxrs/processplatform/assemble/surface/keylock/lock/mockputtopost", get(keylock_lock_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/mode/clear/person/person/manager", get(mode_clear_person_person_manager))
        .route("/jaxrs/processplatform/assemble/surface/mode/delete/{id}", post(mode_id_delete))
        .route("/jaxrs/processplatform/assemble/surface/mode/save", post(mode_save))
        .route("/jaxrs/processplatform/assemble/surface/process/activity/activity/{activityType}/{activityType}", get(process_activity_activity_activityType_activityType))
        .route("/jaxrs/processplatform/assemble/surface/process/{flag}", get(process_flag))
        .route("/jaxrs/processplatform/assemble/surface/process/allowrerouteto/{flag}", get(process_flag_allowrerouteto))
        .route("/jaxrs/processplatform/assemble/surface/process/application/{flag}/{applicationFlag}", get(process_flag_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/process/complex/{flag}", get(process_flag_complex))
        .route("/jaxrs/processplatform/assemble/surface/process/{flag}/{onlyRemoveNotCompleted}", get(process_flag_onlyRemoveNotCompleted))
        .route("/jaxrs/processplatform/assemble/surface/process/list/application/{applicationFlag}", get(process_list_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/process/list/application/filter/{applicationFlag}", get(process_list_application_applicationFlag_filter))
        .route("/jaxrs/processplatform/assemble/surface/process/list/available/identity/process/{flag}", get(process_list_available_identity_process_flag))
        .route("/jaxrs/processplatform/assemble/surface/process/list/controllable/application/{applicationFlag}", get(process_list_controllable_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/read/{count}/{credential}", get(read_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/read/filter/attribute", get(read_filter_attribute))
        .route("/jaxrs/processplatform/assemble/surface/read/filter/attribute/filter", get(read_filter_attribute_filter))
        .route("/jaxrs/processplatform/assemble/surface/read/{id}", get(read_id))
        .route("/jaxrs/processplatform/assemble/surface/read/manage/{id}", get(read_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/manage/mockdeletetoget/{id}", post(read_id_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/read/mockputtopost/{id}", get(read_id_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/read/opinion/manage/{id}", post(read_id_opinion_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/opinion/manage/mockputtopost/{id}", post(read_id_opinion_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/read/processing/{id}", post(read_id_processing))
        .route("/jaxrs/processplatform/assemble/surface/read/processing/manage/{id}", post(read_id_processing_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/processing/manage/mockputtopost/{id}", post(read_id_processing_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/read/reference/{id}", post(read_id_reference))
        .route("/jaxrs/processplatform/assemble/surface/read/reset/manage/{id}", post(read_id_reset_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/reset/manage/mockputtopost/{id}", post(read_id_reset_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/read/list/application/process/{count}/{applicationFlag}", get(read_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/read/list/date/date/manage", get(read_list_date_date_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/list/filter/manage/{page}/{size}/{size}", get(read_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/list/next/{id}/{count}", get(read_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/read/list/next/application/{id}/{count}/{applicationFlag}", get(read_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/read/list/next/filter/{id}/{count}", get(read_list_id_next_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/read/list/next/process/{id}/{count}/{processFlag}", get(read_list_id_next_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/read/list/prev/{id}/{count}", get(read_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/read/list/prev/application/{id}/{count}/{applicationFlag}", get(read_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/read/list/prev/filter/{id}/{count}", get(read_list_id_prev_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/read/list/prev/process/{id}/{count}/{processFlag}", get(read_list_id_prev_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/read/list/job/job", get(read_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/read/list/my/filter/{page}/{size}/{size}", get(read_list_my_filter_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/read/list/my/paging/{page}/{size}/{size}", get(read_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/read/list/person/person/manage", get(read_list_person_person_manage))
        .route("/jaxrs/processplatform/assemble/surface/read/list/work/work", get(read_list_work_work))
        .route("/jaxrs/processplatform/assemble/surface/read/list/workorworkcompleted/{workOrWorkCompleted}", get(read_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/create/next/{id}/{count}", post(read_v2_list_create_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/create/prev/{id}/{count}", post(read_v2_list_create_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/create/paging/{page}/{size}/{size}", post(read_v2_list_create_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/next/{id}/{count}", get(read_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/prev/{id}/{count}", get(read_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/read/v2/list/paging/{page}/{size}/{size}", get(read_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/read/work/{workId}", get(read_work_workId))
        .route("/jaxrs/processplatform/assemble/surface/read/workcompleted/{workCompletedId}", get(read_workcompleted_workCompletedId))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/{count}/{credential}", get(readcompleted_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/filter/attribute", get(readcompleted_filter_attribute))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/filter/attribute/filter", get(readcompleted_filter_attribute_filter))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/{id}", get(readcompleted_id))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/manage/{id}", get(readcompleted_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/manage/mockdeletetoget/{id}", post(readcompleted_id_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/opinion/manage/{id}", post(readcompleted_id_opinion_manage))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/reference/{id}", post(readcompleted_id_reference))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/application/process/{count}/{applicationFlag}", get(readcompleted_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/date/date/manage", get(readcompleted_list_date_date_manage))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/filter/manage/{page}/{size}/{size}", get(readcompleted_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/next/{id}/{count}", get(readcompleted_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/next/application/{id}/{count}/{applicationFlag}", get(readcompleted_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/next/filter/{id}/{count}", get(readcompleted_list_id_next_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/next/process/{id}/{count}/{processFlag}", get(readcompleted_list_id_next_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/prev/{id}/{count}", get(readcompleted_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/prev/application/{id}/{count}/{applicationFlag}", get(readcompleted_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/prev/filter/{id}/{count}", get(readcompleted_list_id_prev_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/prev/process/{id}/{count}/{processFlag}", get(readcompleted_list_id_prev_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/job/job", get(readcompleted_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/my/filter/{page}/{size}/{size}", get(readcompleted_list_my_filter_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/my/paging/{page}/{size}/{size}", get(readcompleted_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/work/work", get(readcompleted_list_work_work))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/list/workorworkcompleted/{workOrWorkCompleted}", get(readcompleted_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/create/next/{id}/{count}", post(readcompleted_v2_list_create_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/create/prev/{id}/{count}", post(readcompleted_v2_list_create_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/create/paging/{page}/{size}/{size}", post(readcompleted_v2_list_create_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/next/{id}/{count}", get(readcompleted_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/prev/{id}/{count}", get(readcompleted_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/readcompleted/v2/list/paging/{page}/{size}/{size}", get(readcompleted_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/readrecord/list/job/job", get(readrecord_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/readrecord/list/workorworkcompleted/{workOrWorkCompleted}", get(readrecord_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/record/manage/{id}", get(record_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/record/manage/mockdeletetoget/{id}", post(record_id_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/record/manage/mockputtopost/{id}", get(record_id_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/record/job/job/manage", get(record_job_job_manage))
        .route("/jaxrs/processplatform/assemble/surface/record/list/job/job", get(record_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/record/list/job/job/paging/{page}/{size}/{size}", get(record_list_job_job_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/record/list/workorworkcompleted/{workOrWorkCompleted}", get(record_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/record/list/workorworkcompleted/paging/{workOrWorkCompleted}/{page}/{size}/{size}", get(record_list_workorworkcompleted_workOrWorkCompleted_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/review/person/{count}/{credential}", get(review_count_person_credential))
        .route("/jaxrs/processplatform/assemble/surface/review/create/work", post(review_create_work))
        .route("/jaxrs/processplatform/assemble/surface/review/create/workcompleted", post(review_create_workcompleted))
        .route("/jaxrs/processplatform/assemble/surface/review/filter/attribute", get(review_filter_attribute))
        .route("/jaxrs/processplatform/assemble/surface/review/filter/create/entry", post(review_filter_create_entry))
        .route("/jaxrs/processplatform/assemble/surface/review/filter/entry", get(review_filter_entry))
        .route("/jaxrs/processplatform/assemble/surface/review/{id}", get(review_id))
        .route("/jaxrs/processplatform/assemble/surface/review/application/manage/{id}/{applicationFlag}", get(review_id_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/review/application/manage/mockdeletetoget/{id}/{applicationFlag}", post(review_id_application_applicationFlag_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/review/list/job/job", get(review_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/create/next/{id}/{count}", post(review_v2_list_create_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/create/prev/{id}/{count}", post(review_v2_list_create_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/create/paging/{page}/{size}/{size}", post(review_v2_list_create_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/next/{id}/{count}", get(review_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/prev/{id}/{count}", get(review_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/paging/{page}/{size}/{size}", get(review_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/list/paging/manage/{page}/{size}/{size}", get(review_v2_list_paging_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/review/v2/search", get(review_v2_search))
        .route("/jaxrs/processplatform/assemble/surface/review/workorworkcompleted/{workOrWorkCompleted}", get(review_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/route/{id}", get(route_id))
        .route("/jaxrs/processplatform/assemble/surface/route/selectconfig/{id}", get(route_id_selectconfig))
        .route("/jaxrs/processplatform/assemble/surface/route/list/mockputtopost", get(route_list_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/script/application/{flag}/{applicationFlag}", get(script_flag_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/script/application/imported/{flag}/{applicationFlag}", get(script_flag_application_applicationFlag_imported))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/generate/process/name/name/serial/{processId}", get(serialnumber_generate_process_processId_name_name_serial))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/{id}", get(serialnumber_id))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/mockdeletetoget/{id}", post(serialnumber_id_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/mockputtopost/{id}", get(serialnumber_id_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/list/application/{applicationFlag}", get(serialnumber_list_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/serialnumber/list/paging/{page}/{size}/{size}", get(serialnumber_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/service/work/touch/{id}", post(service_work_id_touch))
        .route("/jaxrs/processplatform/assemble/surface/service/work/touch/mockputtopost/{id}", post(service_work_id_touch_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/sign/download/{scrawlId}", get(sign_download_scrawlId))
        .route("/jaxrs/processplatform/assemble/surface/sign/{id}", get(sign_id))
        .route("/jaxrs/processplatform/assemble/surface/sign/mockdeletetoget/{id}", post(sign_id_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/sign/list/job/job", get(sign_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/sign/save/task/{taskId}", post(sign_save_task_taskId))
        .route("/jaxrs/processplatform/assemble/surface/sign/task/{taskId}", get(sign_task_taskId))
        .route("/jaxrs/processplatform/assemble/surface/sign/task/mockdeletetoget/{taskId}", post(sign_task_taskId_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/task/{count}/{credential}", get(task_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/task/filter/attribute", get(task_filter_attribute))
        .route("/jaxrs/processplatform/assemble/surface/task/filter/attribute/filter", get(task_filter_attribute_filter))
        .route("/jaxrs/processplatform/assemble/surface/task/{id}", get(task_id))
        .route("/jaxrs/processplatform/assemble/surface/task/manage/{id}", get(task_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/manage/mockdeletetoget/{id}", post(task_id_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/task/mockputtopost/{id}", get(task_id_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/task/opinion/manage/{id}", post(task_id_opinion_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/opinion/manage/mockputtopost/{id}", post(task_id_opinion_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/task/press/manage/{id}", post(task_id_press_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/processing/{id}", post(task_id_processing))
        .route("/jaxrs/processplatform/assemble/surface/task/processing/manage/{id}", post(task_id_processing_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/processing/manage/mockputtopost/{id}", post(task_id_processing_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/task/processing/neural/{id}", post(task_id_processing_neural))
        .route("/jaxrs/processplatform/assemble/surface/task/reference/{id}", post(task_id_reference))
        .route("/jaxrs/processplatform/assemble/surface/task/reset/manage/{id}", post(task_id_reset_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/reset/manage/mockputtopost/{id}", post(task_id_reset_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/task/will/{id}", post(task_id_will))
        .route("/jaxrs/processplatform/assemble/surface/task/list/application/process/{count}/{applicationFlag}", get(task_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/task/list/date/date/hour/hour/exclude/draft/manage/{isExcludeDraft}", get(task_list_date_date_hour_hour_exclude_draft_isExcludeDraft_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/filter/manage/{page}/{size}/{size}", get(task_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/{id}/{count}", get(task_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/application/{id}/{count}/{applicationFlag}", get(task_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/filter/{id}/{count}", get(task_list_id_next_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/filter/manage/{id}/{count}", get(task_list_id_next_count_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/manage/{id}/{count}", get(task_list_id_next_count_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/next/process/{id}/{count}/{processFlag}", get(task_list_id_next_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/{id}/{count}", get(task_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/application/{id}/{count}/{applicationFlag}", get(task_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/filter/{id}/{count}", get(task_list_id_prev_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/filter/manage/{id}/{count}", get(task_list_id_prev_count_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/manage/{id}/{count}", get(task_list_id_prev_count_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/prev/process/{id}/{count}/{processFlag}", get(task_list_id_prev_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/task/list/job/job", get(task_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/task/list/my/filter/{page}/{size}/{size}", get(task_list_my_filter_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/task/list/my/paging/{page}/{size}/{size}", get(task_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/task/list/person/person/exclude/draft/manage/{isExcludeDraft}", get(task_list_person_person_exclude_draft_isExcludeDraft_manage))
        .route("/jaxrs/processplatform/assemble/surface/task/list/work/work", get(task_list_work_work))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/pause/{id}", get(task_v2_id_pause))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/reset/{id}", post(task_v2_id_reset))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/reset/mockputtopost/{id}", post(task_v2_id_reset_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/resume/{id}", post(task_v2_id_resume))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/trigger/processing/{id}", post(task_v2_id_trigger_processing))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/create/next/{id}/{count}", post(task_v2_list_create_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/create/prev/{id}/{count}", post(task_v2_list_create_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/create/paging/{page}/{size}/{size}", post(task_v2_list_create_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/next/{id}/{count}", get(task_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/prev/{id}/{count}", get(task_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/task/v2/list/paging/{page}/{size}/{size}", get(task_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/task/v3/add/{id}", post(task_v3_id_add))
        .route("/jaxrs/processplatform/assemble/surface/task/v3/pin/{id}", get(task_v3_id_pin))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/{count}/{credential}", get(taskcompleted_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/filter/attribute", get(taskcompleted_filter_attribute))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/filter/attribute/filter", get(taskcompleted_filter_attribute_filter))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/{id}", get(taskcompleted_id))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/manage/{id}", get(taskcompleted_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/manage/mockdeletetoget/{id}", post(taskcompleted_id_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/opinion/manage/{id}", post(taskcompleted_id_opinion_manage))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/opinion/manage/mockputtopost/{id}", post(taskcompleted_id_opinion_manage_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/reference/{id}", post(taskcompleted_id_reference))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/reference/control/{id}", post(taskcompleted_id_reference_control))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/application/process/{count}/{applicationFlag}", get(taskcompleted_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/date/date/hour/hour/manage", get(taskcompleted_list_date_date_hour_hour_manage))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/filter/manage/{page}/{size}/{size}", get(taskcompleted_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/next/{id}/{count}", get(taskcompleted_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/next/application/{id}/{count}/{applicationFlag}", get(taskcompleted_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/next/filter/{id}/{count}", get(taskcompleted_list_id_next_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/next/process/{id}/{count}/{processFlag}", get(taskcompleted_list_id_next_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/prev/{id}/{count}", get(taskcompleted_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/prev/application/{id}/{count}/{applicationFlag}", get(taskcompleted_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/prev/filter/{id}/{count}", get(taskcompleted_list_id_prev_count_filter))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/prev/process/{id}/{count}/{processFlag}", get(taskcompleted_list_id_prev_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/job/job", get(taskcompleted_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/my/filter/{page}/{size}/{size}", get(taskcompleted_list_my_filter_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/my/paging/{page}/{size}/{size}", get(taskcompleted_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/prev/manual/{flag}", get(taskcompleted_list_prev_manual_flag))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/work/work", get(taskcompleted_list_work_work))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/list/workorworkcompleted/{workOrWorkCompleted}", get(taskcompleted_list_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/press/work/work", post(taskcompleted_press_work_work))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/create/next/{id}/{count}", post(taskcompleted_v2_list_create_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/create/prev/{id}/{count}", post(taskcompleted_v2_list_create_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/create/paging/{page}/{size}/{size}", post(taskcompleted_v2_list_create_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/next/{id}/{count}", get(taskcompleted_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/prev/{id}/{count}", get(taskcompleted_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/taskcompleted/v2/list/paging/{page}/{size}/{size}", get(taskcompleted_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/work/application/process/{applicationFlag}/{processFlag}", get(work_application_applicationFlag_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/{count}/{credential}", get(work_count_credential))
        .route("/jaxrs/processplatform/assemble/surface/work/application/{count}/{credential}/{appId}", get(work_count_credential_application_appId))
        .route("/jaxrs/processplatform/assemble/surface/work/filter/attribute/application/{applicationFlag}", get(work_filter_attribute_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/filter/attribute/application/manage/{applicationFlag}", get(work_filter_attribute_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/{id}", get(work_id))
        .route("/jaxrs/processplatform/assemble/surface/work/assignment/manage/{id}", get(work_id_assignment_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/close/check/{id}", get(work_id_close_check))
        .route("/jaxrs/processplatform/assemble/surface/work/manage/{id}", get(work_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/mockdeletetoget/{id}", post(work_id_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/work/processing/{id}", post(work_id_processing))
        .route("/jaxrs/processplatform/assemble/surface/work/processing/mockputtopost/{id}", post(work_id_processing_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/work/projection/{id}", get(work_id_projection))
        .route("/jaxrs/processplatform/assemble/surface/work/refer/{id}", get(work_id_refer))
        .route("/jaxrs/processplatform/assemble/surface/work/relative/manage/{id}", get(work_id_relative_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/relative/manage/mockdeletetoget/{id}", post(work_id_relative_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/work/single/manage/{id}", get(work_id_single_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/single/manage/mockdeletetoget/{id}", post(work_id_single_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/work/list/application/process/{count}/{applicationFlag}", get(work_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/work/list/application/process/manage/{count}/{applicationFlag}", get(work_list_count_application_applicationFlag_process_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/filter/manage/{page}/{size}/{size}", get(work_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/application/{id}/{count}/{applicationFlag}", get(work_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/application/filter/{id}/{count}/{applicationFlag}", get(work_list_id_next_count_application_applicationFlag_filter))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/application/filter/manage/{id}/{count}/{applicationFlag}", get(work_list_id_next_count_application_applicationFlag_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/application/manage/{id}/{count}/{applicationFlag}", get(work_list_id_next_count_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/creator/current/{id}/{count}", get(work_list_id_next_count_creator_current))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/creator/current/filter/{id}/{count}", get(work_list_id_next_count_creator_current_filter))
        .route("/jaxrs/processplatform/assemble/surface/work/list/next/process/{id}/{count}/{processFlag}", get(work_list_id_next_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/application/{id}/{count}/{applicationFlag}", get(work_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/application/filter/{id}/{count}/{applicationFlag}", get(work_list_id_prev_count_application_applicationFlag_filter))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/application/filter/manage/{id}/{count}/{applicationFlag}", get(work_list_id_prev_count_application_applicationFlag_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/application/manage/{id}/{count}/{applicationFlag}", get(work_list_id_prev_count_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/creator/current/{id}/{count}", get(work_list_id_prev_count_creator_current))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/creator/current/filter/{id}/{count}", get(work_list_id_prev_count_creator_current_filter))
        .route("/jaxrs/processplatform/assemble/surface/work/list/prev/process/{id}/{count}/{processFlag}", get(work_list_id_prev_count_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/list/my/paging/{page}/{size}/{size}", get(work_list_my_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/work/list/paging/application/filter/manage/{page}/{size}/{size}/{applicationFlag}", get(work_list_paging_page_size_size_application_applicationFlag_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/process/{processFlag}", get(work_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/work/process/force/{processFlag}", get(work_process_processFlag_force))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/add/split/{id}", post(work_v2_id_add_split))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/add/split/mockputtopost/{id}", post(work_v2_id_add_split_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/reroute/{id}", get(work_v2_id_reroute))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/reroute/mockputtopost/{id}", get(work_v2_id_reroute_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/retract/{id}", get(work_v2_id_retract))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/retract/mockputtopost/{id}", get(work_v2_id_retract_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/rollback/{id}", get(work_v2_id_rollback))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/rollback/mockputtopost/{id}", get(work_v2_id_rollback_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/terminate/{id}", get(work_v2_id_terminate))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/terminate/manage/{id}", get(work_v2_id_terminate_manage))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/trigger/processing/{id}", post(work_v2_id_trigger_processing))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/list/activity/goback/{id}", get(work_v2_list_id_activity_goback))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/list/next/{id}/{count}", get(work_v2_list_id_next_count))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/list/prev/{id}/{count}", get(work_v2_list_id_prev_count))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/list/paging/{page}/{size}/{size}", get(work_v2_list_paging_page_size_size))
        .route("/jaxrs/processplatform/assemble/surface/work/v2/workorworkcompleted/{workOrWorkCompleted}", get(work_v2_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/work/v3/retract", get(work_v3_retract))
        .route("/jaxrs/processplatform/assemble/surface/work/v3/retract/stage/job/job", get(work_v3_retract_stage_job_job))
        .route("/jaxrs/processplatform/assemble/surface/work/v3/workorworkcompleted/permission/{workOrWorkCompleted}", get(work_v3_workorworkcompleted_workOrWorkCompleted_permission))
        .route("/jaxrs/processplatform/assemble/surface/work/workorworkcompleted/{workOrWorkCompleted}", get(work_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/filter/attribute/application/{applicationFlag}", get(workcompleted_filter_attribute_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/filter/attribute/application/manage/{applicationFlag}", get(workcompleted_filter_attribute_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/filter/list/prev/application/{id}/{count}/{applicationFlag}", get(workcompleted_filter_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/rollback/{flag}", get(workcompleted_flag_rollback))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/rollback/mockputtopost/{flag}", get(workcompleted_flag_rollback_mockputtopost))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/{id}", get(workcompleted_id))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/assignment/manage/{id}", get(workcompleted_id_assignment_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/delete/manage/{id}", post(workcompleted_id_delete_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/delete/manage/mockdeletetoget/{id}", post(workcompleted_id_delete_manage_mockdeletetoget))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/manage/{id}", get(workcompleted_id_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/application/process/{count}/{applicationFlag}", get(workcompleted_list_count_application_applicationFlag_process))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/application/process/manage/{count}/{applicationFlag}", get(workcompleted_list_count_application_applicationFlag_process_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/filter/manage/{page}/{size}/{size}", get(workcompleted_list_filter_page_size_size_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/next/application/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_next_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/next/application/filter/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_next_count_application_applicationFlag_filter))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/next/application/filter/manage/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_next_count_application_applicationFlag_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/next/application/manage/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_next_count_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/prev/application/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_prev_count_application_applicationFlag))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/prev/application/filter/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_prev_count_application_applicationFlag_filter))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/prev/application/manage/{id}/{count}/{applicationFlag}", get(workcompleted_list_id_prev_count_application_applicationFlag_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/list/paging/application/filter/manage/{page}/{size}/{size}/{applicationFlag}", get(workcompleted_list_paging_page_size_size_application_applicationFlag_filter_manage))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/process/{processFlag}", get(workcompleted_process_processFlag))
        .route("/jaxrs/processplatform/assemble/surface/workcompleted/shift/time", get(workcompleted_shift_time))
        .route("/jaxrs/processplatform/assemble/surface/worklog/list/add/split/work/{workId}", post(worklog_list_add_split_work_workId))
        .route("/jaxrs/processplatform/assemble/surface/worklog/list/job/job", get(worklog_list_job_job))
        .route("/jaxrs/processplatform/assemble/surface/worklog/list/rollback/workorworkcompleted/{workOrWorkCompleted}", get(worklog_list_rollback_workorworkcompleted_workOrWorkCompleted))
        .route("/jaxrs/processplatform/assemble/surface/worklog/list/workorworkcompleted/{workOrWorkCompleted}", get(worklog_list_workorworkcompleted_workOrWorkCompleted))
.layer(Extension(pool))
}
