-- 00009: redeem_codes.id 改为 IDENTITY（真缺陷修复）
--
-- 缺陷：redeem_codes.id 是无默认值的裸 INTEGER PRIMARY KEY（00006），
-- 而 AdminCreateRedeemCode 的 INSERT 不提供 id ——
-- 管理端每创建一条兑换码必然 not-null violation → 500。
-- 同库其它表都是 BIGSERIAL/IDENTITY，只有这张表漏了。
--
-- 取 GENERATED BY DEFAULT AS IDENTITY 而非 BIGSERIAL：
--   - seeder 仍可显式插入固定 id（1/2/3，BY DEFAULT 不拒绝显式值）
--   - setval 对齐到现有最大 id，避免自动生成的 id 撞上种子数据
--
-- +goose Up
ALTER TABLE redeem_codes
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 序列从现有最大 id 之后继续（迁移时表可能已被 seeder 填过）。
-- is_called=false：下一次 nextval 直接返回 setval 的值本身。
SELECT setval(
    pg_get_serial_sequence('redeem_codes', 'id'),
    (SELECT COALESCE(MAX(id), 0) + 1 FROM redeem_codes),
    false
);

-- +goose Down
ALTER TABLE redeem_codes
    ALTER COLUMN id DROP IDENTITY;
