//! Parity regression harness — Phase 4 U4.1.
//!
//! This crate provides:
//! 1. `parity_test!` macro — generates a one-shot axum router contract test
//!    that asserts the given route is registered (not 404).
//! 2. An auto-generated test runner (re-generated by
//!    `scripts/generate_parity_tests.py`) included at build time.
//!
//! ## How it works
//!
//! The Python script `scripts/generate_parity_tests.py` reads
//! `docs/audits/o2server-parity-report.json`, scans each Rust crate for
//! `.route("...", get(...))` registrations, and writes
//! `crates/parity/src/generated_tests.rs`.  That file is
//! `include!`-ed into the `generated_tests` module below, so it is compiled
//! as part of the `parity` crate's test suite.
//!
//! The generated tests build per-crate sub-routers via
//! `oa4rust::<crate>::router(shared::testing::test_pool())` and dispatch
//! one-shot requests, asserting each route responds with a non-404 status.

// ──────────────────────────────────────────────────────────────────────────────
// parity_test! macro
// ──────────────────────────────────────────────────────────────────────────────

/// Generate a single parity contract test for one axum route.
///
/// Expands to a `#[tokio::test] fn parity_contract_test()` that:
/// 1. Builds the crate router via `oa4rust::<crate>::<router_fn>(test_pool())`.
/// 2. Dispatches a one-shot GET/POST/… request to the route path.
/// 3. Asserts the response is NOT 404 — i.e. the route IS registered.
///
/// Each `parity_test!` invocation produces one test function.  When calling
/// manually, place each invocation in its own scope (or rely on the Python
/// script which generates per-route tests with unique names directly).
///
/// Parameters:
///   `crate`      — Rust identifier for the target crate.
///   `router_fn`  — Name of the router builder fn, e.g. `router` or `meeting_router`.
///   `route`      — Full axum route path string literal.
///   `method`     — HTTP method: `GET`, `POST`, `PUT`, `DELETE`, `PATCH`.
///   `handler`    — Handler fn name (informational, used in panic messages).
///   `test_name`  — Unique test fn name identifier (e.g. `parity_behavior__auth__login`).
///   `behavior`   — Optional behavior contract: "login_returns_token",
///                   "list_returns_array", or "route_exists" (default).
///
/// The macro has two forms: with `behavior` (behavior contract validation)
/// and without (backward-compatible, equivalent to `behavior: "route_exists"`).
///
/// Router invocation: `router_args` defaults to `(shared::testing::test_pool())`
/// but can be overridden for crates whose router fn takes extra arguments
/// (e.g. auth: `(shared::testing::test_pool(), RateLimiter::new(), SessionManager::new())`).
///
/// Request body: `body` defaults to `axum::body::Body::empty()`.  For POST/PUT
/// routes that require a JSON payload, pass a string expression, e.g.
/// `body: serde_json::json!({"username":"test"}).to_string()`.
#[macro_export]
macro_rules! parity_test {
    // ── Form 1: with behavior contract + custom body ──────────────────────
    //
    // `content_type` is optional; set it (e.g. "application/json") for routes
    // whose handler extracts an `axum::extract::Json` body — without the
    // header the extractor rejects the request before the handler runs.
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
        behavior: $behavior:expr,
        $(content_type: $content_type:expr,)?
        router_args: $router_args:tt,
        body: $body:expr,
    ) => {
        #[tokio::test]
        async fn $test_name() {
            let router =
                oa4rust::$crate_name::$router_fn $router_args;
            let response = router
                .oneshot(
                    axum::http::Request::builder()
                        .uri($route)
                        .method(axum::http::Method::$method)
                        $(.header(axum::http::header::CONTENT_TYPE, $content_type))?
                        .body(axum::body::Body::from($body))
                        .expect("build parity request"),
                )
                .await
                .expect("oneshot dispatch");

            // Check route exists
            if response.status() == axum::http::StatusCode::NOT_FOUND {
                panic!("parity: route missing on {}::{} → {} ({}) handler={}",
                    stringify!($crate_name), stringify!($router_fn), $route,
                    stringify!($method), stringify!($handler));
            }

            // Behavior contract validation
            match $behavior {
                "login_returns_token" => {
                    assert!(response.status().is_success() || response.status().is_client_error(),
                        "login handler should return 2xx or 4xx, got {}",
                        response.status());
                    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
                        .await
                        .expect("read response body");
                    let json: serde_json::Value =
                        serde_json::from_slice(&body).expect("parse JSON");
                    assert!(
                        json.get("data").is_some(),
                        "login response should have data field, got: {}",
                        json
                    );
                }
                "list_returns_array" => {
                    assert_eq!(response.status(), axum::http::StatusCode::OK,
                        "list handler should return 200, got {}",
                        response.status());
                    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
                        .await
                        .expect("read response body");
                    let json: serde_json::Value =
                        serde_json::from_slice(&body).expect("parse JSON");
                    assert!(
                        json.get("data").is_some(),
                        "list response should have data field, got: {}",
                        json
                    );
                    let data = &json["data"];
                    if data.is_object() {
                        if let Some(nested) = data.get("data") {
                            assert!(nested.is_array() || nested.is_object(),
                                "list nested data should be array or object, got: {}", nested);
                        }
                    } else {
                        assert!(data.is_array() || data.is_object(),
                            "list data should be array or object, got: {}", data);
                    }
                }
                "route_exists" => {}
                _ => {}
            }
        }
    };

    // ── Form 1b: with behavior + default body ─────────────────────────────
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
        behavior: $behavior:expr,
        router_args: $router_args:tt,
    ) => {
        parity_test!(
            crate: $crate_name,
            router_fn: $router_fn,
            route: $route,
            method: $method,
            handler: $handler,
            test_name: $test_name,
            behavior: $behavior,
            router_args: $router_args,
            body: String::new(),
        );
    };

    // ── Form 1c: with behavior + default router_args + default body ───────
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
        behavior: $behavior:expr,
    ) => {
        parity_test!(
            crate: $crate_name,
            router_fn: $router_fn,
            route: $route,
            method: $method,
            handler: $handler,
            test_name: $test_name,
            behavior: $behavior,
            router_args: (shared::testing::test_pool()),
            body: String::new(),
        );
    };

    // ── Form 2: backward-compatible without behavior + custom body ─────────
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
        router_args: $router_args:tt,
        body: $body:expr,
    ) => {
        #[tokio::test]
        async fn $test_name() {
            let router =
                oa4rust::$crate_name::$router_fn $router_args;
            let response = router
                .oneshot(
                    axum::http::Request::builder()
                        .uri($route)
                        .method(axum::http::Method::$method)
                        .body(axum::body::Body::from($body))
                        .expect("build parity request"),
                )
                .await
                .expect("oneshot dispatch");
            assert_ne!(
                response.status(),
                axum::http::StatusCode::NOT_FOUND,
                "parity: route missing on {}::{} → {} ({}) handler={}",
                stringify!($crate_name),
                stringify!($router_fn),
                $route,
                stringify!($method),
                stringify!($handler),
            );
        }
    };

    // ── Form 2b: backward-compatible without behavior + default body ───────
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
        router_args: $router_args:tt,
    ) => {
        parity_test!(
            crate: $crate_name,
            router_fn: $router_fn,
            route: $route,
            method: $method,
            handler: $handler,
            test_name: $test_name,
            router_args: $router_args,
            body: String::new(),
        );
    };

    // ── Form 2c: backward-compatible without behavior + default router_args + default body ──
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
        test_name: $test_name:ident,
    ) => {
        parity_test!(
            crate: $crate_name,
            router_fn: $router_fn,
            route: $route,
            method: $method,
            handler: $handler,
            test_name: $test_name,
            router_args: (shared::testing::test_pool()),
            body: String::new(),
        );
    };
}

// ──────────────────────────────────────────────────────────────────────────────
// Auto-generated test runner
// ──────────────────────────────────────────────────────────────────────────────
//
// scripts/generate_parity_tests.py writes crates/parity/src/generated_tests.rs.
// We `include!` it so it compiles as tests in this crate.

#[cfg(test)]
mod generated_tests {
    //! AUTO-GENERATED — DO NOT EDIT. Run `python scripts/generate_parity_tests.py`.
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_tests.rs"));
}

#[cfg(test)]
mod behavior_tests {
    //! Hand-written behavior contract tests for Top 100 high-frequency routes.
    //!
    //! These use the `behavior:` form of `parity_test!` to validate response
    //! body structure (not just 404 absence).  Do NOT auto-generate — edits
    //! here are intentional and must be reviewed.
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/behavior_tests.rs"));
}

// ──────────────────────────────────────────────────────────────────────────────
// Parity report types (used by tests/parity_runner.rs)
// ──────────────────────────────────────────────────────────────────────────────

/// Result of a single parity check.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParityStatus {
    /// Route is registered and dispatches without 404.
    Pass,
    /// Route is NOT registered — returns 404.
    MissingRoute,
    /// Request could not be dispatched (router error).
    DispatchError,
}

impl ParityStatus {
    pub fn is_pass(&self) -> bool {
        matches!(self, ParityStatus::Pass)
    }
    pub fn is_fail(&self) -> bool {
        !self.is_pass()
    }
}

/// Summary of parity checks across one or more crates.
#[derive(Debug, Default)]
pub struct ParityReport {
    pub total: usize,
    pub pass: usize,
    pub missing: usize,
    pub errors: usize,
    pub findings: Vec<(String, String, ParityStatus)>,
}

impl ParityReport {
    pub fn record(&mut self, crate_name: &str, route: &str, status: ParityStatus) {
        self.total += 1;
        match status {
            ParityStatus::Pass => self.pass += 1,
            ParityStatus::MissingRoute => self.missing += 1,
            ParityStatus::DispatchError => self.errors += 1,
        }
        self.findings
            .push((crate_name.to_string(), route.to_string(), status));
    }

    pub fn is_clean(&self) -> bool {
        self.missing == 0 && self.errors == 0
    }

    pub fn coverage_pct(&self) -> f64 {
        if self.total == 0 {
            100.0
        } else {
            (self.pass as f64 / self.total as f64) * 100.0
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Self-test: parity_test! macro expansion
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod macro_self_test {
    use crate::parity_test;
    use tower::util::ServiceExt;

    parity_test!(
        crate: base,
        router_fn: router,
        route: "/jaxrs/base/echo/get",
        method: GET,
        handler: base_echo_get_handler,
        test_name: parity_self_test_base_echo_get,
        behavior: "route_exists",
        router_args: (shared::testing::test_pool()),
    );
}
