//! Parity regression harness — Phase 4 U4.1.
//!
//! This crate provides:
//! 1. `parity_test!` macro — generates a one-shot axum router contract test
//!    that asserts the given route is registered (not 404).
//! 2. An auto-generated test runner (re-generated by
//!    `scripts/generate_parity_tests.py`) included at build time.
//!
//! ## How it works
//!
//! The Python script `scripts/generate_parity_tests.py` reads
//! `docs/audits/o2server-parity-report.json`, scans each Rust crate for
//! `.route("...", get(...))` registrations, and writes
//! `crates/parity/src/generated_tests.rs`.  That file is
//! `include!`-ed into the `generated_tests` module below, so it is compiled
//! as part of the `parity` crate's test suite.
//!
//! The generated tests build per-crate sub-routers via
//! `oa4rust::<crate>::router(shared::testing::test_pool())` and dispatch
//! one-shot requests, asserting each route responds with a non-404 status.

// ──────────────────────────────────────────────────────────────────────────────
// parity_test! macro
// ──────────────────────────────────────────────────────────────────────────────

/// Generate a single parity contract test for one axum route.
///
/// Expands to a `#[tokio::test] fn parity_contract_test()` that:
/// 1. Builds the crate router via `oa4rust::<crate>::<router_fn>(test_pool())`.
/// 2. Dispatches a one-shot GET/POST/… request to the route path.
/// 3. Asserts the response is NOT 404 — i.e. the route IS registered.
///
/// Each `parity_test!` invocation produces one test function.  When calling
/// manually, place each invocation in its own scope (or rely on the Python
/// script which generates per-route tests with unique names directly).
///
/// Parameters:
///   `crate`      — Rust identifier for the target crate.
///   `router_fn`  — Name of the router builder fn, e.g. `router` or `meeting_router`.
///   `route`      — Full axum route path string literal.
///   `method`     — HTTP method: `GET`, `POST`, `PUT`, `DELETE`, `PATCH`.
///   `handler`    — Handler fn name (informational, used in panic messages).
#[macro_export]
macro_rules! parity_test {
    (
        crate: $crate_name:ident,
        router_fn: $router_fn:ident,
        route: $route:expr,
        method: $method:ident,
        handler: $handler:ident,
    ) => {
        #[tokio::test]
        async fn parity_contract_test() {
            let router =
                oa4rust::$crate_name::$router_fn(shared::testing::test_pool());
            let response = router
                .oneshot(
                    axum::http::Request::builder()
                        .uri($route)
                        .method(axum::http::Method::$method)
                        .body(axum::body::Body::empty())
                        .expect("build parity request"),
                )
                .await
                .expect("oneshot dispatch");
            assert_ne!(
                response.status(),
                axum::http::StatusCode::NOT_FOUND,
                "parity: route missing on {}::{} → {} ({}) handler={}",
                stringify!($crate_name),
                stringify!($router_fn),
                $route,
                stringify!($method),
                stringify!($handler),
            );
        }
    };
}

// ──────────────────────────────────────────────────────────────────────────────
// Auto-generated test runner
// ──────────────────────────────────────────────────────────────────────────────
//
// scripts/generate_parity_tests.py writes crates/parity/src/generated_tests.rs.
// We `include!` it so it compiles as tests in this crate.

#[cfg(test)]
mod generated_tests {
    //! AUTO-GENERATED — DO NOT EDIT. Run `python scripts/generate_parity_tests.py`.
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_tests.rs"));
}

// ──────────────────────────────────────────────────────────────────────────────
// Parity report types (used by tests/parity_runner.rs)
// ──────────────────────────────────────────────────────────────────────────────

/// Result of a single parity check.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParityStatus {
    /// Route is registered and dispatches without 404.
    Pass,
    /// Route is NOT registered — returns 404.
    MissingRoute,
    /// Request could not be dispatched (router error).
    DispatchError,
}

impl ParityStatus {
    pub fn is_pass(&self) -> bool {
        matches!(self, ParityStatus::Pass)
    }
    pub fn is_fail(&self) -> bool {
        !self.is_pass()
    }
}

/// Summary of parity checks across one or more crates.
#[derive(Debug, Default)]
pub struct ParityReport {
    pub total: usize,
    pub pass: usize,
    pub missing: usize,
    pub errors: usize,
    pub findings: Vec<(String, String, ParityStatus)>,
}

impl ParityReport {
    pub fn record(&mut self, crate_name: &str, route: &str, status: ParityStatus) {
        self.total += 1;
        match status {
            ParityStatus::Pass => self.pass += 1,
            ParityStatus::MissingRoute => self.missing += 1,
            ParityStatus::DispatchError => self.errors += 1,
        }
        self.findings
            .push((crate_name.to_string(), route.to_string(), status));
    }

    pub fn is_clean(&self) -> bool {
        self.missing == 0 && self.errors == 0
    }

    pub fn coverage_pct(&self) -> f64 {
        if self.total == 0 {
            100.0
        } else {
            (self.pass as f64 / self.total as f64) * 100.0
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Self-test: parity_test! macro expansion
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod macro_self_test {
    use crate::parity_test;
    use tower::util::ServiceExt;

    parity_test!(
        crate: base,
        router_fn: router,
        route: "/jaxrs/base/echo/get",
        method: GET,
        handler: base_echo_get_handler,
    );
}
