[package]
name = "organization_core_entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
tower.workspace = true
sea-orm.workspace = true
deadpool-postgres.workspace = true

shared = { path = "../shared" }
orm = { path = "../orm" }
chrono.workspace = true

[dev-dependencies]
tower.workspace = true
