use axum::{
    extract::Extension,
    routing::{get, post, put, delete},
    Router,
};
use deadpool_postgres::Pool;

use crate::{
    get_control_config, list_control_sections, update_control_config, document_id_view_count, commend_list_paging, queryview_flag_definition, application_id, document_search, anonymous_document_id_view, data_document_id_array_data,
    data_document_id_mockdeletetoget, data_document_id_mockputtopost, data_document_id_path0, data_document_id_path0_mockdeletetoget, data_document_id_path0_mockputtopost, data_document_id_path0_path1, data_document_id_path0_path1_mockdeletetoget, data_document_id_path0_path1_mockputtopost, data_document_id_path0_path1_path2, data_document_id_path0_path1_path2_mockdeletetoget,
    data_document_id_path0_path1_path2_mockputtopost, data_document_id_path0_path1_path2_path3, data_document_id_path0_path1_path2_path3_mockdeletetoget, data_document_id_path0_path1_path2_path3_mockputtopost, data_document_id_path0_path1_path2_path3_path4, data_document_id_path0_path1_path2_path3_path4_mockdeletetoget, data_document_id_path0_path1_path2_path3_path4_mockputtopost, data_document_id_path0_path1_path2_path3_path4_path5, data_document_id_path0_path1_path2_path3_path4_path5_mockdeletetoget, data_document_id_path0_path1_path2_path3_path4_path5_mockputtopost,
    data_document_id_path0_path1_path2_path3_path4_path5_path6, data_document_id_path0_path1_path2_path3_path4_path5_path6_mockdeletetoget, data_document_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost, data_document_id_path0_path1_path2_path3_path4_path5_path6_path7, data_document_id_path0_path1_path2_path3_path4_path5_path6_path7_mockdeletetoget, data_document_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost, fileinfo_id, fileinfo_id_document_documentId, fileinfo_id_mockdeletetoget, anonymous_fileinfo_download_document_id,
    fileinfo_download_document_id, fileinfo_upload_document_docId, anonymous_fileinfo_download_document_id_stream, anonymous_form_id, anonymous_form_v2_id, anonymous_form_v2_id_mobile, anonymous_form_v2_lookup_document_docId, anonymous_form_v2_lookup_document_docId_mobile, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_data,
    anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data, anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data, appinfo_alias_alias, appinfo_appId_icon_size_size,
    appinfo_erase_app_id, appinfo_erase_app_id_mockdeletetoget, appinfo_get_user_publish_appId, appinfo_id_control, appinfo_id_mockdeletetoget, appinfo_id_permission, categoryinfo_alias_alias, categoryinfo_bind_categoryId_view, categoryinfo_bind_categoryId_view_mockputtopost, categoryinfo_erase_category_id,
    categoryinfo_erase_category_id_mockdeletetoget, categoryinfo_extContent, categoryinfo_id_control, categoryinfo_id_execute_projection, categoryinfo_id_mockdeletetoget, categoryinfo_id_permission, comment_id_commend, comment_id_mockdeletetoget, comment_id_uncommend, correlation_doc_docId_delete,
    correlation_update_doc_docId, design_appdict_id_mockdeletetoget, design_appdict_id_mockputtopost, document_cipher_id_permission_read_person_person, document_cipher_id_persist_view_record, document_cipher_publish_content, document_cipher_publish_content_mockputtopost, file_flag_appInfo_appInfoFlag_content, file_flag_appInfo_appInfoFlag_download, file_flag_mockdeletetoget,
    file_id_content, file_id_download, file_id_mockputtopost, file_id_upload, fileinfo_batch_download_doc_docId_site_site, fileinfo_copy_to_doc_docId, fileinfo_download_document_id_stream, fileinfo_download_transfer_flag_flag, fileinfo_edit_id_doc_docId, fileinfo_edit_id_doc_docId_mockputtopost,
    fileinfo_id_binary_base64_size, fileinfo_id_doc_docId_change_seqnumber_seqNumber, fileinfo_id_online_info, fileinfo_id_preview_pdf, fileinfo_replace_to_doc_docId, fileinfo_update_document_docId_attachment_id, fileinfo_update_document_docId_attachment_id_callback_callback, fileinfo_update_id_content, fileinfo_upload_doc_docId_save_as_flag, fileinfo_upload_document_docId_callback_callback,
    fileinfo_upload_with_url, form_formFlag_appinfo_appFlag, form_id_mockdeletetoget, form_id_mockputtopost, form_v2_id_mobile, form_v2_lookup_document_docId, form_v2_lookup_document_docId_mobile, formversion_id, formversion_list_form_formId, output_appInfoFlag_select,
    output_appInfoFlag_select_mockputtopost, permission_management_refresh_category_categoryId, script_id_mockdeletetoget, script_id_mockputtopost, script_uniqueName_app_flag, script_uniqueName_app_flag_imported, scriptversion_id, scriptversion_list_script_scriptId, surface_appdict_appDictFlag_appInfo_appInfoFlag, surface_appdict_appDictFlag_appInfo_appInfoFlag_data,
    surface_appdict_appDictFlag_appInfo_appInfoFlag_mockputtopost, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data_mockputtopost, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data_mockdeletetoget,
    surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data_mockputtopost, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data_mockputtopost, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data_mockputtopost, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data_mockputtopost,
    surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockdeletetoget, surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockputtopost, templateform_id, templateform_id_mockdeletetoget, view_id_mockdeletetoget, view_id_mockputtopost, viewcategory_id_mockdeletetoget, viewfieldconfig_id_mockdeletetoget, viewfieldconfig_id_mockputtopost,
    viewrecord_document_docId_has_view, anonymous_document_filter_list_id_next_count, anonymous_document_filter_list_id_next_count_mockputtopost, anonymous_document_filter_list_page_size_size, anonymous_document_filter_list_page_size_size_mockputtopost, anonymous_fileinfo_list_document_documentId, appinfo_filter_list_id_next_count, appinfo_filter_list_id_next_count_mockputtopost, appinfo_filter_list_id_prev_count, appinfo_filter_list_id_prev_count_mockputtopost,
    appinfo_list_all, appinfo_list_appType, appinfo_list_appType_manager, appinfo_list_has_document, appinfo_list_has_document_appType, appinfo_list_has_document_type_appType, appinfo_list_manage, appinfo_list_manage_type_appType, appinfo_list_user_publish, appinfo_list_user_publish_type_appType,
    appinfo_list_user_publish_with_process, appinfo_list_user_view, appinfo_list_user_view_all, appinfo_list_user_view_all_type_appType, appinfo_list_user_view_article_type_appType, appinfo_list_user_view_data, appinfo_list_user_view_data_type_appType, appinfo_flag, appinfo_id, categoryinfo_filter_list_id_next_count_app_appId,
    categoryinfo_filter_list_id_next_count_app_appId_mockputtopost, categoryinfo_filter_list_id_prev_count_app_appId, categoryinfo_filter_list_id_prev_count_app_appId_mockputtopost, categoryinfo_filter_list_page_size_size, categoryinfo_filter_list_page_size_size_mockputtopost, categoryinfo_list_all, categoryinfo_list_manage_app_appId, categoryinfo_list_objects, categoryinfo_list_publish_app_appId, categoryinfo_list_view_app_appId,
    categoryinfo_list_view_app_appId_all, categoryinfo_list_view_app_appId_data, categoryinfo_flag, categoryinfo_id, commend_list_paging_page_size_size, commend_id, comment_list_id_next_count, comment_list_id_next_count_mockputtopost, comment_list_id_prev_count, comment_list_id_prev_count_mockputtopost,
    comment_list_page_size_size, comment_list_page_size_size_mockputtopost, comment_id, correlation_doc_docId, correlation_list_doc_docId, correlation_list_doc_docId_site_site, data_document_id, design_appdict_list_appInfo_appId, design_appdict_list_paging_page_size_size, design_appdict_id,
    document_cipher_filter_list_page_size_size, document_cipher_filter_list_page_size_size_mockputtopost, file_list_appInfo_appInfoFlag, file_list_id_next_count, file_list_id_prev_count, file_flag, file_flag_appInfo_appInfoFlag, file_id, fileinfo_list_all, fileinfo_list_document_documentId,
    fileinfo_list_filter, form_filter_list_id_next_count_app_appId, form_filter_list_id_next_count_app_appId_mockputtopost, form_filter_list_id_prev_count_app_appId, form_filter_list_id_prev_count_app_appId_mockputtopost, form_list_all, form_list_app_appId, form_list_formfield_appInfo_appId, form_list_id_formfield, form_id,
    form_v2_id, log_filter_list_id_next_count, log_filter_list_id_prev_count, log_list_app_appId, log_list_category_categoryId, log_list_document_documentId, log_list_filter_page_size_size, log_list_level_operationLevel, log_id, output_list,
    permission_appInfo_id_manageable, permission_appInfo_id_managers, permission_appInfo_id_publishers, permission_appInfo_id_viewers, permission_category_id_managers, permission_category_id_publishers, permission_category_id_viewers, permission_categoryInfo_id_manageable, permission_management_refresh_all, permission_manager_appInfo_id,
    permission_manager_categoryInfo_id, permission_publisher_appInfo_id, permission_publisher_categoryInfo_id, permission_viewer_appInfo_id, permission_viewer_categoryInfo_id, script_list_app_appId_name_name, script_list_app_flag, script_list_manager, script_list_paging_page_size_size, script_list_id_next_count,
    script_list_id_prev_count, script_flag_appInfo_appInfoFlag, script_id, searchfilter_list_archive_filter_category_categoryId, searchfilter_list_draft_filter_category_categoryId, searchfilter_list_publish_filter_category_categoryId, anonymous_surface_appdict_list_appInfo_appInfoFlag, surface_appdict_list_appInfo_appInfoFlag, templateform_list, templateform_list_category,
    templateform_list_category_mockputtopost, uuid_random, view_list_all, view_list_app_appId, view_list_category_categoryId, view_list_form_formId, view_viewdata_list_id_next_count, view_id, viewcategory_list_all, viewcategory_list_category_categoryId,
    viewcategory_list_view_viewId, viewcategory_id, viewfieldconfig_list_all, viewfieldconfig_list_view_viewId, viewfieldconfig_id, viewrecord_document_docId_filter_list_id_next_count, viewrecord_list_install_log_paging_page_size_size, image_encode_base64, image_encode_base64_size_size, image_resize_id_id_width_width_height_height,
    input_compare, input_compare_mockputtopost, input_cover, input_cover_mockputtopost, input_create, input_create_mockputtopost, input_prepare_cover, input_prepare_cover_mockputtopost, input_prepare_create, input_prepare_create_mockputtopost,
    document_u2_get, document_u2_delete, document_u2_create, document_u2_update, document_u2_publish, document_u2_publish_cancel, document_u2_commend, document_u2_uncommend, document_u2_top, document_u2_un_top, document_u2_category_change, document_u2_document_data,
    document_u2_list_document, document_u2_fields, document_u2_filter_count,
    comment_u2_create, comment_u2_delete, comment_u2_list_page_size_size,
    correlation_u2_doc_delete,
    file_u2_create, file_u2_update, fileinfo_u2_delete, fileinfo_u2_filter, fileinfo_u2_copy_to_doc, fileinfo_u2_replace_to_doc,
    form_u2_create, form_u2_update, form_u2_delete,
    script_u2_create, script_u2_update, script_u2_delete, script_u2_list_manager,
    templateform_u2_create, templateform_u2_delete,
    view_u2_create, view_u2_update, view_u2_delete,
    viewcategory_u2_create, viewcategory_u2_delete,
    viewfieldconfig_u2_create, viewfieldconfig_u2_update, viewfieldconfig_u2_delete,
    appinfo_u2_create, appinfo_u2_delete, categoryinfo_u2_create, categoryinfo_u2_delete,
    permission_u2_app_info, permission_u2_category_info, appconfig_u2_update, appconfig_u2_get, designer_u2_search,
};



pub fn router(pool: deadpool_postgres::Pool) -> axum::Router {
    Router::new()
        .route("/jaxrs/cms_assemble_control/get/control/config", get(get_control_config))
        .route("/jaxrs/cms_assemble_control/list/control/sections", get(list_control_sections))
        .route("/jaxrs/cms_assemble_control/update/control/config", get(update_control_config))
        .route("/jaxrs/document/{id}/view/count", post(document_id_view_count))
        .route("/jaxrs/commend/list/paging/{docId}", get(commend_list_paging))
        .route("/jaxrs/queryview/flag/{view_flag}/definition/{query_flag}", get(queryview_flag_definition))
        .route("/jaxrs/application/{id}", get(application_id))
        .route("/jaxrs/cms_assemble_control/document/search", get(document_search))
        .route("/jaxrs/anonymous/document/{id}/view", get(anonymous_document_id_view))
        .route("/jaxrs/data/document/{id}/array/data", get(data_document_id_array_data))
        .route("/jaxrs/data/document/{id}/mockdeletetoget", get(data_document_id_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/mockputtopost", post(data_document_id_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0", get(data_document_id_path0))
        .route("/jaxrs/data/document/{id}/path0/mockdeletetoget", get(data_document_id_path0_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/mockputtopost", post(data_document_id_path0_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1", get(data_document_id_path0_path1))
        .route("/jaxrs/data/document/{id}/path0/path1/mockdeletetoget", get(data_document_id_path0_path1_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/mockputtopost", post(data_document_id_path0_path1_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2", get(data_document_id_path0_path1_path2))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/mockdeletetoget", get(data_document_id_path0_path1_path2_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/mockputtopost", post(data_document_id_path0_path1_path2_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3", get(data_document_id_path0_path1_path2_path3))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/mockdeletetoget", get(data_document_id_path0_path1_path2_path3_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/mockputtopost", post(data_document_id_path0_path1_path2_path3_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4", get(data_document_id_path0_path1_path2_path3_path4))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/mockdeletetoget", get(data_document_id_path0_path1_path2_path3_path4_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/mockputtopost", post(data_document_id_path0_path1_path2_path3_path4_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5", get(data_document_id_path0_path1_path2_path3_path4_path5))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/mockdeletetoget", get(data_document_id_path0_path1_path2_path3_path4_path5_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/mockputtopost", post(data_document_id_path0_path1_path2_path3_path4_path5_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6", get(data_document_id_path0_path1_path2_path3_path4_path5_path6))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/mockdeletetoget", get(data_document_id_path0_path1_path2_path3_path4_path5_path6_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/mockputtopost", post(data_document_id_path0_path1_path2_path3_path4_path5_path6_mockputtopost))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/path7", get(data_document_id_path0_path1_path2_path3_path4_path5_path6_path7))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/path7/mockdeletetoget", get(data_document_id_path0_path1_path2_path3_path4_path5_path6_path7_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/path7/mockputtopost", post(data_document_id_path0_path1_path2_path3_path4_path5_path6_path7_mockputtopost))
        .route("/jaxrs/anonymous/fileinfo/download/document/{id}", get(anonymous_fileinfo_download_document_id))
        .route("/jaxrs/fileinfo/download/document/{id}", get(fileinfo_download_document_id))
        .route("/jaxrs/fileinfo/upload/document/{id}", post(fileinfo_upload_document_docId))
        .route("/jaxrs/fileinfo/{id}", get(fileinfo_id))
        .route("/jaxrs/fileinfo/{id}/document/{docId}", get(fileinfo_id_document_documentId))
        .route("/jaxrs/fileinfo/{id}/mockdeletetoget", get(fileinfo_id_mockdeletetoget))
                .route("/jaxrs/cms/assemble/control/anonymous/fileinfo/download/document/stream/{id}", get(anonymous_fileinfo_download_document_id_stream))
        .route("/jaxrs/cms/assemble/control/anonymous/form/{id}", get(anonymous_form_id))
        .route("/jaxrs/cms/assemble/control/anonymous/form/v2/{id}", get(anonymous_form_v2_id))
        .route("/jaxrs/cms/assemble/control/anonymous/form/v2/mobile/{id}", get(anonymous_form_v2_id_mobile))
        .route("/jaxrs/cms/assemble/control/anonymous/form/v2/lookup/document/{docId}", get(anonymous_form_v2_lookup_document_docId))
        .route("/jaxrs/cms/assemble/control/anonymous/form/v2/lookup/document/mobile/{docId}", get(anonymous_form_v2_lookup_document_docId_mobile))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/path3/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/path3/path4/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/path3/path4/path5/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/path3/path4/path5/path6/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data))
        .route("/jaxrs/cms/assemble/control/anonymous/surface/appdict/path0/path1/path2/path3/path4/path5/path6/path7/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(anonymous_surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data))
        .route("/jaxrs/cms/assemble/control/appinfo/alias/alias", get(appinfo_alias_alias))
        .route("/jaxrs/cms/assemble/control/appinfo/icon/{appId}/{size}/{size}", get(appinfo_appId_icon_size_size))
        .route("/jaxrs/cms/assemble/control/appinfo/erase/app/{id}", post(appinfo_erase_app_id))
        .route("/jaxrs/cms/assemble/control/appinfo/erase/app/mockdeletetoget/{id}", post(appinfo_erase_app_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/appinfo/get/user/publish/{appId}", post(appinfo_get_user_publish_appId))
        .route("/jaxrs/cms/assemble/control/appinfo/control/{id}", get(appinfo_id_control))
        .route("/jaxrs/cms/assemble/control/appinfo/mockdeletetoget/{id}", post(appinfo_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/appinfo/permission/{id}", get(appinfo_id_permission))
        .route("/jaxrs/cms/assemble/control/categoryinfo/alias/alias", get(categoryinfo_alias_alias))
        .route("/jaxrs/cms/assemble/control/categoryinfo/bind/view/{categoryId}", post(categoryinfo_bind_categoryId_view))
        .route("/jaxrs/cms/assemble/control/categoryinfo/bind/view/mockputtopost/{categoryId}", post(categoryinfo_bind_categoryId_view_mockputtopost))
        .route("/jaxrs/cms/assemble/control/categoryinfo/erase/{category}/{id}", post(categoryinfo_erase_category_id))
        .route("/jaxrs/cms/assemble/control/categoryinfo/erase/mockdeletetoget/{category}/{id}", post(categoryinfo_erase_category_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/categoryinfo/{extContent}", get(categoryinfo_extContent))
        .route("/jaxrs/cms/assemble/control/categoryinfo/control/{id}", get(categoryinfo_id_control))
        .route("/jaxrs/cms/assemble/control/categoryinfo/execute/projection/{id}", get(categoryinfo_id_execute_projection))
        .route("/jaxrs/cms/assemble/control/categoryinfo/mockdeletetoget/{id}", post(categoryinfo_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/categoryinfo/permission/{id}", get(categoryinfo_id_permission))
        .route("/jaxrs/cms/assemble/control/comment/commend/{id}", get(comment_id_commend))
        .route("/jaxrs/cms/assemble/control/comment/mockdeletetoget/{id}", post(comment_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/comment/uncommend/{id}", get(comment_id_uncommend))
        .route("/jaxrs/cms/assemble/control/correlation/doc/delete/{docId}", post(correlation_doc_docId_delete))
        .route("/jaxrs/cms/assemble/control/correlation/update/doc/{docId}", post(correlation_update_doc_docId))
        .route("/jaxrs/cms/assemble/control/design/appdict/mockdeletetoget/{id}", post(design_appdict_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/design/appdict/mockputtopost/{id}", get(design_appdict_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/document/cipher/permission/read/person/person/{id}", get(document_cipher_id_permission_read_person_person))
        .route("/jaxrs/cms/assemble/control/document/cipher/persist/view/record/{id}", get(document_cipher_id_persist_view_record))
        .route("/jaxrs/cms/assemble/control/document/cipher/publish/content", post(document_cipher_publish_content))
        .route("/jaxrs/cms/assemble/control/document/cipher/publish/content/mockputtopost", post(document_cipher_publish_content_mockputtopost))
        .route("/jaxrs/cms/assemble/control/file/content/{flag}/{appInfo}/{appInfoFlag}", get(file_flag_appInfo_appInfoFlag_content))
        .route("/jaxrs/cms/assemble/control/file/download/{flag}/{appInfo}/{appInfoFlag}", get(file_flag_appInfo_appInfoFlag_download))
        .route("/jaxrs/cms/assemble/control/file/mockdeletetoget/{flag}", post(file_flag_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/file/content/{id}", get(file_id_content))
        .route("/jaxrs/cms/assemble/control/file/download/{id}", get(file_id_download))
        .route("/jaxrs/cms/assemble/control/file/mockputtopost/{id}", get(file_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/file/upload/{id}", post(file_id_upload))
        .route("/jaxrs/cms/assemble/control/fileinfo/batch/download/doc/site/site/{docId}", get(fileinfo_batch_download_doc_docId_site_site))
        .route("/jaxrs/cms/assemble/control/fileinfo/copy/to/doc/{docId}", get(fileinfo_copy_to_doc_docId))
        .route("/jaxrs/cms/assemble/control/fileinfo/download/document/stream/{id}", get(fileinfo_download_document_id_stream))
        .route("/jaxrs/cms/assemble/control/fileinfo/download/transfer/{flag}/{flag}", get(fileinfo_download_transfer_flag_flag))
        .route("/jaxrs/cms/assemble/control/fileinfo/edit/doc/{id}/{docId}", get(fileinfo_edit_id_doc_docId))
        .route("/jaxrs/cms/assemble/control/fileinfo/edit/doc/mockputtopost/{id}/{docId}", get(fileinfo_edit_id_doc_docId_mockputtopost))
        .route("/jaxrs/cms/assemble/control/fileinfo/binary/base64/{id}/{size}", get(fileinfo_id_binary_base64_size))
        .route("/jaxrs/cms/assemble/control/fileinfo/doc/change/seqnumber/{id}/{docId}/{seqNumber}", get(fileinfo_id_doc_docId_change_seqnumber_seqNumber))
        .route("/jaxrs/cms/assemble/control/fileinfo/online/info/{id}", get(fileinfo_id_online_info))
        .route("/jaxrs/cms/assemble/control/fileinfo/preview/pdf/{id}", get(fileinfo_id_preview_pdf))
        .route("/jaxrs/cms/assemble/control/fileinfo/replace/to/doc/{docId}", get(fileinfo_replace_to_doc_docId))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/document/attachment/{docId}/{id}", post(fileinfo_update_document_docId_attachment_id))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/document/attachment/callback/callback/{docId}/{id}", post(fileinfo_update_document_docId_attachment_id_callback_callback))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/content/{id}", post(fileinfo_update_id_content))
        .route("/jaxrs/cms/assemble/control/fileinfo/upload/doc/save/as/{docId}/{flag}", post(fileinfo_upload_doc_docId_save_as_flag))
        .route("/jaxrs/cms/assemble/control/fileinfo/upload/document/callback/callback/{docId}", post(fileinfo_upload_document_docId_callback_callback))
        .route("/jaxrs/cms/assemble/control/fileinfo/upload/with/url", post(fileinfo_upload_with_url))
        .route("/jaxrs/cms/assemble/control/form/appinfo/{formFlag}/{appFlag}", get(form_formFlag_appinfo_appFlag))
        .route("/jaxrs/cms/assemble/control/form/mockdeletetoget/{id}", post(form_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/form/mockputtopost/{id}", get(form_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/form/v2/mobile/{id}", get(form_v2_id_mobile))
        .route("/jaxrs/cms/assemble/control/form/v2/lookup/document/{docId}", get(form_v2_lookup_document_docId))
        .route("/jaxrs/cms/assemble/control/form/v2/lookup/document/mobile/{docId}", get(form_v2_lookup_document_docId_mobile))
        .route("/jaxrs/cms/assemble/control/formversion/{id}", get(formversion_id))
        .route("/jaxrs/cms/assemble/control/formversion/list/form/{formId}", get(formversion_list_form_formId))
        .route("/jaxrs/cms/assemble/control/output/select/{appInfoFlag}", get(output_appInfoFlag_select))
        .route("/jaxrs/cms/assemble/control/output/select/mockputtopost/{appInfoFlag}", get(output_appInfoFlag_select_mockputtopost))
        .route("/jaxrs/cms/assemble/control/permission/management/refresh/{category}/{categoryId}", get(permission_management_refresh_category_categoryId))
        .route("/jaxrs/cms/assemble/control/script/mockdeletetoget/{id}", post(script_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/script/mockputtopost/{id}", get(script_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/script/app/{uniqueName}/{flag}", get(script_uniqueName_app_flag))
        .route("/jaxrs/cms/assemble/control/script/app/imported/{uniqueName}/{flag}", get(script_uniqueName_app_flag_imported))
        .route("/jaxrs/cms/assemble/control/scriptversion/{id}", get(scriptversion_id))
        .route("/jaxrs/cms/assemble/control/scriptversion/list/script/{scriptId}", get(scriptversion_list_script_scriptId))
        .route("/jaxrs/cms/assemble/control/surface/appdict/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag))
        .route("/jaxrs/cms/assemble/control/surface/appdict/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/path7/data/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/path7/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", post(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/path7/data/mockputtopost/{appDictFlag}/{appInfo}/{appInfoFlag}", get(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockputtopost))
        .route("/jaxrs/cms/assemble/control/templateform/{id}", get(templateform_id))
        .route("/jaxrs/cms/assemble/control/templateform/mockdeletetoget/{id}", post(templateform_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/view/mockdeletetoget/{id}", post(view_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/view/mockputtopost/{id}", get(view_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/viewcategory/mockdeletetoget/{id}", post(viewcategory_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/viewfieldconfig/mockdeletetoget/{id}", post(viewfieldconfig_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/viewfieldconfig/mockputtopost/{id}", get(viewfieldconfig_id_mockputtopost))
        .route("/jaxrs/cms/assemble/control/viewrecord/document/has/view/{docId}", get(viewrecord_document_docId_has_view))
        .route("/jaxrs/cms_assemble_control/anonymous/document/filter/list/id/next/count", get(anonymous_document_filter_list_id_next_count))
        .route("/jaxrs/cms_assemble_control/anonymous/document/filter/list/id/next/count/mockputtopost", post(anonymous_document_filter_list_id_next_count_mockputtopost))
        .route("/jaxrs/cms_assemble_control/anonymous/document/filter/list/page/size/size", get(anonymous_document_filter_list_page_size_size))
        .route("/jaxrs/cms_assemble_control/anonymous/document/filter/list/page/size/size/mockputtopost", post(anonymous_document_filter_list_page_size_size_mockputtopost))
        .route("/jaxrs/anonymous/fileinfo/list/{documentId}", get(anonymous_fileinfo_list_document_documentId))
        .route("/jaxrs/cms_assemble_control/appinfo/filter/list/id/next/count", get(appinfo_filter_list_id_next_count))
        .route("/jaxrs/cms_assemble_control/appinfo/filter/list/id/next/count/mockputtopost", post(appinfo_filter_list_id_next_count_mockputtopost))
        .route("/jaxrs/cms_assemble_control/appinfo/filter/list/id/prev/count", get(appinfo_filter_list_id_prev_count))
        .route("/jaxrs/cms_assemble_control/appinfo/filter/list/id/prev/count/mockputtopost", post(appinfo_filter_list_id_prev_count_mockputtopost))
        .route("/jaxrs/appinfo/list/all", get(appinfo_list_all))
        .route("/jaxrs/appinfo/list/{appType}", get(appinfo_list_appType))
        .route("/jaxrs/appinfo/list/{appType}/manager", get(appinfo_list_appType_manager))
        .route("/jianfo/list/has/document", get(appinfo_list_has_document))
        .route("/jaxrs/appinfo/list/has/document/{appType}", get(appinfo_list_has_document_appType))
        .route("/jaxrs/appinfo/list/has/document/type/{appType}", get(appinfo_list_has_document_type_appType))
        .route("/jaxrs/appinfo/list/manage", get(appinfo_list_manage))
        .route("/jaxrs/appinfo/list/manage/type/{appType}", get(appinfo_list_manage_type_appType))
        .route("/jaxrs/appinfo/list/user/publish", get(appinfo_list_user_publish))
        .route("/jaxrs/appinfo/list/user/publish/type/{appType}", get(appinfo_list_user_publish_type_appType))
        .route("/jaxrs/appinfo/list/user/publish/with/process", get(appinfo_list_user_publish_with_process))
        .route("/jaxrs/appinfo/list/user/view", get(appinfo_list_user_view))
        .route("/jaxrs/appinfo/list/user/view/all", get(appinfo_list_user_view_all))
        .route("/jaxrs/appinfo/list/user/view/all/type/{appType}", get(appinfo_list_user_view_all_type_appType))
        .route("/jaxrs/appinfo/list/user/view/article/type/{appType}", get(appinfo_list_user_view_article_type_appType))
        .route("/jaxrs/appinfo/list/user/view/data", get(appinfo_list_user_view_data))
        .route("/jaxrs/appinfo/list/user/view/data/type/{appType}", get(appinfo_list_user_view_data_type_appType))
        .route("/jaxrs/appinfo/flag", get(appinfo_flag))
        .route("/jaxrs/appinfo/{id}", get(appinfo_id))
        .route("/jaxrs/categoryinfo/filter/list/{id}/next/{count}/app/{appId}", put(categoryinfo_filter_list_id_next_count_app_appId))
        .route("/jaxrs/categoryinfo/filter/list/{id}/next/{count}/app/{appId}/mockputtopost", post(categoryinfo_filter_list_id_next_count_app_appId_mockputtopost))
        .route("/jaxrs/categoryinfo/filter/list/{id}/prev/{count}/app/{appId}", put(categoryinfo_filter_list_id_prev_count_app_appId))
        .route("/jaxrs/categoryinfo/filter/list/{id}/prev/{count}/app/{appId}/mockputtopost", post(categoryinfo_filter_list_id_prev_count_app_appId_mockputtopost))
        .route("/jaxrs/categoryinfo/filter/list/page/{size}", put(categoryinfo_filter_list_page_size_size))
        .route("/jaxrs/categoryinfo/filter/list/page/{size}/mockputtopost", post(categoryinfo_filter_list_page_size_size_mockputtopost))
        .route("/jaxrs/categoryinfo/list/all", get(categoryinfo_list_all))
        .route("/jaxrs/categoryinfo/list/manage/app/{appId}", get(categoryinfo_list_manage_app_appId))
        .route("/jaxrs/categoryinfo/list/objects", get(categoryinfo_list_objects))
        .route("/jaxrs/categoryinfo/list/publish/app/{appId}", get(categoryinfo_list_publish_app_appId))
        .route("/jaxrs/categoryinfo/list/view/app/{appId}", get(categoryinfo_list_view_app_appId))
        .route("/jaxrs/categoryinfo/list/view/app/{appId}/all", get(categoryinfo_list_view_app_appId_all))
        .route("/jaxrs/categoryinfo/list/view/app/{appId}/data", get(categoryinfo_list_view_app_appId_data))
        .route("/jaxrs/categoryinfo/flag", get(categoryinfo_flag))
        .route("/jaxrs/categoryinfo/{id}", get(categoryinfo_id))
        .route("/jaxrs/commend/list/paging/{pageSize}/{size}", get(commend_list_paging_page_size_size))
        .route("/jaxrs/commend/{id}", get(commend_id))
        .route("/jaxrs/comment/list/{id}/next/count", get(comment_list_id_next_count))
        .route("/jaxrs/comment/list/{id}/next/count/mockputtopost", get(comment_list_id_next_count_mockputtopost))
        .route("/jaxrs/comment/list/{id}/prev/count", get(comment_list_id_prev_count))
        .route("/jaxrs/comment/list/{id}/prev/count/mockputtopost", get(comment_list_id_prev_count_mockputtopost))
        .route("/jaxrs/comment/list/page/{size}", get(comment_list_page_size_size))
        .route("/jaxrs/comment/list/page/{size}/mockputtopost", get(comment_list_page_size_size_mockputtopost))
        .route("/jaxrs/comment/{id}", get(comment_id))
        .route("/jaxrs/correlation/doc/{docId}", get(correlation_doc_docId))
        .route("/jaxrs/correlation/list/doc/{docId}", get(correlation_list_doc_docId))
        .route("/jaxrs/correlation/list/doc/{docId}/site/{site}", get(correlation_list_doc_docId_site_site))
        .route("/jaxrs/data/document/{id}", get(data_document_id))
        .route("/jaxrs/design/appdict/list/appInfo/{appId}", get(design_appdict_list_appInfo_appId))
        .route("/jaxrs/design/appdict/list/paging/{pageSize}/{size}", get(design_appdict_list_paging_page_size_size))
        .route("/jaxrs/design/appdict/{id}", get(design_appdict_id))
        .route("/jaxrs/document/cipher/filter/list/page/{size}", put(document_cipher_filter_list_page_size_size))
        .route("/jaxrs/document/cipher/filter/list/page/{size}/mockputtopost", post(document_cipher_filter_list_page_size_size_mockputtopost))
        .route("/jaxrs/file/list/appInfo/{appInfoFlag}", get(file_list_appInfo_appInfoFlag))
        .route("/jaxrs/file/list/{id}/next/count", get(file_list_id_next_count))
        .route("/jaxrs/file/list/{id}/prev/count", get(file_list_id_prev_count))
        .route("/jaxrs/file/flag", get(file_flag))
        .route("/jaxrs/file/flag/appInfo/{appInfoFlag}", get(file_flag_appInfo_appInfoFlag))
        .route("/jaxrs/file/{id}", get(file_id))
        .route("/jaxrs/fileinfo/list/all", get(fileinfo_list_all))
        .route("/jaxrs/fileinfo/list/document/{documentId}", get(fileinfo_list_document_documentId))
        .route("/jaxrs/fileinfo/list/filter", put(fileinfo_list_filter))
        .route("/jaxrs/form/filter/list/{id}/next/count/app/{appId}", put(form_filter_list_id_next_count_app_appId))
        .route("/jaxrs/form/filter/list/{id}/next/count/app/{appId}/mockputtopost", post(form_filter_list_id_next_count_app_appId_mockputtopost))
        .route("/jaxrs/form/filter/list/{id}/prev/count/app/{appId}", put(form_filter_list_id_prev_count_app_appId))
        .route("/jaxrs/form/filter/list/{id}/prev/count/app/{appId}/mockputtopost", post(form_filter_list_id_prev_count_app_appId_mockputtopost))
        .route("/jaxrs/form/list/all", get(form_list_all))
        .route("/jaxrs/form/list/app/{appId}", get(form_list_app_appId))
        .route("/jaxrs/form/list/formfield/appInfo/{appId}", get(form_list_formfield_appInfo_appId))
        .route("/jaxrs/form/list/{id}/formfield", get(form_list_id_formfield))
        .route("/jaxrs/form/{id}", get(form_id))
        .route("/jaxrs/form/v2/{id}", get(form_v2_id))
        .route("/jaxrs/log/filter/list/{id}/next/count", get(log_filter_list_id_next_count))
        .route("/jaxrs/log/filter/list/{id}/prev/count", get(log_filter_list_id_prev_count))
        .route("/jaxrs/log/list/app/{appId}", get(log_list_app_appId))
        .route("/jaxrs/log/list/category/{categoryId}", get(log_list_category_categoryId))
        .route("/jaxrs/log/list/document/{documentId}", get(log_list_document_documentId))
        .route("/jaxrs/log/list/filter/page/{size}", put(log_list_filter_page_size_size))
        .route("/jaxrs/log/list/level/{operationLevel}", get(log_list_level_operationLevel))
        .route("/jaxrs/log/{id}", get(log_id))
        .route("/jaxrs/output/list", get(output_list))
        .route("/jaxrs/permission/appInfo/{id}/manageable", get(permission_appInfo_id_manageable))
        .route("/jaxrs/permission/appInfo/{id}/managers", get(permission_appInfo_id_managers))
        .route("/jaxrs/permission/appInfo/{id}/publishers", get(permission_appInfo_id_publishers))
        .route("/jaxrs/permission/appInfo/{id}/viewers", get(permission_appInfo_id_viewers))
        .route("/jaxrs/permission/category/{id}/managers", get(permission_category_id_managers))
        .route("/jaxrs/permission/category/{id}/publishers", get(permission_category_id_publishers))
        .route("/jaxrs/permission/category/{id}/viewers", get(permission_category_id_viewers))
        .route("/jaxrs/permission/categoryInfo/{id}/manageable", get(permission_categoryInfo_id_manageable))
        .route("/jaxrs/permission/management/refresh/all", get(permission_management_refresh_all))
        .route("/jaxrs/permission/manager/appInfo/{id}", get(permission_manager_appInfo_id))
        .route("/jaxrs/permission/manager/categoryInfo/{id}", get(permission_manager_categoryInfo_id))
        .route("/jaxrs/permission/publisher/appInfo/{id}", get(permission_publisher_appInfo_id))
        .route("/jaxrs/permission/publisher/categoryInfo/{id}", get(permission_publisher_categoryInfo_id))
        .route("/jaxrs/permission/viewer/appInfo/{id}", get(permission_viewer_appInfo_id))
        .route("/jaxrs/permission/viewer/categoryInfo/{id}", get(permission_viewer_categoryInfo_id))
        .route("/jaxrs/script/list/app/{appId}/name/{name}", get(script_list_app_appId_name_name))
        .route("/jaxrs/script/list/app/{flag}", get(script_list_app_flag))
        .route("/jaxrs/script/list/manager", get(script_list_manager))
        .route("/jaxrs/script/list/paging/{pageSize}/{size}", get(script_list_paging_page_size_size))
        .route("/jaxrs/script/list/{id}/next/count", get(script_list_id_next_count))
        .route("/jaxrs/script/list/{id}/prev/count", get(script_list_id_prev_count))
        .route("/jaxrs/script/flag/appInfo/{appInfoFlag}", get(script_flag_appInfo_appInfoFlag))
        .route("/jaxrs/script/{id}", get(script_id))
        .route("/jaxrs/searchfilter/list/archive/filter/category/{categoryId}", get(searchfilter_list_archive_filter_category_categoryId))
        .route("/jaxrs/searchfilter/list/draft/filter/category/{categoryId}", get(searchfilter_list_draft_filter_category_categoryId))
        .route("/jaxrs/searchfilter/list/publish/filter/category/{categoryId}", get(searchfilter_list_publish_filter_category_categoryId))
        .route("/jaxrs/anonymous/surface/appdict/list/appInfo/{appInfoFlag}", get(anonymous_surface_appdict_list_appInfo_appInfoFlag))
        .route("/jaxrs/surface/appdict/list/appInfo/{appInfoFlag}", get(surface_appdict_list_appInfo_appInfoFlag))
        .route("/jaxrs/templateform/list", get(templateform_list))
        .route("/jaxrs/templateform/list/category", get(templateform_list_category))
        .route("/jaxrs/templateform/list/category/mockputtopost", post(templateform_list_category_mockputtopost))
        .route("/jaxrs/uuid/random", get(uuid_random))
        .route("/jaxrs/view/list/all", get(view_list_all))
        .route("/jaxrs/view/list/app/{appId}", get(view_list_app_appId))
        .route("/jaxrs/view/list/category/{categoryId}", get(view_list_category_categoryId))
        .route("/jaxrs/view/list/form/{formId}", get(view_list_form_formId))
        .route("/jaxrs/view/viewdata/list/{id}/next/count", get(view_viewdata_list_id_next_count))
        .route("/jaxrs/view/{id}", get(view_id))
        .route("/jaxrs/viewcategory/list/all", get(viewcategory_list_all))
        .route("/jaxrs/viewcategory/list/category/{categoryId}", get(viewcategory_list_category_categoryId))
        .route("/jaxrs/viewcategory/list/view/{viewId}", get(viewcategory_list_view_viewId))
        .route("/jaxrs/viewcategory/{id}", get(viewcategory_id))
        .route("/jaxrs/viewfieldconfig/list/all", get(viewfieldconfig_list_all))
        .route("/jaxrs/viewfieldconfig/list/view/{viewId}", get(viewfieldconfig_list_view_viewId))
        .route("/jaxrs/viewfieldconfig/{id}", get(viewfieldconfig_id))
        .route("/jaxrs/viewrecord/document/{docId}/filter/list/{id}/next/count", get(viewrecord_document_docId_filter_list_id_next_count))
        .route("/jaxrs/viewrecord/list/install/log/paging/{pageSize}/{size}", get(viewrecord_list_install_log_paging_page_size_size))
        .route("/jaxrs/image/encode/base64", post(image_encode_base64))
        .route("/jaxrs/image/encode/base64/{size}/{size}", post(image_encode_base64_size_size))
        .route("/jaxrs/image/resize/{id}/{id}/width/{width}/{height}", post(image_resize_id_id_width_width_height_height))
        .route("/jaxrs/input/compare", put(input_compare))
        .route("/jaxrs/input/compare/mockputtopost", post(input_compare_mockputtopost))
        .route("/jaxrs/input/cover", put(input_cover))
        .route("/jaxrs/input/cover/mockputtopost", post(input_cover_mockputtopost))
        .route("/jaxrs/input/create", put(input_create))
        .route("/jaxrs/input/create/mockputtopost", post(input_create_mockputtopost))
        .route("/jaxrs/input/prepare/cover", put(input_prepare_cover))
        .route("/jaxrs/input/prepare/cover/mockputtopost", post(input_prepare_cover_mockputtopost))
        .route("/jaxrs/input/prepare/create", put(input_prepare_create))
        .route("/jaxrs/input/prepare/create/mockputtopost", post(input_prepare_create_mockputtopost))
        .route("/jaxrs/cms_assemble_control/update/control/config", put(update_control_config))
        .route("/jaxrs/data/document/{id}/mockdeletetoget", delete(data_document_id_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/mockdeletetoget", delete(data_document_id_path0_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/mockdeletetoget", delete(data_document_id_path0_path1_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/mockdeletetoget", delete(data_document_id_path0_path1_path2_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/mockdeletetoget", delete(data_document_id_path0_path1_path2_path3_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/mockdeletetoget", delete(data_document_id_path0_path1_path2_path3_path4_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/mockdeletetoget", delete(data_document_id_path0_path1_path2_path3_path4_path5_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/mockdeletetoget", delete(data_document_id_path0_path1_path2_path3_path4_path5_path6_mockdeletetoget))
        .route("/jaxrs/data/document/{id}/path0/path1/path2/path3/path4/path5/path6/path7/mockdeletetoget", delete(data_document_id_path0_path1_path2_path3_path4_path5_path6_path7_mockdeletetoget))
        .route("/jaxrs/fileinfo/{id}/mockdeletetoget", delete(fileinfo_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/appinfo/erase/app/mockdeletetoget/{id}", delete(appinfo_erase_app_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/appinfo/mockdeletetoget/{id}", delete(appinfo_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/categoryinfo/erase/mockdeletetoget/{category}/{id}", delete(categoryinfo_erase_category_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/categoryinfo/mockdeletetoget/{id}", delete(categoryinfo_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/comment/mockdeletetoget/{id}", delete(comment_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/correlation/doc/delete/{docId}", delete(correlation_doc_docId_delete))
        .route("/jaxrs/cms/assemble/control/correlation/update/doc/{docId}", put(correlation_update_doc_docId))
        .route("/jaxrs/cms/assemble/control/design/appdict/mockdeletetoget/{id}", delete(design_appdict_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/file/mockdeletetoget/{flag}", delete(file_flag_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/document/attachment/{docId}/{id}", put(fileinfo_update_document_docId_attachment_id))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/document/attachment/callback/callback/{docId}/{id}", put(fileinfo_update_document_docId_attachment_id_callback_callback))
        .route("/jaxrs/cms/assemble/control/fileinfo/update/content/{id}", put(fileinfo_update_id_content))
        .route("/jaxrs/cms/assemble/control/fileinfo/upload/doc/save/as/{docId}/{flag}", put(fileinfo_upload_doc_docId_save_as_flag))
        .route("/jaxrs/cms/assemble/control/form/mockdeletetoget/{id}", delete(form_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/script/mockdeletetoget/{id}", delete(script_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/surface/appdict/path0/path1/path2/path3/path4/path5/path6/path7/data/mockdeletetoget/{appDictFlag}/{appInfo}/{appInfoFlag}", delete(surface_appdict_appDictFlag_appInfo_appInfoFlag_path0_path1_path2_path3_path4_path5_path6_path7_data_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/templateform/mockdeletetoget/{id}", delete(templateform_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/view/mockdeletetoget/{id}", delete(view_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/viewcategory/mockdeletetoget/{id}", delete(viewcategory_id_mockdeletetoget))
        .route("/jaxrs/cms/assemble/control/viewfieldconfig/mockdeletetoget/{id}", delete(viewfieldconfig_id_mockdeletetoget))
        // ── plan002 U2: Java 对齐缺口端点 ──
        .route("/jaxrs/document/{id}", get(document_u2_get))
        .route("/jaxrs/document/{id}", delete(document_u2_delete))
        .route("/jaxrs/document", post(document_u2_create))
        .route("/jaxrs/document/{id}/update", post(document_u2_update))
        .route("/jaxrs/document/publish/{id}", put(document_u2_publish))
        .route("/jaxrs/document/publish/{id}/mockputtopost", post(document_u2_publish))
        .route("/jaxrs/document/publish/{id}/cancel", put(document_u2_publish_cancel))
        .route("/jaxrs/document/publish/{id}/cancel/mockputtopost", post(document_u2_publish_cancel))
        .route("/jaxrs/document/{id}/commend", get(document_u2_commend))
        .route("/jaxrs/document/{id}/uncommend", get(document_u2_uncommend))
        .route("/jaxrs/document/{id}/top", get(document_u2_top))
        .route("/jaxrs/document/{id}/unTop", get(document_u2_un_top))
        .route("/jaxrs/document/category/change", put(document_u2_category_change))
        .route("/jaxrs/document/category/change/mockputtopost", post(document_u2_category_change))
        .route("/jaxrs/document/{id}/document/data", get(document_u2_document_data))
        .route("/jaxrs/document/list/document", post(document_u2_list_document))
        .route("/jaxrs/document/document/fields", get(document_u2_fields))
        .route("/jaxrs/document/filter/count", put(document_u2_filter_count))
        .route("/jaxrs/document/filter/count/mockputtopost", post(document_u2_filter_count))
        .route("/jaxrs/comment", post(comment_u2_create))
        .route("/jaxrs/comment/{id}", delete(comment_u2_delete))
        .route("/jaxrs/comment/list/{page}/size/{size}", put(comment_u2_list_page_size_size))
        .route("/jaxrs/comment/list/{page}/size/{size}/mockputtopost", post(comment_u2_list_page_size_size))
        .route("/jaxrs/correlation/doc/{docId}/delete", post(correlation_u2_doc_delete))
        .route("/jaxrs/file", post(file_u2_create))
        .route("/jaxrs/file/{id}/mockputtopost", post(file_u2_update))
        .route("/jaxrs/fileinfo/{id}", delete(fileinfo_u2_delete))
        .route("/jaxrs/fileinfo/list/filter", post(fileinfo_u2_filter))
        .route("/jaxrs/fileinfo/copy/to/doc/{docId}", post(fileinfo_u2_copy_to_doc))
        .route("/jaxrs/fileinfo/replace/to/doc/{docId}", post(fileinfo_u2_replace_to_doc))
        .route("/jaxrs/form", post(form_u2_create))
        .route("/jaxrs/form/{id}", put(form_u2_update))
        .route("/jaxrs/form/{id}", delete(form_u2_delete))
        .route("/jaxrs/script", post(script_u2_create))
        .route("/jaxrs/script/{id}", put(script_u2_update))
        .route("/jaxrs/script/{id}", delete(script_u2_delete))
        .route("/jaxrs/script/list/manager", post(script_u2_list_manager))
        .route("/jaxrs/templateform", post(templateform_u2_create))
        .route("/jaxrs/templateform/{id}", delete(templateform_u2_delete))
        .route("/jaxrs/view", post(view_u2_create))
        .route("/jaxrs/view/{id}", put(view_u2_update))
        .route("/jaxrs/view/{id}", delete(view_u2_delete))
        .route("/jaxrs/viewcategory", post(viewcategory_u2_create))
        .route("/jaxrs/viewcategory/{id}", delete(viewcategory_u2_delete))
        .route("/jaxrs/viewfieldconfig", post(viewfieldconfig_u2_create))
        .route("/jaxrs/viewfieldconfig/{id}", put(viewfieldconfig_u2_update))
        .route("/jaxrs/viewfieldconfig/{id}", delete(viewfieldconfig_u2_delete))
        .route("/jaxrs/appinfo", post(appinfo_u2_create))
        .route("/jaxrs/appinfo/{id}", delete(appinfo_u2_delete))
        .route("/jaxrs/categoryinfo", post(categoryinfo_u2_create))
        .route("/jaxrs/categoryinfo/{id}", delete(categoryinfo_u2_delete))
        .route("/jaxrs/appinfo/{id}/permission", post(permission_u2_app_info))
        .route("/jaxrs/categoryinfo/{id}/permission", post(permission_u2_category_info))
        .route("/jaxrs/appconfig/{appId}", post(appconfig_u2_update))
        .route("/jaxrs/appconfig/{appId}", get(appconfig_u2_get))
        .route("/jaxrs/designer/search", post(designer_u2_search))
.layer(Extension(pool))
}

pub fn cms_assemble_control_router(pool: Pool) -> Router {
    router(pool)
}

