/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.open;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.open.FileConfig.class)
public class FileConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<FileConfig,Integer> capacity;
    public static volatile SingularAttribute<FileConfig,String> id;
    public static volatile SingularAttribute<FileConfig,String> name;
    public static volatile SingularAttribute<FileConfig,String> person;
    public static volatile SingularAttribute<FileConfig,FileConfigProperties> properties;
    public static volatile SingularAttribute<FileConfig,Integer> recycleDays;
}
