/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.open;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.open.OriginFile.class)
public class OriginFile_ extends StorageObject_  {
    public static volatile SingularAttribute<OriginFile,Boolean> deepPath;
    public static volatile SingularAttribute<OriginFile,String> extension;
    public static volatile SingularAttribute<OriginFile,String> fileMd5;
    public static volatile SingularAttribute<OriginFile,String> id;
    public static volatile SingularAttribute<OriginFile,String> lastUpdatePerson;
    public static volatile SingularAttribute<OriginFile,Date> lastUpdateTime;
    public static volatile SingularAttribute<OriginFile,Long> length;
    public static volatile SingularAttribute<OriginFile,String> name;
    public static volatile SingularAttribute<OriginFile,String> person;
    public static volatile SingularAttribute<OriginFile,String> storage;
    public static volatile SingularAttribute<OriginFile,String> type;
}
