use axum::{
    extract::Extension,
    routing::{get, post, put, delete},
    Router,
};
use deadpool_postgres::Pool;

use crate::{
    applications, current_style, modules_all, application_create, application_save, agent_create, agent_save, collect_list, collect_add, collect_remove,
    config_get, agent_flag, agent_flag_disable, agent_flag_enable, agent_flag_execute, agent_flag_file, andfx_pull_sync, appstyle_current_style, appstyle_current_update, appstyle_image_application_top,
    appstyle_image_application_top_erase, appstyle_image_launch_logo, appstyle_image_launch_logo_erase, appstyle_image_login_avatar, appstyle_image_login_avatar_erase, appstyle_image_menu_logo_blur, appstyle_image_menu_logo_blur_erase, appstyle_image_menu_logo_focus, appstyle_image_menu_logo_focus_erase, appstyle_image_process_default,
    appstyle_image_process_default_erase, appstyle_image_setup_about_logo, appstyle_image_setup_about_logo_erase, appstyle_index_portal, bar_create_mass_from_count, bar_select1_field_field_value_value_count_count, bar_select2_count_count, bar_select3_field_field_value_value_count_count, bar_select4_field_field_value_value_count_count, captcha_list,
    captcha_v2_create_width_width_height_height, captcha_id_validate_answer_answer, center_applications, center_regist_applications, center_version, code_create_mobile_mobile, code_list, code_list_paging_page_size_size, code_validate_mobile_mobile_answer_answer, code_validate_mobile_mobile_answer_answer_cascade,
    collect_code_mobile_mobile, collect_connect, collect_controllebbs, collect_controllermobile_name_name_mobile_mobile, collect_disconnect, collect_login, collect_mobile_check_connect, collect_name_name_exist, collect_name_name_mobile_mobile_code_code, collect_person,
    collect_resetpassword, collect_sync_area, collect_updateUnit, collect_urlMapping, collect_validate, collect_validate_codeanswer, collect_validate_direct, collect_validate_password, command_execute, command_list_node,
    config_open_get_disable_export_enable, config_centerserver, config_change_password, config_collect, config_license, config_list, config_list_application, config_list_dump_data, config_list_dump_data_current_node, config_list_entity,
    config_open, config_open_run_time_config, config_person, config_portal, config_proxy, config_save, config_ternary_management, config_token, datastructure_fileds_all, datastructure_modules_all,
    datastructure_tables_all, deploy_list_paging_page_size_size, deploy_server_o2, deploy_server_resource, deploy_web_resource_as_new_asNew, deploy_id, designer_search, dict_list, dict_list_paging_page_size_size, dict_dictFlag_data,
    dict_dictFlag_path_data, dict_dictFlag_path_data_mockdeletetoget, dict_dictFlag_path_data_mockputtopost, dict_id, dingding_get_callback_aes, dingding_pull_sync, dingding_request_pull_sync, dingding_sync_organization_callback, dingding_sync_organization_register_callback_enable, distribute_assemble_source_source,
    distribute_webserver_assemble_source_source, foo_create_mass_from_count, input_compare, input_cover, input_create, input_prepare_cover, input_prepare_create, invoke_list_category, invoke_list_with_category_category, invoke_token,
    invoke_flag, invoke_flag_client_client_token_token_execute, invoke_flag_execute, invoke_flag_execute_get, invoke_flag_file, jest_clear_cache_source, jest_list, jest_version, market_cloud_unit_is_vip, market_install_offline,
    market_list_category, market_list_install_log_paging_page_size_size, market_list_paging_page_size_size, market_list_paging_page_size_size_category_category, market_list_top_three, market_flag, market_flag_cover_pic, market_flag_install_log, market_flag_install_or_update, market_flag_installed_version,
    market_flag_uninstall, market_id_download, module_compare_upload, module_list, module_list_category, module_output, module_output_structure, module_output_flag_file, module_remove_structure_id, module_write_flag,
    module_id_compare, mpweixin_check, mpweixin_media_add_forever, mpweixin_menu_add, mpweixin_menu_create_to_weixin, mpweixin_menu_delete_id, mpweixin_menu_subscribe, mpweixin_menu_update_id, mpweixin_message_template_send, output_list,
    output_appInfoFlag_select, output_flag_select_file, prompterrorlog_count_exceptionclass, prompterrorlog_count_loggername, prompterrorlog_list_id_next_count, prompterrorlog_list_id_next_count_date_date, prompterrorlog_list_id_next_count_exceptionclass_exceptionClass, prompterrorlog_list_id_next_count_loggername_loggerName, prompterrorlog_list_id_prev_count, prompterrorlog_list_id_prev_count_date_date,
    prompterrorlog_list_id_prev_count_exceptionclass_exceptionClass, prompterrorlog_list_id_prev_count_loggername_loggerName, prompterrorlog_id, qiyeweixin_get_callback_aes, qiyeweixin_pull_sync, qiyeweixin_request_pull_sync, qiyeweixin_send_getprivateinfo_message, schedule_list_schedule, schedule_list_schedulelocal, schedule_list_schedulelog_application_application,
    schedule_report, schedule_schedule_fire, script_list, script_list_paging_page_size_size, script_name_name, script_name_name_imported, script_flag, script_id, test_test1, test_test2,
    tokenthreshold_update, unexpectederrorlog_list_id_next_count, unexpectederrorlog_list_id_next_count_date_date, unexpectederrorlog_list_id_prev_count, unexpectederrorlog_list_id_prev_count_date_date, unexpectederrorlog_id, validation_meta, validation_scripting_benchmark, validation_timeout_timeout, zhengwudingding_pull_sync,
    zhengwudingding_regist_callback, zhengwudingding_sync_organization_callback,};


pub fn router(pool: Pool) -> Router {
    Router::new()
        .route("/jaxrs/program/applications", get(applications))
        .route("/jaxrs/program/appstyle/current/style", get(current_style))
        .route("/jaxrs/program/datastructure/modules/all", get(modules_all))
        .route("/jaxrs/program_center/application/create", post(application_create))
        .route("/jaxrs/program_center/application/save/{id}", post(application_save))
        .route("/jaxrs/program_center/agent/create", post(agent_create))
        .route("/jaxrs/program_center/agent/save/{id}", post(agent_save))
                .route("/jaxrs/program_center/collect/list", get(collect_list))
        .route("/jaxrs/program_center/collect/add", post(collect_add))
        .route("/jaxrs/program_center/collect/remove", get(collect_remove))
        .route("/jaxrs/program_center/config/get", get(config_get))
        .route("/jaxrs/program_center/agent/flag", get(agent_flag))
        .route("/jaxrs/program_center/agent/flag/disable", get(agent_flag_disable))
        .route("/jaxrs/program_center/agent/flag/enable", get(agent_flag_enable))
        .route("/jaxrs/program_center/agent/flag/execute", get(agent_flag_execute))
        .route("/jaxrs/program_center/agent/flag/file", get(agent_flag_file))
        .route("/jaxrs/program_center/andfx/pull/sync", get(andfx_pull_sync))
        .route("/jaxrs/program_center/appstyle/current/style", get(appstyle_current_style))
        .route("/jaxrs/program_center/appstyle/current/update", post(appstyle_current_update))
        .route("/jaxrs/program_center/appstyle/image/application/top", get(appstyle_image_application_top))
        .route("/jaxrs/program_center/appstyle/image/application/top/erase", delete(appstyle_image_application_top_erase))
        .route("/jaxrs/program_center/appstyle/image/launch/logo", get(appstyle_image_launch_logo))
        .route("/jaxrs/program_center/appstyle/image/launch/logo/erase", delete(appstyle_image_launch_logo_erase))
        .route("/jaxrs/program_center/appstyle/image/login/avatar", get(appstyle_image_login_avatar))
        .route("/jaxrs/program_center/appstyle/image/login/avatar/erase", delete(appstyle_image_login_avatar_erase))
        .route("/jaxrs/program_center/appstyle/image/menu/logo/blur", get(appstyle_image_menu_logo_blur))
        .route("/jaxrs/program_center/appstyle/image/menu/logo/blur/erase", delete(appstyle_image_menu_logo_blur_erase))
        .route("/jaxrs/program_center/appstyle/image/menu/logo/focus", get(appstyle_image_menu_logo_focus))
        .route("/jaxrs/program_center/appstyle/image/menu/logo/focus/erase", delete(appstyle_image_menu_logo_focus_erase))
        .route("/jaxrs/program_center/appstyle/image/process/default", get(appstyle_image_process_default))
        .route("/jaxrs/program_center/appstyle/image/process/default/erase", delete(appstyle_image_process_default_erase))
        .route("/jaxrs/program_center/appstyle/image/setup/about/logo", get(appstyle_image_setup_about_logo))
        .route("/jaxrs/program_center/appstyle/image/setup/about/logo/erase", delete(appstyle_image_setup_about_logo_erase))
        .route("/jaxrs/program_center/appstyle/index/portal", get(appstyle_index_portal))
        .route("/jaxrs/program_center/bar/create/mass/from/count", post(bar_create_mass_from_count))
        .route("/jaxrs/program_center/bar/select1/field/field/value/value/count/count", get(bar_select1_field_field_value_value_count_count))
        .route("/jaxrs/program_center/bar/select2/count/count", get(bar_select2_count_count))
        .route("/jaxrs/program_center/bar/select3/field/field/value/value/count/count", get(bar_select3_field_field_value_value_count_count))
        .route("/jaxrs/program_center/bar/select4/field/field/value/value/count/count", get(bar_select4_field_field_value_value_count_count))
        .route("/jaxrs/program_center/captcha/list", get(captcha_list))
        .route("/jaxrs/program_center/captcha/v2/create/width/width/height/height", post(captcha_v2_create_width_width_height_height))
        .route("/jaxrs/program_center/captcha/id/validate/answer/answer", get(captcha_id_validate_answer_answer))
        .route("/jaxrs/program_center/center/applications", get(center_applications))
        .route("/jaxrs/program_center/center/regist/applications", get(center_regist_applications))
        .route("/jaxrs/program_center/center/version", get(center_version))
        .route("/jaxrs/program_center/code/create/mobile/mobile", post(code_create_mobile_mobile))
        .route("/jaxrs/program_center/code/list", get(code_list))
        .route("/jaxrs/program_center/code/list/paging/page/size/size", get(code_list_paging_page_size_size))
        .route("/jaxrs/program_center/code/validate/mobile/mobile/answer/answer", get(code_validate_mobile_mobile_answer_answer))
        .route("/jaxrs/program_center/code/validate/mobile/mobile/answer/answer/cascade", get(code_validate_mobile_mobile_answer_answer_cascade))
        .route("/jaxrs/program_center/collect/code/mobile/mobile", get(collect_code_mobile_mobile))
        .route("/jaxrs/program_center/collect/connect", get(collect_connect))
        .route("/jaxrs/program_center/collect/controllebbs", get(collect_controllebbs))
        .route("/jaxrs/program_center/collect/controllermobile/name/name/mobile/mobile", get(collect_controllermobile_name_name_mobile_mobile))
        .route("/jaxrs/program_center/collect/disconnect", get(collect_disconnect))
        .route("/jaxrs/program_center/collect/login", get(collect_login))
        .route("/jaxrs/program_center/collect/mobile/check/connect", get(collect_mobile_check_connect))
        .route("/jaxrs/program_center/collect/name/name/exist", get(collect_name_name_exist))
        .route("/jaxrs/program_center/collect/name/name/mobile/mobile/code/code", get(collect_name_name_mobile_mobile_code_code))
        .route("/jaxrs/program_center/collect/person", get(collect_person))
        .route("/jaxrs/program_center/collect/resetpassword", get(collect_resetpassword))
        .route("/jaxrs/program_center/collect/sync/area", get(collect_sync_area))
        .route("/jaxrs/program_center/collect/updateUnit", post(collect_updateUnit))
        .route("/jaxrs/program_center/collect/urlMapping", get(collect_urlMapping))
        .route("/jaxrs/program_center/collect/validate", get(collect_validate))
        .route("/jaxrs/program_center/collect/validate/codeanswer", get(collect_validate_codeanswer))
        .route("/jaxrs/program_center/collect/validate/direct", get(collect_validate_direct))
        .route("/jaxrs/program_center/collect/validate/password", get(collect_validate_password))
        .route("/jaxrs/program_center/command/execute", get(command_execute))
        .route("/jaxrs/program_center/command/list/node", get(command_list_node))
        .route("/jaxrs/program_center/config/open/get/disable/export/enable", get(config_open_get_disable_export_enable))
        .route("/jaxrs/program_center/config/centerserver", get(config_centerserver))
        .route("/jaxrs/program_center/config/change/password", get(config_change_password))
        .route("/jaxrs/program_center/config/collect", get(config_collect))
        .route("/jaxrs/program_center/config/license", get(config_license))
        .route("/jaxrs/program_center/config/list", get(config_list))
        .route("/jaxrs/program_center/config/list/application", get(config_list_application))
        .route("/jaxrs/program_center/config/list/dump/data", get(config_list_dump_data))
        .route("/jaxrs/program_center/config/list/dump/data/current/node", get(config_list_dump_data_current_node))
        .route("/jaxrs/program_center/config/list/entity", get(config_list_entity))
        .route("/jaxrs/program_center/config/open", get(config_open))
        .route("/jaxrs/program_center/config/open/run/time/config", get(config_open_run_time_config))
        .route("/jaxrs/program_center/config/person", get(config_person))
        .route("/jaxrs/program_center/config/portal", get(config_portal))
        .route("/jaxrs/program_center/config/proxy", get(config_proxy))
        .route("/jaxrs/program_center/config/save", post(config_save))
        .route("/jaxrs/program_center/config/ternary/management", get(config_ternary_management))
        .route("/jaxrs/program_center/config/token", get(config_token))
        .route("/jaxrs/program_center/datastructure/fileds/all", get(datastructure_fileds_all))
        .route("/jaxrs/program_center/datastructure/modules/all", get(datastructure_modules_all))
        .route("/jaxrs/program_center/datastructure/tables/all", get(datastructure_tables_all))
        .route("/jaxrs/program_center/deploy/list/paging/page/size/size", get(deploy_list_paging_page_size_size))
        .route("/jaxrs/program_center/deploy/server/o2", get(deploy_server_o2))
        .route("/jaxrs/program_center/deploy/server/resource", get(deploy_server_resource))
        .route("/jaxrs/program_center/deploy/web/resource/as/new/asNew", get(deploy_web_resource_as_new_asNew))
        .route("/jaxrs/program_center/deploy/id", get(deploy_id))
        .route("/jaxrs/program_center/designer/search", get(designer_search))
        .route("/jaxrs/program_center/dict/list", get(dict_list))
        .route("/jaxrs/program_center/dict/list/paging/page/size/size", get(dict_list_paging_page_size_size))
        .route("/jaxrs/program_center/dict/dictFlag/data", get(dict_dictFlag_data))
        .route("/jaxrs/program_center/dict/dictFlag/path/data", get(dict_dictFlag_path_data))
        .route("/jaxrs/program_center/dict/dictFlag/path/data/mockdeletetoget", delete(dict_dictFlag_path_data_mockdeletetoget))
        .route("/jaxrs/program_center/dict/dictFlag/path/data/mockputtopost", post(dict_dictFlag_path_data_mockputtopost))
        .route("/jaxrs/program_center/dict/id", get(dict_id))
        .route("/jaxrs/program_center/dingding/get/callback/aes", get(dingding_get_callback_aes))
        .route("/jaxrs/program_center/dingding/pull/sync", get(dingding_pull_sync))
        .route("/jaxrs/program_center/dingding/request/pull/sync", get(dingding_request_pull_sync))
        .route("/jaxrs/program_center/dingding/sync/organization/callback", get(dingding_sync_organization_callback))
        .route("/jaxrs/program_center/dingding/sync/organization/register/callback/enable", get(dingding_sync_organization_register_callback_enable))
        .route("/jaxrs/program_center/distribute/assemble/source/source", get(distribute_assemble_source_source))
        .route("/jaxrs/program_center/distribute/webserver/assemble/source/source", get(distribute_webserver_assemble_source_source))
        .route("/jaxrs/program_center/foo/create/mass/from/count", post(foo_create_mass_from_count))
        .route("/jaxrs/program_center/input/compare", post(input_compare))
        .route("/jaxrs/program_center/input/cover", post(input_cover))
        .route("/jaxrs/program_center/input/create", post(input_create))
        .route("/jaxrs/program_center/input/prepare/cover", post(input_prepare_cover))
        .route("/jaxrs/program_center/input/prepare/create", post(input_prepare_create))
        .route("/jaxrs/program_center/invoke/list/category", get(invoke_list_category))
        .route("/jaxrs/program_center/invoke/list/with/category/category", get(invoke_list_with_category_category))
        .route("/jaxrs/program_center/invoke/token", get(invoke_token))
        .route("/jaxrs/program_center/invoke/flag", get(invoke_flag))
        .route("/jaxrs/program_center/invoke/flag/client/client/token/token/execute", get(invoke_flag_client_client_token_token_execute))
        .route("/jaxrs/program_center/invoke/flag/execute", get(invoke_flag_execute))
        .route("/jaxrs/program_center/invoke/flag/execute/get", get(invoke_flag_execute_get))
        .route("/jaxrs/program_center/invoke/flag/file", get(invoke_flag_file))
        .route("/jaxrs/program_center/jest/clear/cache/source", get(jest_clear_cache_source))
        .route("/jaxrs/program_center/jest/list", get(jest_list))
        .route("/jaxrs/program_center/jest/version", get(jest_version))
        .route("/jaxrs/program_center/market/cloud/unit/is/vip", get(market_cloud_unit_is_vip))
        .route("/jaxrs/program_center/market/install/offline", get(market_install_offline))
        .route("/jaxrs/program_center/market/list/category", get(market_list_category))
        .route("/jaxrs/program_center/market/list/install/log/paging/page/size/size", get(market_list_install_log_paging_page_size_size))
        .route("/jaxrs/program_center/market/list/paging/page/size/size", get(market_list_paging_page_size_size))
        .route("/jaxrs/program_center/market/list/paging/page/size/size/category/category", get(market_list_paging_page_size_size_category_category))
        .route("/jaxrs/program_center/market/list/top/three", get(market_list_top_three))
        .route("/jaxrs/program_center/market/flag", get(market_flag))
        .route("/jaxrs/program_center/market/flag/cover/pic", get(market_flag_cover_pic))
        .route("/jaxrs/program_center/market/flag/install/log", get(market_flag_install_log))
        .route("/jaxrs/program_center/market/flag/install/or/update", post(market_flag_install_or_update))
        .route("/jaxrs/program_center/market/flag/installed/version", get(market_flag_installed_version))
        .route("/jaxrs/program_center/market/flag/uninstall", get(market_flag_uninstall))
        .route("/jaxrs/program_center/market/id/download", get(market_id_download))
        .route("/jaxrs/program_center/module/compare/upload", post(module_compare_upload))
        .route("/jaxrs/program_center/module/list", get(module_list))
        .route("/jaxrs/program_center/module/list/category", get(module_list_category))
        .route("/jaxrs/program_center/module/output", post(module_output))
        .route("/jaxrs/program_center/module/output/structure", post(module_output_structure))
        .route("/jaxrs/program_center/module/output/flag/file", post(module_output_flag_file))
        .route("/jaxrs/program_center/module/remove/structure/id", get(module_remove_structure_id))
        .route("/jaxrs/program_center/module/write/flag", get(module_write_flag))
        .route("/jaxrs/program_center/module/id/compare", get(module_id_compare))
        .route("/jaxrs/program_center/mpweixin/check", get(mpweixin_check))
        .route("/jaxrs/program_center/mpweixin/media/add/forever", post(mpweixin_media_add_forever))
        .route("/jaxrs/program_center/mpweixin/menu/add", post(mpweixin_menu_add))
        .route("/jaxrs/program_center/mpweixin/menu/create/to/weixin", post(mpweixin_menu_create_to_weixin))
        .route("/jaxrs/program_center/mpweixin/menu/delete/id", delete(mpweixin_menu_delete_id))
        .route("/jaxrs/program_center/mpweixin/menu/subscribe", get(mpweixin_menu_subscribe))
        .route("/jaxrs/program_center/mpweixin/menu/update/id", post(mpweixin_menu_update_id))
        .route("/jaxrs/program_center/mpweixin/message/template/send", get(mpweixin_message_template_send))
        .route("/jaxrs/program_center/output/list", post(output_list))
        .route("/jaxrs/program_center/output/appInfoFlag/select", post(output_appInfoFlag_select))
        .route("/jaxrs/program_center/output/flag/select/file", post(output_flag_select_file))
        .route("/jaxrs/program_center/prompterrorlog/count/exceptionclass", get(prompterrorlog_count_exceptionclass))
        .route("/jaxrs/program_center/prompterrorlog/count/loggername", get(prompterrorlog_count_loggername))
        .route("/jaxrs/program_center/prompterrorlog/list/id/next/count", get(prompterrorlog_list_id_next_count))
        .route("/jaxrs/program_center/prompterrorlog/list/id/next/count/date/date", get(prompterrorlog_list_id_next_count_date_date))
        .route("/jaxrs/program_center/prompterrorlog/list/id/next/count/exceptionclass/exceptionClass", get(prompterrorlog_list_id_next_count_exceptionclass_exceptionClass))
        .route("/jaxrs/program_center/prompterrorlog/list/id/next/count/loggername/loggerName", get(prompterrorlog_list_id_next_count_loggername_loggerName))
        .route("/jaxrs/program_center/prompterrorlog/list/id/prev/count", get(prompterrorlog_list_id_prev_count))
        .route("/jaxrs/program_center/prompterrorlog/list/id/prev/count/date/date", get(prompterrorlog_list_id_prev_count_date_date))
        .route("/jaxrs/program_center/prompterrorlog/list/id/prev/count/exceptionclass/exceptionClass", get(prompterrorlog_list_id_prev_count_exceptionclass_exceptionClass))
        .route("/jaxrs/program_center/prompterrorlog/list/id/prev/count/loggername/loggerName", get(prompterrorlog_list_id_prev_count_loggername_loggerName))
        .route("/jaxrs/program_center/prompterrorlog/id", get(prompterrorlog_id))
        .route("/jaxrs/program_center/qiyeweixin/get/callback/aes", get(qiyeweixin_get_callback_aes))
        .route("/jaxrs/program_center/qiyeweixin/pull/sync", get(qiyeweixin_pull_sync))
        .route("/jaxrs/program_center/qiyeweixin/request/pull/sync", get(qiyeweixin_request_pull_sync))
        .route("/jaxrs/program_center/qiyeweixin/send/getprivateinfo/message", get(qiyeweixin_send_getprivateinfo_message))
        .route("/jaxrs/program_center/schedule/list/schedule", get(schedule_list_schedule))
        .route("/jaxrs/program_center/schedule/list/schedulelocal", get(schedule_list_schedulelocal))
        .route("/jaxrs/program_center/schedule/list/schedulelog/application/application", get(schedule_list_schedulelog_application_application))
        .route("/jaxrs/program_center/schedule/report", get(schedule_report))
        .route("/jaxrs/program_center/schedule/schedule/fire", get(schedule_schedule_fire))
        .route("/jaxrs/program_center/script/list", get(script_list))
        .route("/jaxrs/program_center/script/list/paging/page/size/size", get(script_list_paging_page_size_size))
        .route("/jaxrs/program_center/script/name/name", get(script_name_name))
        .route("/jaxrs/program_center/script/name/name/imported", get(script_name_name_imported))
        .route("/jaxrs/program_center/script/flag", get(script_flag))
        .route("/jaxrs/program_center/script/id", get(script_id))
        .route("/jaxrs/program_center/test/test1", get(test_test1))
        .route("/jaxrs/program_center/test/test2", get(test_test2))
        .route("/jaxrs/program_center/tokenthreshold/update", post(tokenthreshold_update))
        .route("/jaxrs/program_center/unexpectederrorlog/list/id/next/count", get(unexpectederrorlog_list_id_next_count))
        .route("/jaxrs/program_center/unexpectederrorlog/list/id/next/count/date/date", get(unexpectederrorlog_list_id_next_count_date_date))
        .route("/jaxrs/program_center/unexpectederrorlog/list/id/prev/count", get(unexpectederrorlog_list_id_prev_count))
        .route("/jaxrs/program_center/unexpectederrorlog/list/id/prev/count/date/date", get(unexpectederrorlog_list_id_prev_count_date_date))
        .route("/jaxrs/program_center/unexpectederrorlog/id", get(unexpectederrorlog_id))
        .route("/jaxrs/program_center/validation/meta", get(validation_meta))
        .route("/jaxrs/program_center/validation/scripting/benchmark", get(validation_scripting_benchmark))
        .route("/jaxrs/program_center/validation/timeout/timeout", get(validation_timeout_timeout))
        .route("/jaxrs/program_center/zhengwudingding/pull/sync", get(zhengwudingding_pull_sync))
        .route("/jaxrs/program_center/zhengwudingding/regist/callback", get(zhengwudingding_regist_callback))
        .route("/jaxrs/program_center/zhengwudingding/sync/organization/callback", get(zhengwudingding_sync_organization_callback))
        .route("/jaxrs/program_center/agent/save/{id}", put(agent_save))
        .route("/jaxrs/program_center/application/save/{id}", put(application_save))
        .route("/jaxrs/program_center/appstyle/current/update", put(appstyle_current_update))
        .route("/jaxrs/program_center/collect/remove", delete(collect_remove))
        .route("/jaxrs/program_center/collect/updateUnit", put(collect_updateUnit))
        .route("/jaxrs/program_center/config/save", put(config_save))
        .route("/jaxrs/program_center/market/flag/install/or/update", put(market_flag_install_or_update))
        .route("/jaxrs/program_center/module/remove/structure/id", delete(module_remove_structure_id))
        .route("/jaxrs/program_center/mpweixin/menu/update/id", put(mpweixin_menu_update_id))
        .route("/jaxrs/program_center/tokenthreshold/update", put(tokenthreshold_update))
.layer(Extension(pool))
}
