/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.meeting.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.meeting.core.entity.MeetingConfig.class)
public class MeetingConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MeetingConfig,String> id;
    public static volatile SingularAttribute<MeetingConfig,String> name;
    public static volatile SingularAttribute<MeetingConfig,MeetingConfigProperties> properties;
}
