/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceDingtalkDetail.class)
public class AttendanceDingtalkDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> baseCheckTime;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> checkType;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> ddId;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> groupId;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> id;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> locationResult;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> o2Unit;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> o2User;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> planId;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> recordId;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> sourceType;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> timeResult;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> userCheckTime;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Date> userCheckTimeDate;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,String> userId;
    public static volatile SingularAttribute<AttendanceDingtalkDetail,Long> workDate;
}
