/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceStatisticRequireLog.class)
public class AttendanceStatisticRequireLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> description;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> id;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> processStatus;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,Date> processTime;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticDay;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticKey;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticMonth;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticName;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticType;
    public static volatile SingularAttribute<AttendanceStatisticRequireLog,String> statisticYear;
}
