/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceEmployeeConfig.class)
public class AttendanceEmployeeConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> configType;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> empInTopUnitTime;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> employeeName;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> employeeNumber;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> id;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> topUnitName;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> topUnitOu;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> unitName;
    public static volatile SingularAttribute<AttendanceEmployeeConfig,String> unitOu;
}
