/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceAdmin.class)
public class AttendanceAdmin_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceAdmin,String> admin;
    public static volatile SingularAttribute<AttendanceAdmin,String> adminLevel;
    public static volatile SingularAttribute<AttendanceAdmin,String> adminName;
    public static volatile SingularAttribute<AttendanceAdmin,String> id;
    public static volatile SingularAttribute<AttendanceAdmin,String> unitName;
    public static volatile SingularAttribute<AttendanceAdmin,String> unitOu;
}
