/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.DingdingQywxSyncRecord.class)
public class DingdingQywxSyncRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DingdingQywxSyncRecord,Long> dateFrom;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,Long> dateTo;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,Date> endTime;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,String> exceptionMessage;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,String> id;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,Date> startTime;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,String> status;
    public static volatile SingularAttribute<DingdingQywxSyncRecord,String> type;
}
