/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Long;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.StatisticDingdingUnitForDay.class)
public class StatisticDingdingUnitForDay_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> absenteeismTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,String> id;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> lateTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> leaveEarlyTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> notSignedCount;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,String> o2Unit;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> offDutyTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> onDutyTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> resultNormal;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> seriousLateTimes;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,String> statisticDate;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,String> statisticMonth;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,String> statisticYear;
    public static volatile SingularAttribute<StatisticDingdingUnitForDay,Long> workDayCount;
}
