/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Long;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.StatisticQywxPersonForMonth.class)
public class StatisticQywxPersonForMonth_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> absenteeismTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,String> id;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> lateTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> leaveEarlyTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> notSignedCount;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,String> o2Unit;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,String> o2User;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> offDutyTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> onDutyTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> outsideDutyTimes;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> resultNormal;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,String> statisticMonth;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,String> statisticYear;
    public static volatile SingularAttribute<StatisticQywxPersonForMonth,Long> workDayCount;
}
