[package]
name = "search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
deadpool-postgres.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

shared = { path = "../shared" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tower.workspace = true
