use axum::{
    routing::{get, post},
    Router,
};
use deadpool_postgres::Pool;

pub fn general_assemble_control_routes(pool: Pool) -> Router {
    Router::new()
        .route("/jaxrs/general/assemble/control/status", get(crate::get_general_control_status))
        .route("/jaxrs/general/assemble/control/status/update", post(crate::update_general_control_status))
        .route("/jaxrs/general/assemble/control/permissions/{module}", get(crate::get_module_permissions))
        .route("/jaxrs/general/assemble/control/attendscope/list", get(crate::attendscope_list))
        .route("/jaxrs/general/assemble/control/attendscope/{id}", get(crate::attendscope_get))
        .route("/jaxrs/general/assemble/control/attendscope/create", post(crate::attendscope_create))
        .route("/jaxrs/general/assemble/control/attendscope/save/{id}", post(crate::attendscope_save))
        .route("/jaxrs/general/assemble/control/attendscope/delete/{id}", post(crate::attendscope_delete))
        .route("/jaxrs/general/assemble/control/area/list", get(crate::area_list))
        .route("/jaxrs/general/assemble/control/area/create", post(crate::area_create))
        .route("/jaxrs/general/assemble/control/area/{id}", get(crate::area_get))
        .route("/jaxrs/general/assemble/control/area/update/{id}", post(crate::area_update))
        .route("/jaxrs/general/assemble/control/area/delete/{id}", post(crate::area_delete))
        .route("/jaxrs/general/assemble/control/area/list/province/{province}", get(crate::area_list_province_province))
        .route("/jaxrs/general/assemble/control/area/list/province/{province}/city/{city}", get(crate::area_list_province_province_city_city))
        .route("/jaxrs/general/assemble/control/area/list/province/{province}/city/{city}/district/{district}", get(crate::area_list_province_province_city_city_district_district))
        .route("/jaxrs/general/assemble/control/ecnet/check", get(crate::ecnet_check))
        .route("/jaxrs/general/assemble/control/excel/{\"excelName\"}", get(crate::excel_excelName_excelName))
        .route("/jaxrs/general/assemble/control/excel/{\"excelName\"}/sheetList", get(crate::excel_excelName_excelName_sheetList))
        .route("/jaxrs/general/assemble/control/excel/result/flag/{flag}", get(crate::excel_result_flag))
        .route("/jaxrs/general/assemble/control/excel/upload", post(crate::excel_upload))
        .route("/jaxrs/general/assemble/control/excel/upload/with/url", post(crate::excel_upload_with_url))
        .route("/jaxrs/general/assemble/control/generalfile/download/flag/{flag}", get(crate::generalfile_download_flag_flag))
        .route("/jaxrs/general/assemble/control/generalfile/flag/{flag}", get(crate::generalfile_flag_flag))
        .route("/jaxrs/general/assemble/control/generalfile/flag/{flag}/binary/base64", get(crate::generalfile_flag_flag_binary_base64))
        .route("/jaxrs/general/assemble/control/invoice/create", post(crate::invoice_create))
        .route("/jaxrs/general/assemble/control/invoice/delete/{id}", post(crate::invoice_delete_id))
        .route("/jaxrs/general/assemble/control/invoice/download/flag/{flag}", get(crate::invoice_download_flag_flag))
        .route("/jaxrs/general/assemble/control/invoice/get/{id}", get(crate::invoice_get_id))
        .route("/jaxrs/general/assemble/control/invoice/list/paging/{page}/size/{size}", get(crate::invoice_list_paging_page_size_size))
        .route("/jaxrs/general/assemble/control/invoice/update/apply/status/{id}", post(crate::invoice_update_apply_status_id))
        .route("/jaxrs/general/assemble/control/invoice/update/{id}", post(crate::invoice_update_id))
        .route("/jaxrs/general/assemble/control/invoice/upload", post(crate::invoice_upload))
        .route("/jaxrs/general/assemble/control/invoice/upload/for/create", post(crate::invoice_upload_for_create))
        .route("/jaxrs/general/assemble/control/invoice/upload/with/url", post(crate::invoice_upload_with_url))
        .route("/jaxrs/general/assemble/control/office/html/to/word", post(crate::office_html_to_word))
        .route("/jaxrs/general/assemble/control/office/html/to/word/result/flag/{flag}", get(crate::office_html_to_word_result_flag))
        .route("/jaxrs/general/assemble/control/qrcode/width/{width}/height/{height}/text/{text}", post(crate::qrcode_width_width_height_height_text_text))
        .route("/jaxrs/general/assemble/control/qrcode/list", get(crate::qrcode_list))
        .route("/jaxrs/general/assemble/control/qrcode/{id}", get(crate::qrcode_get))
        .route("/jaxrs/general/assemble/control/qrcode/delete/{id}", post(crate::qrcode_delete))
        .route("/jaxrs/general/assemble/control/securityclearance/enable", post(crate::securityclearance_enable))
        .route("/jaxrs/general/assemble/control/securityclearance/object", get(crate::securityclearance_object))
        .route("/jaxrs/general/assemble/control/securityclearance/subject", get(crate::securityclearance_subject))
        .route("/jaxrs/general/assemble/control/securityclearance/system", get(crate::securityclearance_system))
        .route("/jaxrs/general/assemble/control/securityclearance/create", post(crate::securityclearance_create))
        .route("/jaxrs/general/assemble/control/securityclearance/{id}", get(crate::securityclearance_get))
        .route("/jaxrs/general/assemble/control/securityclearance/update/{id}", post(crate::securityclearance_update))
        .route("/jaxrs/general/assemble/control/securityclearance/delete/{id}", post(crate::securityclearance_delete))
        .route("/jaxrs/general/assemble/control/upgrade/2021090901", get(crate::upgrade_2021090901))
        .route("/jaxrs/general/assemble/control/upgrade/2021090902", get(crate::upgrade_2021090902))
        .route("/jaxrs/general/assemble/control/worktime/between/holiday/count/start/{startDate}/end/{endDate}", get(crate::worktime_betweenholidaycount_start_startDate_end_endDate))
        .route("/jaxrs/general/assemble/control/worktime/between/minutes/start/{start}/end/{end}", get(crate::worktime_betweenminutes_start_start_end_end))
        .route("/jaxrs/general/assemble/control/worktime/forward/days/start/{start}/days/{days}", get(crate::worktime_forwarddays_start_start_days_days))
        .route("/jaxrs/general/assemble/control/worktime/forward/minutes/start/{start}/minutes/{minutes}", get(crate::worktime_forwardminutes_start_start_minutes_minutes))
        .route("/jaxrs/general/assemble/control/worktime/indefined/holiday/{date}", get(crate::worktime_indefinedholiday_date))
        .route("/jaxrs/general/assemble/control/worktime/indefined/workday/{date}", get(crate::worktime_indefinedworkday_date))
        .route("/jaxrs/general/assemble/control/worktime/is/holiday/{date}", get(crate::worktime_isholiday_date))
        .route("/jaxrs/general/assemble/control/worktime/is/workday/{date}", get(crate::worktime_isworkday_date))
        .route("/jaxrs/general/assemble/control/worktime/is/worktime/{date}", get(crate::worktime_isworktime_date))
        .route("/jaxrs/general/assemble/control/worktime/minutes/of/workday", get(crate::worktime_minutesofworkday))
        .layer(axum::Extension(pool))
}
