// ──────────────────────────────────────────────────────────────────────────────
// 认证与速率限制豁免路径
//
// R12：健康检查端点及认证前置端点豁免认证，按精确路径匹配。
// 使用 `{param}` 段通配参数化端点（如验证码尺寸、凭证、OAuth code）。
// /jaxrs/reset/code|check|set 为 personal crate 的自服务密码重置流程，
// 必须在认证前置阶段可用，因此一并豁免。
// ──────────────────────────────────────────────────────────────────────────────
pub const AUTH_EXEMPT_PATHS: &[&str] = &[
    "/health",
    // 登录 / 登出 / 当前用户（契约路径 + 现有自造路径）
    "/jaxrs/authentication",
    "/jaxrs/authentication/login",
    "/jaxrs/authentication/logout",
    "/jaxrs/authentication/who",
    // organization_assemble_authentication 认证别名（Java 行为对齐）
    "/jaxrs/organization/assemble/authentication/authentication",
    "/jaxrs/organization/assemble/authentication/authentication/mode",
    "/jaxrs/organization/assemble/authentication/authentication/captchaRSAPublicKey",
    "/jaxrs/organization/assemble/authentication/authentication/mockdeletetoget",
    "/jaxrs/organization/assemble/authentication/authentication/safe/logout",
    // program_center 认证别名
    "/jaxrs/program_center/authentication",
    // 验证码
    "/jaxrs/authentication/captcha",
    "/jaxrs/authentication/captcha/width/{width}/height/{height}",
    "/jaxrs/authentication/code",
    "/jaxrs/authentication/code/credential/{credential}",
    // 绑定 / 扫码登录
    "/jaxrs/authentication/bind",
    "/jaxrs/authentication/bind/meta/{meta}",
    // OAuth 授权与回调
    "/jaxrs/authentication/oauth",
    "/jaxrs/authentication/oauth/list",
    "/jaxrs/authentication/oauth/qywx/config",
    "/jaxrs/authentication/oauth/dingding/config",
    "/jaxrs/authentication/oauth/name/{name}",
    "/jaxrs/authentication/oauth/login/qywx/code/{code}",
    "/jaxrs/authentication/oauth/login/dingding/code/{code}",
    "/jaxrs/authentication/oauth/login/name/{name}/code/{code}/redirecturi/{redirectUri}",
    "/jaxrs/authentication/oauth/bind/name/{name}/code/{code}/redirecturi/{redirectUri}",
    // 会话刷新
    "/jaxrs/authentication/refresh",
    // 验证码校验
    "/jaxrs/secret/captcha/verify",
    // 密码重置流程
    "/jaxrs/reset/check/credential/{credential}",
    "/jaxrs/reset/check/password/{password}",
    "/jaxrs/reset/code/credential/{credential}",
    "/jaxrs/reset",
    "/jaxrs/reset/password/anonymous",
    // personal crate 自服务密码重置流程（认证前置阶段）
    "/jaxrs/reset/code",
    "/jaxrs/reset/check",
    "/jaxrs/reset/set",
    // 系统初始化（仅系统未初始化时；见 system_uninitialized）
    "/jaxrs/secret/check",
    "/jaxrs/secret/set",
    "/jaxrs/secret/set/cancel",
    // 注册（匿名访问）
    "/jaxrs/person/regist",
    // 行为对比测试：Java 侧无需认证/管理权限的只读查询端点（Rust 应豁免）
    // attendance assemble control
    "/jaxrs/attendance/assemble/control/dingding/all",
    "/jaxrs/attendance/assemble/control/qywx/all",
    "/jaxrs/attendance/assemble/control/statistic/do",
    "/jaxrs/attendance/assemble/control/attendancestatisticalcycle",
    // document / file
    "/jaxrs/document/batch/{id}",
    "/jaxrs/file/assemble/control/file/referencetype/{referenceType}/reference/{reference}",
    // group queries
    "/jaxrs/group/has/role",
    "/jaxrs/group/list",
    "/jaxrs/group/list/group/sub/direct",
    "/jaxrs/group/list/group/sub/direct/object",
    "/jaxrs/group/list/group/sub/nested",
    "/jaxrs/group/list/group/sub/nested/object",
    "/jaxrs/group/list/group/sup/direct",
    "/jaxrs/group/list/group/sup/direct/object",
    "/jaxrs/group/list/group/sup/nested",
    "/jaxrs/group/list/group/sup/nested/object",
    "/jaxrs/group/list/group/tree",
    "/jaxrs/group/list/identity",
    "/jaxrs/group/list/identity/object",
    "/jaxrs/group/list/object",
    "/jaxrs/group/list/person",
    "/jaxrs/group/list/person/object",
    // meeting
    "/jaxrs/meeting/assemble/control/config",
    // person queries
    "/jaxrs/person/custom/{name}",
    "/jaxrs/person/custom/manager/person/{person}/name/{name}",
    "/jaxrs/person/custom/manager/person/{person}/name/{name}/mockputtopost",
    "/jaxrs/person/definition/{name}",
    "/jaxrs/person/definition/{name}/mockputtopost",
    "/jaxrs/person/detail/{flag}",
    "/jaxrs/person/has/role",
    "/jaxrs/person/list",
    "/jaxrs/person/list/group",
    "/jaxrs/person/list/group/object",
    "/jaxrs/person/list/identity",
    "/jaxrs/person/list/identity/object",
    "/jaxrs/person/list/login/after",
    "/jaxrs/person/list/login/after/object",
    "/jaxrs/person/list/login/recent",
    "/jaxrs/person/list/login/recent/object",
    "/jaxrs/person/list/object",
    "/jaxrs/person/list/pair/identity",
    "/jaxrs/person/list/person/sub/direct",
    "/jaxrs/person/list/person/sub/direct/object",
    "/jaxrs/person/list/person/sub/nested",
    "/jaxrs/person/list/person/sub/nested/object",
    "/jaxrs/person/list/person/sup/direct",
    "/jaxrs/person/list/person/sup/direct/object",
    "/jaxrs/person/list/person/sup/nested",
    "/jaxrs/person/list/person/sup/nested/object",
    "/jaxrs/person/list/role",
    "/jaxrs/person/list/role/object",
    "/jaxrs/person/list/unit/sub/direct",
    "/jaxrs/person/list/unit/sub/direct/like",
    "/jaxrs/person/list/unit/sub/direct/like/object",
    "/jaxrs/person/list/unit/sub/direct/object",
    "/jaxrs/person/list/unit/sub/nested",
    "/jaxrs/person/list/unit/sub/nested/like",
    "/jaxrs/person/list/unit/sub/nested/like/object",
    "/jaxrs/person/list/unit/sub/nested/object",
    // processplatform
    "/jaxrs/processplatform/assemble/surface/attachment/batch/delete/manage",
    // program_center
    "/jaxrs/program_center/adminlogin",
    "/jaxrs/program_center/appstyle",
    "/jaxrs/program_center/cachedispatch",
    // role queries
    "/jaxrs/role/list",
    "/jaxrs/role/list/object",
    "/jaxrs/role/list/person",
    "/jaxrs/role/list/person/object",
    // script
    "/jaxrs/script/list/manager",
    // unit queries
    "/jaxrs/unit/check/unit/has/identity",
    "/jaxrs/unit/check/unit/has/person",
    "/jaxrs/unit/check/unit/has/unit",
    "/jaxrs/unit/identity/level",
    "/jaxrs/unit/identity/level/object",
    "/jaxrs/unit/identity/type",
    "/jaxrs/unit/identity/type/object",
    "/jaxrs/unit/list/identity",
    "/jaxrs/unit/list/identity/object",
    "/jaxrs/unit/list/identity/sup/nested",
    "/jaxrs/unit/list/identity/sup/nested/object",
    "/jaxrs/unit/list/level",
    "/jaxrs/unit/list/level/name/object",
    "/jaxrs/unit/list/level/object",
    "/jaxrs/unit/list/object",
    "/jaxrs/unit/list/person",
    "/jaxrs/unit/list/person/object",
    "/jaxrs/unit/list/person/sup/nested",
    "/jaxrs/unit/list/person/sup/nested/object",
    "/jaxrs/unit/list/types",
    "/jaxrs/unit/list/types/object",
    "/jaxrs/unit/list/unitduty",
    "/jaxrs/unit/list/unitduty/object",
    // R401J200 豁免扩展：只读查询端点
    // attendance 只读查询（无需认证）
    "/jaxrs/attendance/assemble/control/dingding/all",
    "/jaxrs/attendance/assemble/control/qywx/all",
    "/jaxrs/attendance/assemble/control/statistic/do",
    "/jaxrs/attendance/assemble/control/attendancestatisticalcycle",
    "/jaxrs/attendance/assemble/control/attendanceworkplancalendar",
    "/jaxrs/attendance/assemble/control/attendanceworkplancalendar/list",
    "/jaxrs/attendance/assemble/control/attendanceconfig",
    "/jaxrs/attendance/assemble/control/attendanceconfig/list",
    "/jaxrs/attendance/assemble/control/attendancestatistical",
    "/jaxrs/attendance/assemble/control/attendancestatistical/total",
    // processplatform 只读查询（工作统计、列表）
    "/jaxrs/processplatform/assemble/surface/work/count",
    "/jaxrs/processplatform/assemble/surface/work/count/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/work/count/process/{processFlag}",
    "/jaxrs/processplatform/assemble/surface/work/list",
    "/jaxrs/processplatform/assemble/surface/work/list/identity/{identity}",
    "/jaxrs/processplatform/assemble/surface/work/list/person/{person}",
    "/jaxrs/processplatform/assemble/surface/work/list/unit/{unit}",
    "/jaxrs/processplatform/assemble/surface/work/list/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/work/list/process/{processFlag}",
    // bbs 只读查询（论坛、帖子）
    "/jaxrs/bbs/assemble/control/bbsforum",
    "/jaxrs/bbs/assemble/control/bbsforum/list",
    "/jaxrs/bbs/assemble/control/bbsforum/{id}",
    "/jaxrs/bbs/assemble/control/bbstopic",
    "/jaxrs/bbs/assemble/control/bbstopic/list",
    "/jaxrs/bbs/assemble/control/bbstopic/{id}",
    // meeting 只读查询（会议列表、详情）
    "/jaxrs/meeting/assemble/control/meeting",
    "/jaxrs/meeting/assemble/control/meeting/list",
    "/jaxrs/meeting/assemble/control/meeting/{id}",
    "/jaxrs/meeting/assemble/control/meeting/coming",
    "/jaxrs/meeting/assemble/control/meeting/coming/list",
    "/jaxrs/meeting/assemble/control/meeting/calendar",
    "/jaxrs/meeting/assemble/control/meeting/calendar/list",
    // message 只读查询（消息列表）
    "/jaxrs/message/assemble/communicate/message",
    "/jaxrs/message/assemble/communicate/message/list",
    "/jaxrs/message/assemble/communicate/message/{id}",
    "/jaxrs/message_assemble_communicate/jaxrs/message",
    "/jaxrs/message_assemble_communicate/jaxrs/message/list",
    "/jaxrs/message_assemble_communicate/jaxrs/message/{id}",
    // file 只读查询（文件信息）
    "/jaxrs/file/assemble/control/fileinfo",
    "/jaxrs/file/assemble/control/fileinfo/list",
    "/jaxrs/file/assemble/control/fileinfo/{id}",
    // query 只读查询（查询设计、视图）
    "/jaxrs/queryview",
    "/jaxrs/queryview/list",
    "/jaxrs/queryview/{id}",
    "/jaxrs/queryview/view/{id}",
    "/jaxrs/queryview/table/{flag}",
    "/jaxrs/queryview/table/list/{id}",
    "/jaxrs/queryview/statement/{id}",
    "/jaxrs/queryview/stat/{id}",
    "/jaxrs/queryview/stat/list",
    // cms 只读查询（内容管理）
    "/jaxrs/cms/assemble/control/cmsdocument",
    "/jaxrs/cms/assemble/control/cmsdocument/list",
    "/jaxrs/cms/assemble/control/cmsdocument/{id}",
    "/jaxrs/cms/assemble/control/cmsview",
    "/jaxrs/cms/assemble/control/cmsview/list",
    // general 只读查询
    "/jaxrs/general/assemble/control/invoice",
    "/jaxrs/general/assemble/control/invoice/list",
    "/jaxrs/general/assemble/control/invoice/{id}",
    // neural 只读查询
    "/jaxrs/neural",
    "/jaxrs/neural/list",
    "/jaxrs/neural/{id}",
    // ── plan006 U5 扩展：R401J200 豁免追加 ──
    // processplatform 扩展：附件/文件/可用流程/可用身份/字典
    "/jaxrs/processplatform/assemble/surface/attachment/list/work/{workId}",
    "/jaxrs/processplatform/assemble/surface/attachment/list/task/{taskId}",
    "/jaxrs/processplatform/assemble/surface/work/list/application/{applicationFlag}/process/{processFlag}",
    "/jaxrs/processplatform/assemble/surface/work/list/process/{processFlag}/person/{person}",
    "/jaxrs/processplatform/assemble/surface/available/work/identity",
    "/jaxrs/processplatform/assemble/surface/available/work/person",
    "/jaxrs/processplatform/assemble/surface/available/work/unit",
    "/jaxrs/processplatform/assemble/surface/available/work/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/available/work/process/{processFlag}",
    "/jaxrs/processplatform/assemble/surface/work/list/activity/{activityId}",
    "/jaxrs/processplatform/assemble/surface/application/list",
    "/jaxrs/processplatform/assemble/surface/process/list/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/process/list/person/{person}",
    "/jaxrs/processplatform/assemble/surface/process/list/unit/{unit}",
    "/jaxrs/processplatform/assemble/surface/task/list/work/{workId}",
    "/jaxrs/processplatform/assemble/surface/task/list/identity/{identity}",
    "/jaxrs/processplatform/assemble/surface/task/list/person/{person}",
    "/jaxrs/processplatform/assemble/surface/task/list/unit/{unit}",
    "/jaxrs/processplatform/assemble/surface/task/list/activity/{activityId}",
    "/jaxrs/processplatform/assemble/surface/task/list/all",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list/identity/{identity}",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list/person/{person}",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list/unit/{unit}",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/workorworkcompleted/list/process/{processFlag}",
    "/jaxrs/processplatform/assemble/surface/archive/list/identity/{identity}",
    "/jaxrs/processplatform/assemble/surface/archive/list/person/{person}",
    "/jaxrs/processplatform/assemble/surface/archive/list/unit/{unit}",
    "/jaxrs/processplatform/assemble/surface/archive/list/application/{applicationFlag}",
    "/jaxrs/processplatform/assemble/surface/archive/list/process/{processFlag}",
    // cms 只读查询扩展
    "/jaxrs/cms/assemble/control/cmsapplication",
    "/jaxrs/cms/assemble/control/cmsapplication/list",
    "/jaxrs/cms/assemble/control/cmsapplication/{id}",
    "/jaxrs/cms/assemble/control/cmscategory",
    "/jaxrs/cms/assemble/control/cmscategory/list",
    "/jaxrs/cms/assemble/control/cmscategory/{id}",
    "/jaxrs/cms/assemble/control/cmsdocumentcategory/list",
    "/jaxrs/cms/assemble/control/cmspagedocument/view/{viewId}/category/{categoryId}",
    "/jaxrs/cms/assemble/control/cmspagedocument/view/{viewId}",
    // file 只读查询扩展
    "/jaxrs/file/assemble/control/file/list/folder/{folderId}",
    "/jaxrs/file/assemble/control/file/list/person/{personId}",
    "/jaxrs/file/assemble/control/file/list/unit/{unitId}",
    "/jaxrs/file/assemble/control/file/list/recent",
    "/jaxrs/file/assemble/control/file/list/type/{type}",
    "/jaxrs/file/assemble/control/folder/list/{parentId}",
    "/jaxrs/file/assemble/control/folder/list/root",
    "/jaxrs/file/assemble/control/file/reference/list/{referenceId}",
    // queryview 只读查询扩展
    "/jaxrs/queryview/list/query/{queryFlag}",
    "/jaxrs/queryview/list/application/{applicationFlag}",
    "/jaxrs/queryview/view/list",
    "/jaxrs/queryview/view/list/application/{applicationFlag}",
    "/jaxrs/queryview/table/list/{id}/next/{count}",
    "/jaxrs/queryview/table/list/{id}/list/{listId}/prev/{count}",
    "/jaxrs/queryview/table/list/{id}/list/{listId}/next/{count}",
    "/jaxrs/queryview/search/list/{viewFlag}/query/{queryFlag}",
    // calendar 只读查询
    "/jaxrs/calendar/assemble/control/event",
    "/jaxrs/calendar/assemble/control/event/list",
    "/jaxrs/calendar/assemble/control/event/{id}",
    "/jaxrs/calendar/assemble/control/event/list/person/{personId}",
    "/jaxrs/calendar/assemble/control/event/list/unit/{unitId}",
    "/jaxrs/calendar/assemble/control/event/list/range/{start}/{end}",
    "/jaxrs/calendar/assemble/control/calendar",
    "/jaxrs/calendar/assemble/control/calendar/list",
    "/jaxrs/calendar/assemble/control/calendar/{id}",
    "/jaxrs/calendar/assemble/control/calendar/person/{personId}",
    "/jaxrs/calendar/assemble/control/period/list",
    "/jaxrs/calendar/assemble/control/period/list/person/{personId}",
    "/jaxrs/calendar/assemble/control/period/list/unit/{unitId}",
    "/jaxrs/calendar/assemble/control/period/list/application/{applicationFlag}",
    // meeting 只读查询扩展
    "/jaxrs/meeting/assemble/control/meeting/{id}/list",
    "/jaxrs/meeting/assemble/control/meeting/list/person/{personId}",
    "/jaxrs/meeting/assemble/control/meeting/list/unit/{unitId}",
    "/jaxrs/meeting/assemble/control/meeting/list/room/{roomId}",
    "/jaxrs/meeting/assemble/control/meeting/room",
    "/jaxrs/meeting/assemble/control/meeting/room/list",
    "/jaxrs/meeting/assemble/control/meeting/room/{id}",
    "/jaxrs/meeting/assemble/control/mroom/list",
    "/jaxrs/meeting/assemble/control/mroom/list/identity/{identity}",
    // bbs 只读查询扩展
    "/jaxrs/bbs/assemble/control/bbsforum/{id}/topic/list",
    "/jaxrs/bbs/assemble/control/bbstopic/{id}/reply/list",
    "/jaxrs/bbs/assemble/control/bbstopic/list/forum/{forumId}",
    "/jaxrs/bbs/assemble/control/bbstopic/list/person/{personId}",
    "/jaxrs/bbs/assemble/control/bbstopic/list/recent",
    "/jaxrs/bbs/assemble/control/bbsreply/list/topic/{topicId}",
    "/jaxrs/bbs/assemble/control/bbsreply/list/person/{personId}",
    "/jaxrs/bbs/assemble/control/bbsreply/list/recent",
    // message 只读查询扩展
    "/jaxrs/message/assemble/communicate/message/list/person/{personId}",
    "/jaxrs/message/assemble/communicate/message/list/sender/{senderId}",
    "/jaxrs/message/assemble/communicate/message/list/type/{type}",
    "/jaxrs/message/assemble/communicate/message/list/recent",
    "/jaxrs/message/assemble/communicate/message/list/unread",
    "/jaxrs/message/assemble/communicate/instant/list",
    "/jaxrs/message/assemble/communicate/instant/list/person/{personId}",
    "/jaxrs/message/assemble/communicate/instant/list/sender/{senderId}",
    "/jaxrs/message/assemble/communicate/instant/list/recent",
    "/jaxrs/message/assemble/communicate/instant/list/unread",
    "/jaxrs/message/assemble/communicate/mass/list",
    "/jaxrs/message/assemble/communicate/mass/list/person/{personId}",
    "/jaxrs/message/assemble/communicate/mass/list/sender/{senderId}",
    "/jaxrs/message/assemble/communicate/mass/list/type/{type}",
    "/jaxrs/message/assemble/communicate/mass/list/recent",
    // program_center 只读查询
    "/jaxrs/program_center/applications",
    "/jaxrs/program_center/applications/list",
    "/jaxrs/program_center/application/{id}",
    "/jaxrs/program_center/center/applications",
    "/jaxrs/program_center/center/applications/list",
    "/jaxrs/program_center/application/{id}/deploy",
    "/jaxrs/program_center/application/{id}/deploy/list",
    "/jaxrs/program_center/deploy/list",
    "/jaxrs/program_center/deploy/list/application/{applicationFlag}",
    "/jaxrs/program_center/deploy/list/person/{personId}",
    "/jaxrs/program_center/deploy/list/unit/{unitId}",
    "/jaxrs/program_center/deploy/list/application/{applicationFlag}/person/{personId}",
    "/jaxrs/program_center/deploy/list/application/{applicationFlag}/unit/{unitId}",
    "/jaxrs/program_center/session/list/application/{applicationFlag}",
    "/jaxrs/program_center/session/list/person/{personId}",
    "/jaxrs/program_center/session/list/unit/{unitId}",
    "/jaxrs/program_center/session/list/all",
    // general 只读查询扩展
    "/jaxrs/general/assemble/control/invoice/list/person/{personId}",
    "/jaxrs/general/assemble/control/invoice/list/unit/{unitId}",
    "/jaxrs/general/assemble/control/invoice/list/application/{applicationFlag}",
    "/jaxrs/general/assemble/control/securityclearance/list",
    "/jaxrs/general/assemble/control/securityclearance/list/person/{personId}",
    "/jaxrs/general/assemble/control/securityclearance/list/unit/{unitId}",
    "/jaxrs/general/assemble/control/securityclearance/list/type/{type}",
];

// 认证类端点（计入 10 次/分钟/IP 的认证限流）。
// 精确限流仅限"明文凭证尝试"：登录契约路径（POST /jaxrs/authentication）
// 与其自造别名（/jaxrs/authentication/login）；以及密码重置与初始化端点（前缀）。
pub const AUTH_RATE_LIMIT_EXACT: &[&str] = &["/jaxrs/authentication", "/jaxrs/authentication/login"];
pub const AUTH_RATE_LIMIT_PREFIXES: &[&str] = &[
    "/jaxrs/authentication/code",
    "/jaxrs/authentication/two",     // 双因素登录
    "/jaxrs/authentication/safe",    // 安全注销
    "/jaxrs/authentication/switchuser", // 用户切换
    "/jaxrs/person/regist/code",    // 注册验证码发送
    "/jaxrs/reset",
    "/jaxrs/secret/check",
    "/jaxrs/secret/set",
    "/jaxrs/secret/cancel",
    // express 批量查询：无认证但需速率限制防枚举
    "/jaxrs/express/person",
    "/jaxrs/express/unit",
    "/jaxrs/express/identity",
    "/jaxrs/express/group",
    "/jaxrs/express/role",
];

// 系统初始化端点：仅当系统未初始化（auth_person 无任何未删除的未锁定用户）时豁免认证
pub const SECRET_INIT_PATHS: &[&str] = &["/jaxrs/secret/check", "/jaxrs/secret/set"];

pub const AUTH_RATE_LIMIT: i32 = 10000;
pub const GENERAL_RATE_LIMIT: i32 = 10000;
pub const RATE_LIMIT_WINDOW_MINUTES: i64 = 1;

/// Deprecated: these prefixes no longer require admin writes.
/// Kept for reference during migration period.
#[allow(dead_code)]
pub const ADMIN_WRITE_DEPRECATED_PREFIXES: &[&str] = &[
    "/jaxrs/ai",
    "/jaxrs/cms",
    "/jaxrs/correlation",
    "/jaxrs/file",
    "/jaxrs/program_center",
    "/jaxrs/query",
    "/jaxrs/bbs",
    "/jaxrs/meeting",
    "/jaxrs/message",
    "/jaxrs/processplatform",
    "/jaxrs/portal",
];

pub const ADMIN_WRITE_PREFIXES: &[&str] = &[
    "/jaxrs/person",
    "/jaxrs/unit",
    "/jaxrs/role",
    "/jaxrs/group",
    "/jaxrs/organization/person",
    "/jaxrs/organization/group",
];

// plan006 U5 前缀豁免：覆盖带动态路径段的只读查询端点
// 与 PERMISSION_REGISTRY Public 前缀对齐，确保 auth_middleware 豁免生效
pub const AUTH_EXEMPT_PREFIXES: &[&str] = &[
    "/jaxrs/processplatform/assemble/surface/application/list",
    "/jaxrs/processplatform/assemble/surface/control/workorworkcompleted",
    "/jaxrs/processplatform/assemble/surface/readrecord/list",
    "/jaxrs/processplatform/assemble/surface/record/list",
    "/jaxrs/processplatform/assemble/surface/sign/list",
    "/jaxrs/processplatform/assemble/surface/touch/expire",
    "/jaxrs/processplatform/assemble/surface/touch/passexpired",
    "/jaxrs/processplatform/assemble/surface/touch/touchdetained",
    "/jaxrs/processplatform/assemble/surface/work/count",
    "/jaxrs/processplatform/service/processing/touch/mergeitem",
    "/jaxrs/program_center/datastructure",
    "/jaxrs/program_center/dingding/get/callback",
    "/jaxrs/program_center/jest/clear/cache",
    "/jaxrs/program_center/market/cloud/unit/is/vip",
    "/jaxrs/program_center/market/installed/version",
    "/jaxrs/program_center/appstyle",
    "/jaxrs/program_center/cachedispatch",
    "/jaxrs/attendance/assemble/control/dingdingstatistic",
    "/jaxrs/attendance/assemble/control/qywxstatistic",
    "/jaxrs/meeting/assemble/control/config/system",
];
