/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.jpush.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.jpush.core.entity.PushDevice.class)
public class PushDevice_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<PushDevice,String> deviceId;
    public static volatile SingularAttribute<PushDevice,String> deviceType;
    public static volatile SingularAttribute<PushDevice,String> id;
    public static volatile SingularAttribute<PushDevice,String> person;
    public static volatile SingularAttribute<PushDevice,String> pushType;
    public static volatile SingularAttribute<PushDevice,String> unique;
}
