/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.message;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.message.Event.class)
public class Event_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Event,Integer> failure;
    public static volatile SingularAttribute<Event,String> id;
    public static volatile SingularAttribute<Event,String> job;
    public static volatile SingularAttribute<Event,String> target;
    public static volatile SingularAttribute<Event,String> type;
}
