/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.message;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.message.WorkCompletedEvent.class)
public class WorkCompletedEvent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<WorkCompletedEvent,String> application;
    public static volatile SingularAttribute<WorkCompletedEvent,String> id;
    public static volatile SingularAttribute<WorkCompletedEvent,String> job;
    public static volatile SingularAttribute<WorkCompletedEvent,String> type;
    public static volatile SingularAttribute<WorkCompletedEvent,String> workCompleted;
}
