/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.message;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.message.WorkEvent.class)
public class WorkEvent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<WorkEvent,String> application;
    public static volatile SingularAttribute<WorkEvent,String> id;
    public static volatile SingularAttribute<WorkEvent,String> job;
    public static volatile SingularAttribute<WorkEvent,String> type;
    public static volatile SingularAttribute<WorkEvent,String> work;
}
