/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.CategoryExt.class)
public class CategoryExt_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<CategoryExt,String> content;
    public static volatile SingularAttribute<CategoryExt,String> id;
}
