/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.CmsBatchOperation.class)
public class CmsBatchOperation_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<CmsBatchOperation,String> bundle;
    public static volatile SingularAttribute<CmsBatchOperation,String> description;
    public static volatile SingularAttribute<CmsBatchOperation,Integer> errorCount;
    public static volatile SingularAttribute<CmsBatchOperation,String> id;
    public static volatile SingularAttribute<CmsBatchOperation,Boolean> isRunning;
    public static volatile SingularAttribute<CmsBatchOperation,String> objType;
    public static volatile SingularAttribute<CmsBatchOperation,String> oldInfo;
    public static volatile SingularAttribute<CmsBatchOperation,String> optType;
}
