/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.DocumentCommentCommend.class)
public class DocumentCommentCommend_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DocumentCommentCommend,String> commendPerson;
    public static volatile SingularAttribute<DocumentCommentCommend,String> commentId;
    public static volatile SingularAttribute<DocumentCommentCommend,String> documentId;
    public static volatile SingularAttribute<DocumentCommentCommend,String> id;
}
