/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.DocumentCommend.class)
public class DocumentCommend_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DocumentCommend,String> commendPerson;
    public static volatile SingularAttribute<DocumentCommend,String> commentId;
    public static volatile SingularAttribute<DocumentCommend,String> commentTitle;
    public static volatile SingularAttribute<DocumentCommend,String> creatorPerson;
    public static volatile SingularAttribute<DocumentCommend,String> documentId;
    public static volatile SingularAttribute<DocumentCommend,String> id;
    public static volatile SingularAttribute<DocumentCommend,String> title;
    public static volatile SingularAttribute<DocumentCommend,String> type;
}
