/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.ReadRemind.class)
public class ReadRemind_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ReadRemind,String> appId;
    public static volatile SingularAttribute<ReadRemind,String> categoryId;
    public static volatile SingularAttribute<ReadRemind,String> documentId;
    public static volatile SingularAttribute<ReadRemind,String> id;
    public static volatile SingularAttribute<ReadRemind,Date> readTime;
    public static volatile SingularAttribute<ReadRemind,Boolean> readed;
    public static volatile SingularAttribute<ReadRemind,String> readerFlagName;
    public static volatile SingularAttribute<ReadRemind,String> readerFlagType;
    public static volatile SingularAttribute<ReadRemind,String> remindReader;
    public static volatile SingularAttribute<ReadRemind,Date> remindTime;
    public static volatile SingularAttribute<ReadRemind,Boolean> reminded;
    public static volatile SingularAttribute<ReadRemind,String> title;
}
