/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.Review.class)
public class Review_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Review,String> appAlias;
    public static volatile SingularAttribute<Review,String> appId;
    public static volatile SingularAttribute<Review,String> appName;
    public static volatile SingularAttribute<Review,String> categoryAlias;
    public static volatile SingularAttribute<Review,String> categoryId;
    public static volatile SingularAttribute<Review,String> categoryName;
    public static volatile SingularAttribute<Review,String> creatorIdentity;
    public static volatile SingularAttribute<Review,String> creatorPerson;
    public static volatile SingularAttribute<Review,String> creatorTopUnitName;
    public static volatile SingularAttribute<Review,String> creatorUnitName;
    public static volatile SingularAttribute<Review,Date> docCreateTime;
    public static volatile SingularAttribute<Review,String> docId;
    public static volatile SingularAttribute<Review,String> docSequence;
    public static volatile SingularAttribute<Review,String> docStatus;
    public static volatile SingularAttribute<Review,String> documentType;
    public static volatile SingularAttribute<Review,String> id;
    public static volatile SingularAttribute<Review,String> permissionObj;
    public static volatile SingularAttribute<Review,String> permissionObjType;
    public static volatile SingularAttribute<Review,Date> publishTime;
    public static volatile SingularAttribute<Review,String> title;
}
