[package]
name = "organization_assemble_personal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
serde_json = "1"
deadpool-postgres.workspace = true
uuid = { workspace = true, features = ["v4"] }
shared = { path = "../shared" }

[dev-dependencies]
tower.workspace = true
tokio = { workspace = true, features = ["full"] }

