/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.hotpic.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.hotpic.entity.HotPictureInfo.class)
public class HotPictureInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<HotPictureInfo,String> application;
    public static volatile SingularAttribute<HotPictureInfo,String> creator;
    public static volatile SingularAttribute<HotPictureInfo,String> id;
    public static volatile SingularAttribute<HotPictureInfo,String> infoId;
    public static volatile SingularAttribute<HotPictureInfo,String> picId;
    public static volatile SingularAttribute<HotPictureInfo,String> summary;
    public static volatile SingularAttribute<HotPictureInfo,String> title;
}
