/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.base.core.entity;

import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.base.core.entity.JpaObject.class)
public class JpaObject_ {
    public static volatile SingularAttribute<JpaObject,Date> createTime;
    public static volatile SingularAttribute<JpaObject,String> sequence;
    public static volatile SingularAttribute<JpaObject,Date> updateTime;
}
