/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.base.core.entity;

import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.base.core.entity.StorageObject.class)
public class StorageObject_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StorageObject,String> encryptKey;
}
