/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Application.class)
public class Application_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Application,String> abort;
    public static volatile SingularAttribute<Application,String> category;
    public static volatile SingularAttribute<Application,Integer> commentCount;
    public static volatile SingularAttribute<Application,String> describe;
    public static volatile SingularAttribute<Application,Integer> downloadCount;
    public static volatile SingularAttribute<Application,Double> grade;
    public static volatile SingularAttribute<Application,String> icon;
    public static volatile SingularAttribute<Application,String> id;
    public static volatile SingularAttribute<Application,String> installSteps;
    public static volatile SingularAttribute<Application,Date> lastUpdateTime;
    public static volatile SingularAttribute<Application,String> name;
    public static volatile SingularAttribute<Application,Integer> orderNumber;
    public static volatile SingularAttribute<Application,Double> price;
    public static volatile SingularAttribute<Application,Date> publishTime;
    public static volatile SingularAttribute<Application,String> publisher;
    public static volatile SingularAttribute<Application,Integer> recommend;
    public static volatile SingularAttribute<Application,String> subCategory;
    public static volatile SingularAttribute<Application,String> version;
}
