/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.AppPackApkFile.class)
public class AppPackApkFile_ extends StorageObject_  {
    public static volatile SingularAttribute<AppPackApkFile,String> appVersionName;
    public static volatile SingularAttribute<AppPackApkFile,String> appVersionNo;
    public static volatile SingularAttribute<AppPackApkFile,Boolean> deepPath;
    public static volatile SingularAttribute<AppPackApkFile,String> extension;
    public static volatile SingularAttribute<AppPackApkFile,String> id;
    public static volatile SingularAttribute<AppPackApkFile,String> isPackAppIdOuter;
    public static volatile SingularAttribute<AppPackApkFile,Date> lastUpdateTime;
    public static volatile SingularAttribute<AppPackApkFile,Long> length;
    public static volatile SingularAttribute<AppPackApkFile,String> name;
    public static volatile SingularAttribute<AppPackApkFile,String> packInfoId;
    public static volatile SingularAttribute<AppPackApkFile,Integer> status;
    public static volatile SingularAttribute<AppPackApkFile,String> storage;
}
