/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Attachment.class)
public class Attachment_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Attachment,String> application;
    public static volatile SingularAttribute<Attachment,String> icon;
    public static volatile SingularAttribute<Attachment,String> id;
    public static volatile SingularAttribute<Attachment,Date> lastUpdateTime;
    public static volatile SingularAttribute<Attachment,String> name;
    public static volatile SingularAttribute<Attachment,String> person;
    public static volatile SingularAttribute<Attachment,String> type;
}
