/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Captcha.class)
public class Captcha_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Captcha,String> answer;
    public static volatile SingularAttribute<Captcha,String> id;
    public static volatile SingularAttribute<Captcha,String> meta;
}
