/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.DeployLog.class)
public class DeployLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DeployLog,String> id;
    public static volatile SingularAttribute<DeployLog,String> installPerson;
    public static volatile SingularAttribute<DeployLog,Date> installTime;
    public static volatile SingularAttribute<DeployLog,String> name;
    public static volatile SingularAttribute<DeployLog,String> remark;
    public static volatile SingularAttribute<DeployLog,String> title;
    public static volatile SingularAttribute<DeployLog,String> type;
    public static volatile SingularAttribute<DeployLog,String> version;
}
