/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.InstallLog.class)
public class InstallLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<InstallLog,String> category;
    public static volatile SingularAttribute<InstallLog,String> data;
    public static volatile SingularAttribute<InstallLog,String> id;
    public static volatile SingularAttribute<InstallLog,String> installPerson;
    public static volatile SingularAttribute<InstallLog,Date> installTime;
    public static volatile SingularAttribute<InstallLog,String> name;
    public static volatile SingularAttribute<InstallLog,String> status;
    public static volatile SingularAttribute<InstallLog,String> unInstallPerson;
    public static volatile SingularAttribute<InstallLog,Date> unInstallTime;
    public static volatile SingularAttribute<InstallLog,String> version;
}
