/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.MPWeixinMenu.class)
public class MPWeixinMenu_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MPWeixinMenu,String> appid;
    public static volatile SingularAttribute<MPWeixinMenu,String> content;
    public static volatile SingularAttribute<MPWeixinMenu,String> id;
    public static volatile SingularAttribute<MPWeixinMenu,String> key;
    public static volatile SingularAttribute<MPWeixinMenu,String> name;
    public static volatile SingularAttribute<MPWeixinMenu,String> order;
    public static volatile SingularAttribute<MPWeixinMenu,String> pagepath;
    public static volatile SingularAttribute<MPWeixinMenu,String> parentId;
    public static volatile SingularAttribute<MPWeixinMenu,String> type;
    public static volatile SingularAttribute<MPWeixinMenu,String> url;
}
