/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.ScheduleLog.class)
public class ScheduleLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ScheduleLog,String> application;
    public static volatile SingularAttribute<ScheduleLog,String> className;
    public static volatile SingularAttribute<ScheduleLog,Long> elapsed;
    public static volatile SingularAttribute<ScheduleLog,Date> fireTime;
    public static volatile SingularAttribute<ScheduleLog,String> id;
    public static volatile SingularAttribute<ScheduleLog,String> node;
    public static volatile SingularAttribute<ScheduleLog,String> stackTrace;
    public static volatile SingularAttribute<ScheduleLog,Boolean> success;
    public static volatile SingularAttribute<ScheduleLog,String> type;
}
