/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Structure.class)
public class Structure_ extends StorageObject_  {
    public static volatile SingularAttribute<Structure,String> data;
    public static volatile SingularAttribute<Structure,Boolean> deepPath;
    public static volatile SingularAttribute<Structure,String> description;
    public static volatile SingularAttribute<Structure,String> descriptionLob;
    public static volatile SingularAttribute<Structure,String> extension;
    public static volatile SingularAttribute<Structure,String> id;
    public static volatile SingularAttribute<Structure,Date> lastUpdateTime;
    public static volatile SingularAttribute<Structure,Long> length;
    public static volatile SingularAttribute<Structure,String> name;
    public static volatile SingularAttribute<Structure,String> storage;
}
