/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.WarnLog.class)
public class WarnLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<WarnLog,Boolean> collected;
    public static volatile SingularAttribute<WarnLog,String> id;
    public static volatile SingularAttribute<WarnLog,String> loggerName;
    public static volatile SingularAttribute<WarnLog,String> message;
    public static volatile SingularAttribute<WarnLog,Date> occurTime;
    public static volatile SingularAttribute<WarnLog,String> version;
}
