/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity.validation;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.validation.Bar.class)
public class Bar_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Bar,String> id;
    public static volatile SingularAttribute<Bar,String> name;
    public static volatile SingularAttribute<Bar,BarProperties> properties;
    public static volatile SingularAttribute<Bar,String> s1;
    public static volatile SingularAttribute<Bar,String> s2;
    public static volatile SingularAttribute<Bar,String> s3;
    public static volatile SingularAttribute<Bar,String> s4;
    public static volatile ListAttribute<Bar,String> sl1;
    public static volatile ListAttribute<Bar,String> sl2;
    public static volatile ListAttribute<Bar,String> sl3;
    public static volatile ListAttribute<Bar,String> sl4;
}
