/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity.validation;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.validation.Foo.class)
public class Foo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Foo,String> id;
    public static volatile SingularAttribute<Foo,String> name;
    public static volatile SingularAttribute<Foo,FooProperties> properties;
    public static volatile SingularAttribute<Foo,String> s1;
    public static volatile SingularAttribute<Foo,String> s2;
    public static volatile SingularAttribute<Foo,String> s3;
    public static volatile SingularAttribute<Foo,String> s4;
}
