/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity.validation;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.validation.Meta.class)
public class Meta_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Meta,Boolean> booleanValue;
    public static volatile ListAttribute<Meta,Boolean> booleanValueList;
    public static volatile MapAttribute<Meta,String,Boolean> booleanValueMap;
    public static volatile SingularAttribute<Meta,Date> dateTimeValue;
    public static volatile ListAttribute<Meta,Date> dateTimeValueList;
    public static volatile MapAttribute<Meta,String,Date> dateTimeValueMap;
    public static volatile SingularAttribute<Meta,Date> dateValue;
    public static volatile SingularAttribute<Meta,Double> doubleValue;
    public static volatile ListAttribute<Meta,Double> doubleValueList;
    public static volatile MapAttribute<Meta,String,Double> doubleValueMap;
    public static volatile SingularAttribute<Meta,Float> floatValue;
    public static volatile ListAttribute<Meta,Float> floatValueList;
    public static volatile MapAttribute<Meta,String,Float> floatValueMap;
    public static volatile SingularAttribute<Meta,String> id;
    public static volatile SingularAttribute<Meta,Integer> integerValue;
    public static volatile ListAttribute<Meta,Integer> integerValueList;
    public static volatile MapAttribute<Meta,String,Integer> integerValueMap;
    public static volatile SingularAttribute<Meta,Long> longValue;
    public static volatile ListAttribute<Meta,Long> longValueList;
    public static volatile MapAttribute<Meta,String,Long> longValueMap;
    public static volatile SingularAttribute<Meta,MetaProperties> properties;
    public static volatile SingularAttribute<Meta,String> stringLobValue;
    public static volatile SingularAttribute<Meta,String> stringValue;
    public static volatile ListAttribute<Meta,String> stringValueList;
    public static volatile MapAttribute<Meta,String,String> stringValueMap;
    public static volatile SingularAttribute<Meta,Date> timeValue;
}
