// AUTO-GENERATED by scripts/gen_mcp_tools.py — DO NOT EDIT
// This file defines GENERATED_ROUTE_DEFS as a Vec<RouteDef>

/// 自动生成的 MCP 工具路由定义（Vec 版本，避免宏依赖）
pub static GENERATED_ROUTE_DEFS: &[RouteDef] = &[
    RouteDef {
        tool_name: "jaxrs_query_service_processing_query_service_processing_reset",
        method: HttpMethod::Post,
        path: "/jaxrs/query/service/processing/reset",
        description: "reset_service handler",
        path_params: &[],
        body_params: &[],
    },
];

/// 生成的工具总数
pub const GENERATED_TOOL_COUNT: usize = 746;