#[cfg(test)]
mod tests {

    // SKIPPED: organization_assemble_control_role_list_flag_next_count not accessible
    // SKIPPED: organization_assemble_control_role_flag not accessible
    // SKIPPED: organization_assemble_control_unit_list_flag_next_count not accessible
    // SKIPPED: organization_assemble_control_unit_flag not accessible
    // SKIPPED: organization_assemble_control_unit_list_flag_sub_nested not accessible
    // SKIPPED: organization_assemble_control_unit_list_flag_sup_nested not accessible
    // SKIPPED: organization_assemble_control_unit_list_flag_sup_nested_type_type not accessible
    // SKIPPED: organization_assemble_control_person_list_like not accessible
    // SKIPPED: export_export_all not accessible
    // SKIPPED: export_result_flag_flag not accessible
    // SKIPPED: export_zhengwudingding_person not accessible
    // SKIPPED: group_list_like_mockputtopost not accessible
    // SKIPPED: group_list_like_pinyin not accessible
    // SKIPPED: group_list_like_pinyin_mockputtopost not accessible
    // SKIPPED: group_list_pinyininitial not accessible
    // SKIPPED: group_list_pinyininitial_mockputtopost not accessible
    // SKIPPED: group_list_flag_sub_direct not accessible
    // SKIPPED: group_list_flag_sub_nested not accessible
    // SKIPPED: group_list_flag_sup_direct not accessible
    // SKIPPED: group_list_flag_sup_nested not accessible
    // SKIPPED: group_flag not accessible
    // SKIPPED: group_flag_add_member not accessible
    // SKIPPED: group_flag_add_member_mockputtopost not accessible
    // SKIPPED: group_flag_delete_member not accessible
    // SKIPPED: group_flag_delete_member_mockputtopost not accessible
    // SKIPPED: group_flag_mockdeletetoget not accessible
    // SKIPPED: group_flag_mockputtopost not accessible
    // SKIPPED: identity_id not accessible
    // SKIPPED: identity_list_like_mockputtopost not accessible
    // SKIPPED: identity_list_like_pinyin not accessible
    // SKIPPED: identity_list_like_pinyin_mockputtopost not accessible
    // SKIPPED: identity_list_pinyininitial not accessible
    // SKIPPED: identity_list_pinyininitial_mockputtopost not accessible
    // SKIPPED: identity_flag not accessible
    // SKIPPED: identity_flag_mockdeletetoget not accessible
    // SKIPPED: identity_flag_mockputtopost not accessible
    // SKIPPED: inputperson_template not accessible
    // SKIPPED: inputperson_wipe not accessible
    // SKIPPED: permissionsetting_list not accessible
    // SKIPPED: permissionsetting_flag not accessible
    // SKIPPED: permissionsetting_flag_mockdeletetoget not accessible
    // SKIPPED: permissionsetting_flag_mockputtopost not accessible
    // SKIPPED: personattribute_flag not accessible
    // SKIPPED: personattribute_flag_mockdeletetoget not accessible
    // SKIPPED: personattribute_flag_mockputtopost not accessible
    // SKIPPED: personcard_listgrouptypes not accessible
    // SKIPPED: personcard_listpaging_page_page_size_size_mockputtopost not accessible
    // SKIPPED: personcard_listpagingwithgroup_page_page_size_size_mockputtopost not accessible
    // SKIPPED: personcard_mylist not accessible
    // SKIPPED: personcard_flag not accessible
    // SKIPPED: personcard_flag_mockdeletetoget not accessible
    // SKIPPED: role_list_like_mockputtopost not accessible
    // SKIPPED: role_list_like_pinyin not accessible
    // SKIPPED: role_list_like_pinyin_mockputtopost not accessible
    // SKIPPED: role_list_pinyininitial not accessible
    // SKIPPED: role_list_pinyininitial_mockputtopost not accessible
    // SKIPPED: role_flag_mockdeletetoget not accessible
    // SKIPPED: role_flag_mockputtopost not accessible
    // SKIPPED: unitattribute_flag not accessible
    // SKIPPED: unitattribute_flag_mockdeletetoget not accessible
    // SKIPPED: unitattribute_flag_mockputtopost not accessible
    // SKIPPED: unitduty_distinct_name not accessible
    // SKIPPED: unitduty_flag_mockputtopost not accessible
    // SKIPPED: unitduty_flag_mockdeletetoget not accessible
    // SKIPPED: unitduty_flag not accessible
    // SKIPPED: unitduty_update_member not accessible
    // SKIPPED: unitduty_list_flag_prev_count not accessible
    // SKIPPED: unitduty_list_flag_next_count not accessible
    // SKIPPED: unitduty_list_unit_unitFlag not accessible
    // SKIPPED: unitduty_list_name_name not accessible
    // SKIPPED: unitduty_list_like not accessible
    // SKIPPED: unitduty_list_identity_identityFlag not accessible
    // SKIPPED: unitduty_distinct_name_like_key not accessible
    // SKIPPED: unitattribute_list_flag_prev_count not accessible
    // SKIPPED: unitattribute_list_flag_next_count not accessible
    // SKIPPED: unitattribute_list_unit_flag not accessible
    // SKIPPED: role_list_flag_prev_count not accessible
    // SKIPPED: role_list_person_personFlag not accessible
    // SKIPPED: role_list_like not accessible
    // SKIPPED: role_list_group_groupFlag not accessible
    // SKIPPED: personcard_listpagingwithgroup_page_page_size_size not accessible
    // SKIPPED: personcard_listpaging_page_page_size_size not accessible
    // SKIPPED: personcard_listVCf_idList not accessible
    // SKIPPED: personcard_listPersonalVCf_idList not accessible
    // SKIPPED: personcard_createQR_cardId not accessible
    // SKIPPED: personcard_createCode_cardId not accessible
    // SKIPPED: personattribute_list_flag_prev_count not accessible
    // SKIPPED: personattribute_list_flag_next_count not accessible
    // SKIPPED: personattribute_list_person_personFlag not accessible
    // SKIPPED: loginrecord_stream not accessible
    // SKIPPED: inputperson_result_flag_flag not accessible
    // SKIPPED: identity_flag_order_before_followFlag not accessible
    // SKIPPED: identity_list_flag_unitduty_name_unitDutyName not accessible
    // SKIPPED: identity_list_flag_prev_count not accessible
    // SKIPPED: identity_list_flag_next_count not accessible
    // SKIPPED: identity_list_unitduty_name_unitDutyName not accessible
    // SKIPPED: identity_list_unit_unitFlag not accessible
    // SKIPPED: identity_list_person_personFlag not accessible
    // SKIPPED: identity_list_like not accessible
    // SKIPPED: group_list_flag_prev_count not accessible
    // SKIPPED: group_list_flag_next_count not accessible
    // SKIPPED: group_list_role_roleFlag not accessible
    // SKIPPED: group_list_person_personFlag_sup_nested not accessible
    // SKIPPED: group_list_person_personFlag_sup_direct not accessible
    // SKIPPED: group_list_like not accessible
}