/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.log;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.log.MergeItemPlan.class)
public class MergeItemPlan_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MergeItemPlan,String> application;
    public static volatile SingularAttribute<MergeItemPlan,String> applicationName;
    public static volatile SingularAttribute<MergeItemPlan,Date> completedTime;
    public static volatile SingularAttribute<MergeItemPlan,Long> count;
    public static volatile SingularAttribute<MergeItemPlan,Boolean> enable;
    public static volatile SingularAttribute<MergeItemPlan,Long> estimatedCount;
    public static volatile SingularAttribute<MergeItemPlan,String> id;
    public static volatile SingularAttribute<MergeItemPlan,String> lastUpdatePerson;
    public static volatile SingularAttribute<MergeItemPlan,Date> lastUpdateTime;
    public static volatile SingularAttribute<MergeItemPlan,String> name;
    public static volatile SingularAttribute<MergeItemPlan,String> process;
    public static volatile SingularAttribute<MergeItemPlan,String> processName;
    public static volatile SingularAttribute<MergeItemPlan,Date> startTime;
    public static volatile SingularAttribute<MergeItemPlan,String> status;
}
