/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2PersonConfig.class)
public class AttendanceV2PersonConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2PersonConfig,String> id;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Integer> offDutyFastCheckInBegin;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Boolean> offDutyFastCheckInEnable;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Integer> offDutyFastCheckInEnd;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Integer> onDutyFastCheckInBegin;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Boolean> onDutyFastCheckInEnable;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,Integer> onDutyFastCheckInEnd;
    public static volatile SingularAttribute<AttendanceV2PersonConfig,String> person;
}
