/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2AppealInfo.class)
public class AttendanceV2AppealInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> endTime;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> id;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> jobId;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> reason;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,Date> recordDate;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> recordDateString;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> recordId;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,Boolean> sendStatus;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> startTime;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,Integer> status;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> updateStatusAdminPerson;
    public static volatile SingularAttribute<AttendanceV2AppealInfo,String> userId;
}
