/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2GroupScheduleConfig.class)
public class AttendanceV2GroupScheduleConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2GroupScheduleConfig,String> groupId;
    public static volatile SingularAttribute<AttendanceV2GroupScheduleConfig,String> id;
    public static volatile SingularAttribute<AttendanceV2GroupScheduleConfig,String> scheduleConfigJson;
}
