/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2Shift.class)
public class AttendanceV2Shift_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2Shift,Integer> absenteeismLateMinutes;
    public static volatile SingularAttribute<AttendanceV2Shift,String> id;
    public static volatile SingularAttribute<AttendanceV2Shift,String> lateAndEarlyOffTime;
    public static volatile SingularAttribute<AttendanceV2Shift,String> lateAndEarlyOnTime;
    public static volatile SingularAttribute<AttendanceV2Shift,Boolean> needLimitWorkTime;
    public static volatile SingularAttribute<AttendanceV2Shift,String> operator;
    public static volatile SingularAttribute<AttendanceV2Shift,AttendanceV2ShiftCheckTimeProperties> properties;
    public static volatile SingularAttribute<AttendanceV2Shift,Integer> seriousTardinessLateMinutes;
    public static volatile SingularAttribute<AttendanceV2Shift,String> shiftName;
    public static volatile SingularAttribute<AttendanceV2Shift,Integer> workTime;
}
