/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2AlertMessage.class)
public class AttendanceV2AlertMessage_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2AlertMessage,String> checkInType;
    public static volatile SingularAttribute<AttendanceV2AlertMessage,String> id;
    public static volatile SingularAttribute<AttendanceV2AlertMessage,Date> sendDateTime;
    public static volatile SingularAttribute<AttendanceV2AlertMessage,Boolean> sendStatus;
    public static volatile SingularAttribute<AttendanceV2AlertMessage,String> userId;
}
