/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2CheckInRecord.class)
public class AttendanceV2CheckInRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> appealId;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> checkInResult;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> checkInType;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> description;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,Boolean> fieldWork;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> groupCheckType;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> groupId;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> groupName;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> id;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> latitude;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> leaveDataId;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> longitude;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,Boolean> offDutyNextDay;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> placeName;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> preDutyTime;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> preDutyTimeAfterLimit;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> preDutyTimeBeforeLimit;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> recordAddress;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,Date> recordDate;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> recordDateString;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> shiftId;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> shiftName;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> signDescription;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> sourceDevice;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> sourceType;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> userId;
    public static volatile SingularAttribute<AttendanceV2CheckInRecord,String> workPlaceId;
}
