/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2Group.class)
public class AttendanceV2Group_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2Group,Boolean> allowFieldWork;
    public static volatile ListAttribute<AttendanceV2Group,String> assistAdminList;
    public static volatile SingularAttribute<AttendanceV2Group,String> checkType;
    public static volatile SingularAttribute<AttendanceV2Group,Boolean> fieldWorkMarkError;
    public static volatile SingularAttribute<AttendanceV2Group,String> groupName;
    public static volatile SingularAttribute<AttendanceV2Group,String> id;
    public static volatile ListAttribute<AttendanceV2Group,String> noNeedCheckInDateList;
    public static volatile SingularAttribute<AttendanceV2Group,String> operator;
    public static volatile ListAttribute<AttendanceV2Group,String> participateList;
    public static volatile ListAttribute<AttendanceV2Group,String> requiredCheckInDateList;
    public static volatile SingularAttribute<AttendanceV2Group,Boolean> requiredFieldWorkRemarks;
    public static volatile SingularAttribute<AttendanceV2Group,String> shiftId;
    public static volatile SingularAttribute<AttendanceV2Group,Integer> status;
    public static volatile ListAttribute<AttendanceV2Group,String> trueParticipantList;
    public static volatile ListAttribute<AttendanceV2Group,String> unParticipateList;
    public static volatile SingularAttribute<AttendanceV2Group,String> workDateList;
    public static volatile SingularAttribute<AttendanceV2Group,AttendanceV2GroupWorkDayProperties> workDateProperties;
    public static volatile ListAttribute<AttendanceV2Group,String> workPlaceIdList;
}
