/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2WorkPlace.class)
public class AttendanceV2WorkPlace_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> creator;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> description;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,Integer> errorRange;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> gpsLat;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> gpsLng;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> id;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> latitude;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> longitude;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> placeAlias;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> placeName;
    public static volatile SingularAttribute<AttendanceV2WorkPlace,String> positionType;
}
