/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2GroupSchedule.class)
public class AttendanceV2GroupSchedule_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> groupId;
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> id;
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> scheduleDateString;
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> scheduleMonthString;
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> shiftId;
    public static volatile SingularAttribute<AttendanceV2GroupSchedule,String> userId;
}
