/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2Config.class)
public class AttendanceV2Config_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> appealEnable;
    public static volatile SingularAttribute<AttendanceV2Config,Integer> appealMaxTimes;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> checkInAlertEnable;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> closeOldAttendance;
    public static volatile SingularAttribute<AttendanceV2Config,String> detailStatisticCronString;
    public static volatile SingularAttribute<AttendanceV2Config,String> exceptionAlertDate;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> exceptionAlertEnable;
    public static volatile SingularAttribute<AttendanceV2Config,String> exceptionAlertTime;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> faceDetectionEnable;
    public static volatile SingularAttribute<AttendanceV2Config,String> id;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> offDutyFastCheckInEnable;
    public static volatile SingularAttribute<AttendanceV2Config,Boolean> onDutyFastCheckInEnable;
    public static volatile SingularAttribute<AttendanceV2Config,String> processId;
    public static volatile SingularAttribute<AttendanceV2Config,String> processName;
}
