/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2LeaveData.class)
public class AttendanceV2LeaveData_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2LeaveData,String> description;
    public static volatile SingularAttribute<AttendanceV2LeaveData,Date> endTime;
    public static volatile SingularAttribute<AttendanceV2LeaveData,String> id;
    public static volatile SingularAttribute<AttendanceV2LeaveData,String> jobId;
    public static volatile SingularAttribute<AttendanceV2LeaveData,Double> leaveDayNumber;
    public static volatile SingularAttribute<AttendanceV2LeaveData,String> leaveType;
    public static volatile SingularAttribute<AttendanceV2LeaveData,String> person;
    public static volatile SingularAttribute<AttendanceV2LeaveData,Date> startTime;
}
