/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity.v2;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.v2.AttendanceV2Detail.class)
public class AttendanceV2Detail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> absenteeismDays;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> attendance;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> fieldWorkTimes;
    public static volatile SingularAttribute<AttendanceV2Detail,String> groupId;
    public static volatile SingularAttribute<AttendanceV2Detail,String> groupName;
    public static volatile SingularAttribute<AttendanceV2Detail,String> id;
    public static volatile SingularAttribute<AttendanceV2Detail,Long> lateTimeDuration;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> lateTimes;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> leaveDays;
    public static volatile SingularAttribute<AttendanceV2Detail,Long> leaveEarlierTimeDuration;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> leaveEarlierTimes;
    public static volatile SingularAttribute<AttendanceV2Detail,String> monthString;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> offDutyAbsenceTimes;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> onDutyAbsenceTimes;
    public static volatile SingularAttribute<AttendanceV2Detail,String> recordDateString;
    public static volatile SingularAttribute<AttendanceV2Detail,String> recordDay;
    public static volatile ListAttribute<AttendanceV2Detail,String> recordIdList;
    public static volatile SingularAttribute<AttendanceV2Detail,Integer> rest;
    public static volatile SingularAttribute<AttendanceV2Detail,String> shiftId;
    public static volatile SingularAttribute<AttendanceV2Detail,String> shiftName;
    public static volatile SingularAttribute<AttendanceV2Detail,String> userId;
    public static volatile SingularAttribute<AttendanceV2Detail,Boolean> workDay;
    public static volatile SingularAttribute<AttendanceV2Detail,Long> workTimeDuration;
    public static volatile SingularAttribute<AttendanceV2Detail,String> yearString;
}
