/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.correlation.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.correlation.core.entity.content.Correlation.class)
public class Correlation_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Correlation,String> fromBundle;
    public static volatile SingularAttribute<Correlation,String> fromType;
    public static volatile SingularAttribute<Correlation,String> id;
    public static volatile SingularAttribute<Correlation,Integer> orderNumber;
    public static volatile SingularAttribute<Correlation,String> person;
    public static volatile SingularAttribute<Correlation,CorrelationProperties> properties;
    public static volatile SingularAttribute<Correlation,String> site;
    public static volatile SingularAttribute<Correlation,String> targetBundle;
    public static volatile SingularAttribute<Correlation,String> targetType;
}
