/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.schema;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.schema.ExternalConnection.class)
public class ExternalConnection_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ExternalConnection,String> description;
    public static volatile SingularAttribute<ExternalConnection,String> driverClassName;
    public static volatile SingularAttribute<ExternalConnection,Boolean> enable;
    public static volatile SingularAttribute<ExternalConnection,String> id;
    public static volatile SingularAttribute<ExternalConnection,String> name;
    public static volatile SingularAttribute<ExternalConnection,String> pass;
    public static volatile SingularAttribute<ExternalConnection,String> schema;
    public static volatile SingularAttribute<ExternalConnection,String> url;
    public static volatile SingularAttribute<ExternalConnection,String> user;
}
