#[cfg(test)]
mod tests {

    // SKIPPED: get_designer not accessible
    // SKIPPED: create_designer not accessible
    // SKIPPED: list_designers not accessible
    // SKIPPED: save_designer not accessible
    // SKIPPED: delete_designer not accessible
    // SKIPPED: designer_search not accessible
    // SKIPPED: id_count not accessible
    // SKIPPED: importmodel_list_query_flag not accessible
    // SKIPPED: importmodel_id not accessible
    // SKIPPED: importmodel_id_permission not accessible
    // SKIPPED: input_compare not accessible
    // SKIPPED: input_cover not accessible
    // SKIPPED: input_create not accessible
    // SKIPPED: input_prepare_cover not accessible
    // SKIPPED: input_prepare_create not accessible
    // SKIPPED: neural_generate_model_modelFlag not accessible
    // SKIPPED: neural_learn_model_modelFlag not accessible
    // SKIPPED: neural_list_model not accessible
    // SKIPPED: neural_model not accessible
    // SKIPPED: neural_model_modelFlag not accessible
    // SKIPPED: neural_model_modelFlag_reset_status not accessible
    // SKIPPED: neural_stop_generating_model_modelFlag not accessible
    // SKIPPED: neural_stop_learn_model_modelFlag not accessible
    // SKIPPED: output_list not accessible
    // SKIPPED: output_flag_select_file not accessible
    // SKIPPED: output_queryFlag_select not accessible
    // SKIPPED: query_entity_entity_category_entityCategory_properties not accessible
    // SKIPPED: query_list_all not accessible
    // SKIPPED: query_list_querycategory_queryCategory not accessible
    // SKIPPED: query_list_summary not accessible
    // SKIPPED: query_list_summary_querycategory_queryCategory not accessible
    // SKIPPED: query_querycategory_list not accessible
    // SKIPPED: query_flag not accessible
    // SKIPPED: query_flag_icon not accessible
    // SKIPPED: query_id_permission not accessible
    // SKIPPED: stat_list_query_flag not accessible
    // SKIPPED: stat_list_id_next_count not accessible
    // SKIPPED: stat_list_id_prev_count not accessible
    // SKIPPED: stat_id not accessible
    // SKIPPED: stat_id_permission not accessible
    // SKIPPED: stat_id_simulate not accessible
    // SKIPPED: table_export_tableFlag_count_count not accessible
    // SKIPPED: table_list_manage not accessible
    // SKIPPED: table_list_query_flag not accessible
    // SKIPPED: table_list_tableFlag_row_select_where_where not accessible
    // SKIPPED: table_list_tableFlag_row_id_next_count not accessible
    // SKIPPED: table_list_tableFlag_row_id_prev_count not accessible
    // SKIPPED: table_query_query_build not accessible
    // SKIPPED: table_reload_dynamic not accessible
    // SKIPPED: table_flag not accessible
    // SKIPPED: table_flag_execute not accessible
    // SKIPPED: table_flag_status_build not accessible
    // SKIPPED: table_flag_status_draft not accessible
    // SKIPPED: table_id_permission not accessible
    // SKIPPED: table_query_build_dispatch not accessible
    // SKIPPED: table_tableFlag_row not accessible
    // SKIPPED: table_tableFlag_row_count_where_where not accessible
    // SKIPPED: table_tableFlag_row_delete_all not accessible
    // SKIPPED: table_tableFlag_row_save not accessible
    // SKIPPED: table_tableFlag_row_id not accessible
    // SKIPPED: view_list_query_flag not accessible
    // SKIPPED: view_list_id_next_count not accessible
    // SKIPPED: view_list_id_prev_count not accessible
    // SKIPPED: view_id not accessible
    // SKIPPED: view_id_bundle not accessible
    // SKIPPED: view_id_permission not accessible
    // SKIPPED: view_id_simulate not accessible
}