/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.ai.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.ai.core.entity.AiModel.class)
public class AiModel_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AiModel,String> apiKey;
    public static volatile SingularAttribute<AiModel,Boolean> asDefault;
    public static volatile SingularAttribute<AiModel,String> completionUrl;
    public static volatile SingularAttribute<AiModel,String> desc;
    public static volatile SingularAttribute<AiModel,Boolean> enable;
    public static volatile SingularAttribute<AiModel,String> id;
    public static volatile SingularAttribute<AiModel,String> model;
    public static volatile SingularAttribute<AiModel,String> name;
    public static volatile SingularAttribute<AiModel,Boolean> proxyEnable;
    public static volatile SingularAttribute<AiModel,String> proxyHost;
    public static volatile SingularAttribute<AiModel,String> proxyPass;
    public static volatile SingularAttribute<AiModel,Integer> proxyPort;
    public static volatile SingularAttribute<AiModel,String> proxyUser;
    public static volatile SingularAttribute<AiModel,String> type;
}
