/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.ai.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.ai.core.entity.Clue.class)
public class Clue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Clue,String> id;
    public static volatile SingularAttribute<Clue,String> person;
    public static volatile SingularAttribute<Clue,String> title;
}
