/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.ai.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.ai.core.entity.Completion.class)
public class Completion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Completion,String> clueId;
    public static volatile SingularAttribute<Completion,String> content;
    public static volatile SingularAttribute<Completion,String> generateType;
    public static volatile SingularAttribute<Completion,String> id;
    public static volatile SingularAttribute<Completion,String> input;
    public static volatile SingularAttribute<Completion,String> person;
    public static volatile ListAttribute<Completion,String> referenceIdList;
}
