/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.ai.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.ai.core.entity.File.class)
public class File_ extends StorageObject_  {
    public static volatile SingularAttribute<File,String> creator;
    public static volatile SingularAttribute<File,Boolean> deepPath;
    public static volatile SingularAttribute<File,String> extension;
    public static volatile SingularAttribute<File,String> fileId;
    public static volatile SingularAttribute<File,String> id;
    public static volatile SingularAttribute<File,Date> lastUpdateTime;
    public static volatile SingularAttribute<File,Long> length;
    public static volatile SingularAttribute<File,String> name;
    public static volatile SingularAttribute<File,String> storage;
}
